### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by LunarDevelopment** [scotch-io/scotch-box#101]
Hello! 

I'm new to VM / linux, so it could be something basic I'm missing here..

I start up the cotchbox server through VirtualBox and I have access to the shell through the Virtual Box's "Show" button.

However I then get prompted to log in to scotchbox with: 

``` 
scotchbox login: 
password: 
```
But when I use my scotch.io login details I simply get the "Login Incorrect " text.. 

Any ideas appart from the obvious "I'm getting my login wrong" which I'm pretty certain isn't the case.. 

Lewis

**Comment by grizfan** [comment]
Use `vagrant ssh` instead. Think of VirtualBox as just a tool that Vagrant uses. Vagrant will be your primary means of interacting with the VM. The https://docs.vagrantup.com/v2/ site has some great tutorials for beginners (I'm still quite new to all of this). Spend some time with the Vagrant docs, and you should be in great shape.

**Comment by ncerminara** [comment]
Thanks @grizfan
