### ISSUE TITLE
Facing issues installing scotch box

### ISSUE THREAD

**Issue by deep80** [scotch-io/scotch-box#103]
Hello Chris, Nick

My Name is Deep.

I read about scotchbox and decided to give it a try. I went through the instructions mentioned at the site and followed along i.e. cloned the git repo and typed ‘vagrant up’.

Since the box isn’t found by vagrant, it started downloading the box. Fine!!

Couple of minutes later the download got disrupted. Reason Unknown!!

I repeated this couple of times and same thing happened over and over again.

So I looked for another route and download the box manually following the URL mentioned below:

https://drive.scotch.io/scotchbox/2.0.0/scotch.box

Download was successful and was added successfully to the system too.

When I typed vagrant up in the terminal and after cloning the repo, the virtual machine started however the ssh (Private Key) was unsuccessful. It says ‘connection timed out: retrying’ couple of time.

Please advise me on this. Scotch Box seems interesting and would really love to use it.

**Comment by ncerminara** [comment]
Try adding this to the Vagrant file:

```
config.ssh.username = "vagrant"
config.ssh.password = "vagrant"
```

**Comment by deep80** [comment]
Hello Nick,



Thanks for the support but the problem still persists.



Added the code (Copied and Pasted) you mentioned at the vagrant file.



For better understanding, I’m sending you the system screenshot and the
vagrant file where I added the code.



I’m new to Vagrant. Just learnt the basics of it including adding boxes!



Hope the attachments will help you come know the problem better.



Hope to hear from you very soon.



Regards



Deep

On Tue, Aug 18, 2015 at 7:06 AM, Nicholas Cerminara <
notifications@github.com> wrote:

> Try adding this to the Vagrant file:
>
> config.ssh.username = "vagrant"
> config.ssh.password = "vagrant"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scotch-io/scotch-box/issues/103#issuecomment-132220763>
> .
>



-- 
Thanks and Regards

Deep

PROPERBOUNCE TECHNOLOGIES
PH: +91 9007173746
SKYPE: deep.karmakar2

**Comment by barooney** [comment]
I recently had the same problem when I tried to boot up my scotchbox. Somehow, the filesystem got corrupted after a system crash and a message from ```fsck``` appeared asking for permission to repair the filesystem.

This does not happen via Vagrant, because it tries to connect to the VM via SSH, which in fact is not up and running at that point of time.

Try to boot the VM via Virtual Box and then follow the directions given.

Hopefully, this helps.
