### ISSUE TITLE
Facing issues installing scotch box

### ISSUE THREAD

**Issue by deep80** [scotch-io/scotch-box#104]
Hello Nick, 

Thanks for the support but the problem still persists. Added the code (Copied and Pasted) you mentioned at the vagrant file. 

For better understanding, I’m sending you the system screenshot. I’m new to Vagrant. Just learnt the basics of it including adding boxes! 

Hope the attachments will help you come know the problem better. Hope to hear from you very soon. 

Regards Deep

![scotchbox](https://cloud.githubusercontent.com/assets/10944348/9349691/feb10f7a-4666-11e5-896b-7484e8ff2387.jpg)

**Comment by ncerminara** [comment]
Is any of this helpful: http://stackoverflow.com/questions/22575261/vagrant-stuck-connection-timeout-retrying

Seems this isn't really Scotch Box but a Vagrant issue.

**Comment by ncerminara** [comment]
Merging with your other open issue: https://github.com/scotch-io/scotch-box/issues/103
