### ISSUE TITLE
Update Guest Additions Version

### ISSUE THREAD

**Issue by guilhermemarconi** [scotch-io/scotch-box#106]
Hey guys.

I updated the box and start configuring Virtual Hosts from the box, but I found something that I think have to be done here in the Box, not in my local Vagrant installation, that is update Guest Additions to support VirtualBox 5.

I'm using Windows 10 and, like I said in [this other issue][1], VirtualBox 4 doesn't work with it.

Thanks! :smiley: 

[1]:https://github.com/scotch-io/scotch-box/issues/91

**Comment by ncerminara** [comment]
Nice info here... Which version of Virtual Box 5? So basically I just need to repackage the box with v5?

Have you seen: https://github.com/dotless-de/vagrant-vbguest

**Comment by ncerminara** [comment]
I was under the impression Virtual Box 5 still did not work with Vagrant

**Comment by guilhermemarconi** [comment]
@ncerminara

Actually I'm not completely sure, but I think, from the Vagrant 1.7.4, we already have support VirtualBox 5 (I use 5.0.2).

Anyway, anyone can follow [these steps][1] to use the Vagrant with VirtualBox 5.

PS: I did not know this vagrant-vbguest. It can solve my problem?

[1]:https://github.com/mitchellh/vagrant/issues/5572#issuecomment-93250550

**Comment by ncerminara** [comment]
This might not be possible yet with a Vagrant bug: https://github.com/mitchellh/vagrant/issues/5186
