### ISSUE TITLE
ssh keys for the box

### ISSUE THREAD

**Issue by stevieg83** [scotch-io/scotch-box#107]
If you have a team working on 1 Scotchbox instance, it makes sense to generate a public key that can be used to access dev, test & production for example.

How can we add this once, for all?

**Comment by ncerminara** [comment]
Vagrant uses an insecure public key. It's located somewhere when it's installed.

You can just use `vagrant share` for https or ssh share https://scotch.io/tutorials/sharing-your-virtual-machine-on-the-web-with-vagrant-share#ssh-sharing


```
vagrant share --ssh
```

**Comment by ncerminara** [comment]
Also I don't think that makes sense for collaborating. Everyone should have their own key pair

**Comment by ncerminara** [comment]
To elaborate. Your team should each have their own Scotch Box. Then just pass the code around with Git

**Comment by stevieg83** [comment]
I think you've maybe missed the intention in this request to be fair.

I want to be able to ssh into a variation of servers from within Scotchbox using 1 public key. For example, a new developer joins our team, they clone/fork the repo that contains Scotchbox and our project source code, they need a copy of the production database and so when the box provisions, it runs a shell script to ssh into the production server, take a db dump and then sync that back into the Scotchbox setup.

**Comment by ncerminara** [comment]
Ah - Makes sense. Can't you just add it in the Vagrantfile via a shell script?

**Comment by stevieg83** [comment]
wouldn't that generate a different key each time you launch the box?

I like how www.puphpet.com handles this because the key actually gets added to Git.

**Comment by ncerminara** [comment]
I'm sure there's a way to do it with Shell scripts.

PuPHPet isn't setup on this version of ScotchBox. You can use the older version: https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#want-the-older-box-back

Another option is to add the key manually and repackage the box and serve it internally to your team: https://scotch.io/tutorials/how-to-create-a-vagrant-base-box-from-an-existing-one. It's actually really easy

But it seems PuPHPet might actually be your best option here.

**Comment by stevieg83** [comment]
Yeah, PuPHPet has always been kinda flaky for us which is why we opted for
this awesome box :)

I think adding the key manually and repackaging the box is a great idea -
didn't know that was doable.

On 25 August 2015 at 22:23, Nicholas Cerminara <notifications@github.com>
wrote:

> I'm sure there's a way to do it with Shell scripts.
>
> PuPHPet isn't setup on this version of ScotchBox. You can use the older
> version:
> https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#want-the-older-box-back
>
> Another option is to add the key manually and repackage the box and serve
> it internally to your team:
> https://scotch.io/tutorials/how-to-create-a-vagrant-base-box-from-an-existing-one.
> It's actually really easy
>
> But it seems PuPHPet might actually be your best option here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scotch-io/scotch-box/issues/107#issuecomment-134745559>
> .
>



-- 
Steven Grant

**Comment by ncerminara** [comment]
Awesome. Going to close this.

Final thought: SSH and stuff is already setup on the box. You could probably get away with just dumping/copying the key file to "~/.ssh/" on the box on vagrant up. Then just have your team do:

```
vagrant ssh
ssh -i ~/.ssh/custom_key root@123.45.67.89
```
