### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by markmarijnissen** [scotch-io/scotch-box#108]
Hello,

is HTTPS supported?

Thanks

**Comment by ncerminara** [comment]
You manually need to set it up locally (generate your own self-signed certficiate, a bunch of stuff, etc.)

You can also do:

```
vagrant share --https 443
```

To generate an SSL local tunnel with Vagrant share

**Comment by marcelo2605** [comment]
After run `vagrant share --https 443`, http version works fine. But https return error 500.

Has anyone had this problem?
