### ISSUE TITLE
Additional documentation and example for multiple virtual hosts

### ISSUE THREAD

**Issue by andrewkamm** [scotch-io/scotch-box#109]
I've setup a repository that provides documentation and code for setting up an instance of Scotch Box aimed at easy setup of multiple virtual hosts within the same box using a YAML file. The documentation includes the steps involved in setting up dnsmasq on OS-X to allow use of wildcard domains.

The repo is here: <https://github.com/andrewkamm/sites-box>

Feel free to use any/all of it within the Scotch Box docs or repo as needed. Let me know if you need anything, and thanks for Scotch Box.

(per [this conversation on Twitter](https://twitter.com/scotch_io/status/636339494027952128))

**Comment by ncerminara** [comment]
Hey - just quickly wanted to say thanks for this and still on my to-do list to add this to the article/docs
