### ISSUE TITLE
Data Bags sites and HostManager

### ISSUE THREAD

**Issue by rickbenetti** [scotch-io/scotch-box#112]
Will be usefull for projects using custom wordpress installation if we could be set different path to our virtual host, like R8 use in there [Vagran Lamp](https://github.com/r8/vagrant-lamp/blob/master/data_bags/sites/local.json)

I'm used the last year R8 solution, but know with Vagrant 1.7.4 and VirtualBox 5 stoped work.

My default sites configuration is:
```
{
    "id": "local",
    "host": "local.dev",
    "aliases": [
        "www.local.dev", 
        "test.com",
        "www.test.com"
    ],
    "docroot": "/vagrant/public/wpprojects/my-project/web",
}
```

Obviously using Vagrant HostManager you can free to your team to work better.

**Comment by ncerminara** [comment]
The goal with Scotch Box is to keep it dead-simple for everyone and so things are super unlikely to break - including being dependency/plugin free.

I also am a believer in one Vagrantfile per site and just managing multiple VMs at once. So unfortunately probably won't be adding this.

You can technically set this up yourself though as it's all just Vagrant. Lots of people add the plugin separately.

Here's one way of doing multiple domains with Scotch Box: https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#multiple-domains-(virtual-hosts)

**Comment by ncerminara** [comment]
Here's another way someone uses Scotch Box: https://github.com/scotch-io/scotch-box/issues/109
