### ISSUE TITLE
Is there any easy way to update Bower?

### ISSUE THREAD

**Issue by satrya** [scotch-io/scotch-box#113]
I thought I can run `npm install -g bower` to update Bower inside `vagrant ssh` but it didn't worked. Like the title, is there any easy way to update it?

**Comment by robhadfield** [comment]
This is being discussed in Issue #47 I think.

**Comment by ncerminara** [comment]
https://github.com/scotch-io/scotch-box/issues/47 is more for a timeline and schedule of the project so people know what to expect. I'm looking into completing that still

For bower (node, or anything), there's some permission issues getting hashed out. Just do:


```
sudo npm install -g bower-update
```

Boom bower updated.
