### ISSUE TITLE
Multiple Wordpress DB's?

### ISSUE THREAD

**Issue by FlannelBeard** [scotch-io/scotch-box#115]
Trying to set up a workflow that has my public folder and vagrantfile within a root folder, ~/Documents. The idea is to have multiple projects in one source on one server ( 192.168.33.10/wordpress-one, 192.168.33.10/wordpress-two, etc... ).

I'm having an issue with having multiple DB's that are named differently in sequel pro. If I have a wp-config with a DB_NAME of "scotchbox" it installs fine. However if I try to use a DB_NAME such as "wordpress-one" or "wordpress-two" it will not connect, even if my DB_NAME is the same in both sequel pro and the wp-config for each project ... 

Does scotchbox only let you connect via the "scotchbox" DB_NAME, or can you have several DB_NAME's for each project and connect accordingly?

**Comment by FlannelBeard** [comment]
I can connect when my sequelpro and wp-config are defined as such:

    define('DB_NAME', 'scotchbox');
    define('DB_USER', 'root');
    define('DB_PASSWORD', 'root');
    define('DB_HOST', 'localhost');

But they will not connect like this:

    define('DB_NAME', 'wordpress-one');
    define('DB_USER', 'root');
    define('DB_PASSWORD', 'root');
    define('DB_HOST', 'localhost');

or:

    define('DB_NAME', 'wordpress-two');
    define('DB_USER', 'root');
    define('DB_PASSWORD', 'root');
    define('DB_HOST', 'localhost');

**Comment by ncerminara** [comment]
At the end of the day, it's just a MySQL server. You should be able to create as many databases as you want.

Something must be wrong with your MySQL connection? Screenshot of Sequel Pro?

**Comment by ncerminara** [comment]
Specifically Sequel pro dropdown with the databases

**Comment by FlannelBeard** [comment]
Here's a screenshot of everything I have. DB just won't connect. If I rename them both to "scotchbox" the installer works ... just not with custom names. See attached (and ty for the speedy help!)

![screen shot 2015-09-14 at 3 39 55 pm 2](https://cloud.githubusercontent.com/assets/8441088/9859923/f2ba1b36-5af6-11e5-971a-3d89d720ea80.png)

**Comment by FlannelBeard** [comment]
Shot of how I have things configured. Vagrant status is up. ![screen shot 2015-09-14 at 3 44 20 pm](https://cloud.githubusercontent.com/assets/8441088/9860006/7be7d1f0-5af7-11e5-9ff1-dcf90de12e04.png)

**Comment by ncerminara** [comment]
Sorry for ads on this site, but watch this: http://www.filedropper.com/example-multidb

This works. Something must be off with your multi-setup.

How are you doing multisite right now? https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#multiple-domains-(virtual-hosts)

**Comment by ncerminara** [comment]
Actually ignore that link it doesn't matter if you're setting up vhosts or subfolders.

It looks like in Sequel Pro, you're creating a "Connection" called "test", not a database. The video shows you how to actually create a new database.

**Comment by FlannelBeard** [comment]
First off thank you so much for helping me, I sincerelyappreciate it. I'll give all these links a go and try it  out asap. Scotch is a wonderful vagrant box and I'm sure once I get this setup running it'll be a fantastic workflow. 

Technically it is not a multisite, but rather many individual sites running on one server. Definitely not a true wordpress multisite stack. 

Thank you so much again

**Comment by ncerminara** [comment]
No problem!
