### ISSUE TITLE
Mysql returning ints as strings

### ISSUE THREAD

**Issue by sonicfive** [scotch-io/scotch-box#116]
After V2 mysql started returning ints as strings. I searched and found suggestions to use the mysqlnd.so driver. 
A quick fix for me was to use mutators on attributes for the affected models to cast to ints. In this case to use http://laravel.com/docs/5.1/eloquent-mutators
I am running the same code on production in digital ocean Ubuntu 14.04 with no problems.

**Comment by ncerminara** [comment]
Hmmm. This is super weird and doesn't make any sense.

Scotch Box 2 is only running MySQL 5.5 because MySQL 5.6 requires more memory than the default install of Vagrant will provide.

Any chance it's your SQL dump and not Scotch Box?

**Comment by sonicfive** [comment]
No, it's definitely not my sql dump. I have a system on production without
these issues. And also I have a 1.x scotchbox that runs without problems.
Additionally, I am using the same dump on 3 systems to make sure there is
no confusion there.

On Wed, Sep 16, 2015 at 9:13 AM, Nicholas Cerminara <
notifications@github.com> wrote:

> Hmmm. This is super weird and doesn't make any sense.
>
> Scotch Box 2 is only running MySQL 5.5 because MySQL 5.6 requires more
> memory than the default install of Vagrant will provide.
>
> Any chance it's your SQL dump and not Scotch Box?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scotch-io/scotch-box/issues/116#issuecomment-140772475>
> .
>



-- 
Alejandro

Think Before You Print. No trees were killed in the sending of this
message. However a large number of electrons were terribly inconvenienced.

**Comment by ncerminara** [comment]
Let me try and replicate on my own machine. I've never encountered this issue but will verify

**Comment by sonicfive** [comment]
I can share you my screen and show you production vs. scotchbox so you can
see it in action if you wish.

On Wed, Sep 16, 2015 at 9:29 AM, Nicholas Cerminara <
notifications@github.com> wrote:

> Let me try and replicate on my own machine. I've never encountered this
> issue but will verify
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scotch-io/scotch-box/issues/116#issuecomment-140776967>
> .
>



-- 
Alejandro

Think Before You Print. No trees were killed in the sending of this
message. However a large number of electrons were terribly inconvenienced.

**Comment by ncerminara** [comment]
This appears to fix the issue:

```
sudo apt-get install php5-mysqlnd
```

**Comment by ncerminara** [comment]
I'm adding it to the box

**Comment by ncerminara** [comment]
https://scotch.io/bar-talk/announcing-scotch-box-2-5
