### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by Blindmikey** [scotch-io/scotch-box#117]
When running grunt using (postcss-import)[https://github.com/postcss/postcss-import] through scotchbox I get the error:

```
Loading "Gruntfile.js" tasks... ERROR
>> ReferenceError: Promise is not defined
```

This works fine if I run grunt on my non-VM machine.

**Comment by Blindmikey** [comment]
This fixed the issue for me - however it would be nice to have this as part of the scotchbox build.

http://davidwalsh.name/upgrade-nodejs

**Comment by ncerminara** [comment]
Unfortunately, since this is a preconfigured box, you may have to update node or other NPM packages.
