### ISSUE TITLE
laravel: command not found

### ISSUE THREAD

**Issue by iamgoodbytes** [scotch-io/scotch-box#118]
I'm using the latest version of scotchbox 2.0 and I assumed laravel would be in the PATH by default. After going into the vagrant box via ssh, the laravel command isn't available. 

I read in the docs that it's required to add composer to the PATH variable (not sure why that needs to be done manually)

I added the code listed in the docs to do this but it still isn't working:

`config.vm.provision "shell", inline: <<-SHELL
        export PATH="~/.composer/vendor/bin:$PATH" 
SHELL`

My path variable looks like this after reloading: 

`vagrant@scotchbox:~$ echo $PATH
/home/vagrant/.rbenv/plugins/ruby-build/bin:/home/vagrant/.rbenv/shims:/home/vagrant/.rbenv/bin:/home/vagrant/.rbenv/plugins/ruby-build/bin:/home/vagrant/.rbenv/shims:/home/vagrant/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games``

Manually adding composer to the path in the shell fixes this:

`PATH=$PATH:~/.composer/vendor/bin`

Wouldn't it be a lot easier for everyone if this would be included in the box by default? I remember reading other github issues from some months ago, mentioning that this was included by default, but now it seems to be removed again. 

Can someone explain why that is? Thanks a lot for helping out! I love scotchbox and the time it saved me before!

**Comment by ncerminara** [comment]
Added Composer to PATH by default: https://scotch.io/bar-talk/announcing-scotch-box-2-5
