### ISSUE TITLE
documentation: how to install laravel with scotchbox 2

### ISSUE THREAD

**Issue by iamgoodbytes** [scotch-io/scotch-box#119]
I'm really wondering what the best flow would be to quickly install laravel in scotchbox 2.

My current way of doing things with scotchbox 2 is:
- clone scotch-box repo
- `vagrant up`
- ssh into vagrant, and going to /var/www (after manually adding composer to the path variable)
- run `laravel new project`
- this is where it gets tricky because now we have a folder `project/public` next to the standard `public` folder and we need to find a way to move everything out of `/var/www/project` to `/var/www``
- move everything into /var/www
- laravel crashes because the encryption key is not set in .env or config/app.php so let's do that manually
- laravel works

My gut feeling is telling me this is not the way to go but I couldn't find any posts or documentation about this. What would be the go-to and hassle free way to install a new laravel project in scotchbox?

**Comment by ncerminara** [comment]
This is one method: https://scotch.io/bar-talk/announcing-scotch-box-2-5#installing-laravel
