### ISSUE TITLE
Vagrant boot up error

### ISSUE THREAD

**Issue by itarafath** [scotch-io/scotch-box#12]
i get the this  error message
![image](https://cloud.githubusercontent.com/assets/1159869/5137993/02c60cf8-716c-11e4-8a59-b57085cd73f3.png)

**Comment by larsbo** [comment]
I got the same error on Windows 8 64bit.
The VirtualBox log shows some problems that might be related: 
`WARNING! 64-bit guest type selected but the host CPU does NOT support HW virtualization.`
and 
`VMSetError: VT-x is not available.`

**Comment by itarafath** [comment]
@larsbo enable VT-X in bios.

**Comment by larsbo** [comment]
@itarafath thank you for the suggestion but there is no related bios option on that laptop.
But no problem - I have a desktop pc with virtualization ;-)
