### ISSUE TITLE
Use NVM to control Node versions

### ISSUE THREAD

**Issue by wlepinski** [scotch-io/scotch-box#120]
What if we use https://github.com/creationix/nvm to control the default nodejs version enabled on the box.

**Comment by wlepinski** [comment]
Taking advantage of this issue, if you don't agree on implementing this. 
What is the correct procedure to update NodeJS? Compile from source? apt-get?

**Comment by jeremejazz** [comment]
:+1:  to this. seeing that node has now updated to v4,

**Comment by jeremejazz** [comment]
why not use an updated node.js on scotchbox. Node just turned v4 recently

**Comment by ncerminara** [comment]
That's the plan

**Comment by ncerminara** [comment]
I updated Node: https://scotch.io/bar-talk/announcing-scotch-box-2-5#node-js-updates but I will hold off on NVM for now
