### ISSUE TITLE
I have a problem with Vagrant up

### ISSUE THREAD

**Issue by raisiqueira** [scotch-io/scotch-box#121]
![captura de tela de 2015-09-22 22 16 43](https://cloud.githubusercontent.com/assets/2914170/10036054/c7136eec-6177-11e5-892f-686a40aab5a1.png)

**Comment by ncerminara** [comment]
Looks like it's timing out. Try doing this first:

```
vagrant box add scotch/box
```

**Comment by raisiqueira** [comment]
Friend, the connection is closed after a certain time, tested on Linux and Windows, both with the same error reported in the picture! some other possible solution?

**Comment by ncerminara** [comment]
What country are you in? Download the box manually here: https://drive.scotch.io/scotchbox/2.0.0?

**Comment by ncerminara** [comment]
Also - reopened for you

**Comment by raisiqueira** [comment]
I'm from Brazil, I try to manually download!

**Comment by raisiqueira** [comment]
Ok, the file reaches 12.1MB downloaded, and the download falls ...
