### ISSUE TITLE
How to develop in our project

### ISSUE THREAD

**Issue by altsanz** [scotch-io/scotch-box#122]
Hi,

Congratulations for the great box you prepared. We are actually moving a project inside scotch box and we are wondering how should be done in order to keep scotch updates from repository.

So, we actually have a repository holding all our PHP code. How we should proceed?
I want the whole box to be inserted on our repository, so new people just have to clone repo and run vagrant up.

Should we do a git clone inside /public folder? Will it create conflicts when, in the future, we'll be doing git pull from scotch-box repository for updates?

Thanks in advance,

**Comment by ncerminara** [comment]
In some cases, it makes sense to not include Scotch Box in the repo. For example, if you're whole team is not using Vagrant or have different environments (which isn't the best practice approach).

What's ideal IMO is:

```
.git/ (you're repo)
Vagrantfile
public/ (you're code)
```

It's really up to you. Scotch Box doesn't update much as it's prepackaged and stable.
