### ISSUE TITLE
scotchBox randomly throws "403 Forbidden"

### ISSUE THREAD

**Issue by codestic** [scotch-io/scotch-box#123]
Hi guys,

I'm new to Vagrant but I'm rather comfortable with my terminal/shell. Today I went through the process of finally getting into Vagrant and I found scotchBox, which is great! Thanks a lot guys!

However... I just cannot get it to work smoothly. It generally runs well and I love that it runs multiple hosts on the same machine, particularly working with a lot of smaller projects, everything else would be overkill. BUT, it keeps throwing "403 Forbidden" every now and then. I tried reinstalling the box a couple times, without success. I also frequently lose the connection to the MySQL (through Sequel Pro). It seems completely random. Often it works a couple minutes without issue, and then the box is unavailable again for seconds or minutes.

I investigated the problem a bit and I found this 

```
[Mon Jul 13 19:03:17.741950 2015] [mpm_prefork:notice] [pid 2730] AH00169: caught SIGTERM, shutting down
[Mon Jul 13 19:13:26.210633 2015] [mpm_prefork:notice] [pid 1324] AH00163: Apache/2.4.12 (Ubuntu) configured -- resuming normal operations
[Mon Jul 13 19:13:26.213376 2015] [core:notice] [pid 1324] AH00094: Command line: '/usr/sbin/apache2'
[Mon Jul 13 19:14:27.572939 2015] [mpm_prefork:notice] [pid 1324] AH00169: caught SIGTERM, shutting down
[Wed Oct 14 13:45:12.221051 2015] [mpm_prefork:notice] [pid 1623] AH00163: Apache/2.4.12 (Ubuntu) configured -- resuming normal operations
[Wed Oct 14 13:45:12.224089 2015] [core:notice] [pid 1623] AH00094: Command line: '/usr/sbin/apache2'
[Wed Oct 14 14:13:16.824350 2015] [mpm_prefork:notice] [pid 1623] AH00169: caught SIGTERM, shutting down
[Wed Oct 14 14:13:17.864198 2015] [mpm_prefork:notice] [pid 1895] AH00163: Apache/2.4.12 (Ubuntu) configured -- resuming normal operations
[Wed Oct 14 14:13:17.864248 2015] [core:notice] [pid 1895] AH00094: Command line: '/usr/sbin/apache2'
```

I also found, that even while Vagrant is down, I can still access the IP (http://192.168.33.10) and get the same "403 Forbidden". I would really love to make this work and I have spent the last 3 hours researching this, without success.

Anyone?

Thanks!

**Comment by oliwerhelsen** [comment]
I still got this problem. Any solution?

**Comment by codestic** [comment]
Hi @oliwerhelsen. In my case it turned out that *somehow* the VM was launched twice (see task manager and look for HeadlessVM or so). For me it was fixed through a uninstall/reinstall, a simple reboot may work as well though!

**Comment by oliwerhelsen** [comment]
Hi @codestic,

That was the problem. I had 4 other machines running at the same time!
Thanks for the fast respond!

Best regards
Oliwer
