### ISSUE TITLE
Change default setting in php.ini

### ISSUE THREAD

**Issue by rastographics** [scotch-io/scotch-box#124]
For any developers using [processwire](http://processwire.com/), there is a bug with php 5.6 that causes image uploads to fail silently.
The solution is to change a setting in php.ini. I'm not a php expert, but it appears that this setting isn't used for any common scenarios and shouldn't hurt to change in the scotch box image. 

The change is [explained here](https://processwire.com/talk/topic/8712-imagefile-upload-problems-without-errors/page-2) and involves simply uncommenting Line 704 of the file.

I'm not aware of a way to change the php.ini file (/etc/php5/apache2/php.ini) using the vagrant config.
Is there a way to do that?

**Comment by ncerminara** [comment]
You can can do:

```
vagrant ssh
cd /etc/php5/apache2/conf.d/
vim user.ini
```

Then add that snippet of code in.

Then run

```
sudo service apache2 restart
```

**Comment by ncerminara** [comment]
If you don't know Vim, you can do with any other editor

**Comment by rastographics** [comment]
thanks for fast reply. 
yes, i ended up making that edit with vim, but I was wondering is there a way to script that edit in the vagrantfile so i don't have to keep making the edit manually every time i spin up a new machine?

**Comment by ncerminara** [comment]
Try:

```
config.vm.provision "shell", inline: <<-SHELL
    sudo bash -c \'echo export "always_populate_raw_post_data = -1" >> /etc/php5/apache2/conf.d/user.ini\'

    sudo service apache2 restart
SHELL
```

**Comment by ncerminara** [comment]
Also if you link me some resources on this, I might add it to the next update

**Comment by rastographics** [comment]
excellent, thank you

**Comment by rastographics** [comment]
what resources do you want me to link to you about? a pull request?

**Comment by sensenel** [comment]
> You can can do:
> 
> ```
> vagrant ssh
> cd /etc/php5/apache2/conf.d/
> vim user.ini
> ```
> 
> Then add that snippet of code in.
> 
> Then run
> 
> ```
> sudo service apache2 restart
> ```

unfortunately I have big problems to find or edit the php.ini - your tip with vagrant ssh and cd /etc/php/7.0/apache2/php.ini (that's my path from phpinfo) gives me: Not a directory 

Can you help me? 

I only have to change / comment out date.timezone - for a Silverstripe installation, unfortunately this is the absolute showstopper at the moment 

I would also edit the file manually, I am on Mac OS, but this php.ini is untraceable as just a relative path with /etc/php/7.0/apache2/php.ini

[FromWhere??]/etc/php/7.0/apache2/php.ini
I know where to go in MAMP or XAMP but even in MAC OS private/etc/ ... nothing 


Thanks a lot
