### ISSUE TITLE
How can i install phpmyadmin?

### ISSUE THREAD

**Issue by coderontheroad** [scotch-io/scotch-box#129]
Can anyone explain how can i install phpmyadmin to my scotch box?

**Comment by stevwarner** [comment]
Apt-get install phpmyadmin into /etc/

**Comment by ncerminara** [comment]
Use sequel pro or Navicat. We don't support phpMyAdmin

**Comment by JosiahWitt** [comment]
If you would like to use phpMyAdmin, you could always install it in your /var/www[/public] directory using Composer. Instructions for that are located here: http://docs.phpmyadmin.net/en/latest/setup.html#installing-using-composer

**Comment by bamunusingha** [comment]
1. ssh into your scotch box (vagrant ssh)
2. switch to root user (sudo su)
3. follow the following tutorial
https://www.liquidweb.com/kb/how-to-install-and-configure-phpmyadmin-on-ubuntu-14-04/

**Comment by nikolaykv** [comment]
After installing phpmyadmin on the scothc box, a bunch of errors have appeared. For God's sake, give me a ready lamp server with php7.0, apache2, xdebug and phpmyadmun support, please !!!
