### ISSUE TITLE
diff between homestead and scotch-box

### ISSUE THREAD

**Issue by lorvent** [scotch-io/scotch-box#13]
Hi,
looking at doc, it looks like you are not including ubuntu with it, is that true?

what is the main difference between this and homestead?

i like homestead but i think it needs more RAM (i am on 2GB ram device)

also, can i maintain more than one project?

or i need scotch-box for each project?

Thanks.

**Comment by CourteousCoder** [comment]
Update: Homestead now supports apache. https://laravel.com/docs/7.x/homestead#configuring-homestead
