### ISSUE TITLE
no /var/www/public folder

### ISSUE THREAD

**Issue by manooweb** [scotch-io/scotch-box#130]
Hello,
I'd just installed your vagrant box and I wanted to browse ip, I recieved a "not found" apache's error.
All vhost's document root point to /var/www/public folder by default but the public folder didn't exist

I created the missing folder, restarted apache server and it worked fine !

Something has been forgotten in the scotch box ?

Best regards
Emmanuel

**Comment by ncerminara** [comment]
You probably did `vagrant init scotch/box` or something. You should clone this first: https://github.com/scotch-io/scotch-box

It's all presetup

**Comment by manooweb** [comment]
hum, ok thanks ;-)
