### ISSUE TITLE
Exclude syncing .git folders

### ISSUE THREAD

**Issue by ymcheung** [scotch-io/scotch-box#132]
Hi, 
I don't want .git folders to be synced into boxes.
I searched and people said that rsync can do excluding things but didn't have ideas to get started.
How do I exclude .git folders in scotch boxes?

**Comment by ahoffmann-wi** [comment]
There is no way to filter what files are synchronized when configuring a synced folder. I recommend simply deleting the `.git` directory after cloning. Alternatively, if you do a google search for [git clone without .git directory](https://www.google.com/webhp?hl=en#hl=en&q=git+clone+without+.git+directory), you will find other ways to clone without including the `.git` directory.

**Comment by ncerminara** [comment]
```
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__exclude: ".git/"
end
```

https://docs.vagrantup.com/v2/synced-folders/rsync.html

**Comment by ncerminara** [comment]
Or something like that
