### ISSUE TITLE
Unknown configuration section 'berkshelf'

### ISSUE THREAD

**Issue by dev6** [scotch-io/scotch-box#133]
I keep getting this error when I go for 'vagrant up' command in the new project directory after the git clone.

This is the full error:
Failed to load the "vagrant-berkshelf" plugin. View logs for more details.

Bringing machine 'myfirstvagrantproject' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'berkshelf'.

tried reinstalling berkshell and also updated ruby to latest version using rvm.

Any possible solution for this error.

**Comment by ncerminara** [comment]
Are you using the right Vagrantfile?

**Comment by dev6** [comment]
If you are talking about the vagrant file which is located in the new project folder, then yes, I checked that Vagrantfile and I am using it to change the project name and ip address

Anything other than that Vagrantfile I need to look into?

**Comment by ncerminara** [comment]
Can you copy and paste it here

**Comment by dev6** [comment]
# -*- mode: ruby -*-
# vi: set ft=ruby :

# General project settings
#################################

  # IP Address for the host only network, change it to anything you like
  # but please keep it within the IPv4 private network range
  ip_address = "172.33.33.33"

  # The project name is base for directories, hostname and alike
  project_name = "myfirstvagrantproject"

  # MySQL and PostgreSQL password - feel free to change it to something
  # more secure (Note: Changing this will require you to update the index.php example file)
  database_password = "root"



# Vagrant configuration
#################################

  Vagrant.configure("2") do |config|
    # Enable Berkshelf support
    config.berkshelf.enabled = true

    # Define VM box to use
    config.vm.box = "precise32"
    config.vm.box_url = "http://files.vagrantup.com/precise32.box"

    # Set share folder
    config.vm.synced_folder "./" , "/var/www/" + project_name + "/", :mount_options => ["dmode=777", "fmode=666"]


    # Use hostonly network with a static IP Address and enable
    # hostmanager so we can have a custom domain for the server
    # by modifying the host machines hosts file
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.vm.define project_name do |node|
      node.vm.hostname = project_name + ".local"
      node.vm.network :private_network, ip: ip_address
      node.hostmanager.aliases = [ "www." + project_name + ".local" ]
    end
    config.vm.provision :hostmanager

    # Make sure that the newest version of Chef have been installed
    config.vm.provision :shell, :inline => "apt-get update -qq && apt-get install make ruby1.9.1-dev --no-upgrade --yes"
    config.vm.provision :shell, :inline => "gem install chef --version 11.6.0 --no-rdoc --no-ri --conservative"

    # Enable and configure chef solo
    config.vm.provision :chef_solo do |chef|
      chef.add_recipe "app::packages"
      chef.add_recipe "app::web_server"
      chef.add_recipe "app::vhost"
      chef.add_recipe "memcached"
      chef.add_recipe "app::db"
      chef.json = {
        :app => {
          # Project name
          :name           => project_name,

          # Name of MySQL database that should be created
          :db_name        => "dbname",

          # Server name and alias(es) for Apache vhost
          :server_name    => project_name + ".local",
          :server_aliases =>  [ "www." + project_name + ".local" ],

          # Document root for Apache vhost
          :docroot        => "/var/www/" + project_name + "/public",

          # General packages
          :packages   => %w{ vim git screen curl },
          
          # PHP packages
          :php_packages   => %w{ php5-mysqlnd php5-curl php5-mcrypt php5-memcached php5-gd }
        },
        :mysql => {
          :server_root_password   => database_password,
          :server_repl_password   => database_password,
          :server_debian_password => database_password,
          :bind_address           => ip_address,
          :allow_remote_root      => true
        }
      }
    end
  end

**Comment by ncerminara** [comment]
Ahhh

So you're referencing and old unsupported Vagrant stack: https://github.com/MiniCodeMonkey/Vagrant-LAMP-Stack. Probably following the tutorial on Scotch.io.

Scotch Box is here: https://github.com/scotch-io/scotch-box and is basically everything this has prepackaged so you don't have to get errors.

Here's where to start: https://github.com/scotch-io/scotch-box
