### ISSUE TITLE
'shell_expand_guest_path': undefined method `split' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by martinbertinat** [scotch-io/scotch-box#134]
Hello. I'm having a problem when I run vagrant up. Yesterday it was working fine. I use version 1.5.0

default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => /home/martin/vagrants/scotch-box
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/guests/linux/cap/shell_expand_guest_path.rb:15:in `shell_expand_guest_path': undefined method `split' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/capability_host.rb:111:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/capability_host.rb:111:in `capability'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/guest.rb:43:in `capability'

When I open the machine from virtualbox I can't login. I enter vagrant as username and vagrant as password, press enter and I can see the welcome message but it shows me the login screen again, so I don't have time to enter any command.

Thanks!

**Comment by ncerminara** [comment]
Try uninstalling everything and reinstalling to the latest versions.

If this doesn't work, the announcement articles explain how to use the still supported 1.5 box instead.

**Comment by martinbertinat** [comment]
Ok but if I uninstall everything I will loose all my databases, right?

**Comment by ncerminara** [comment]
Yeah so make sure you do a full backup first.
