### ISSUE TITLE
Installing phpmyadmin by default

### ISSUE THREAD

**Issue by javimaravillas** [scotch-io/scotch-box#135]
Hi scotch,
I know that is is only an apt-get install command but it would be nice if you have installed by default the tool phpmyadmin.
A lot of old stuff folks still use it!

Regards,

**Comment by ncerminara** [comment]
We actually will never support phpMyAdmin. Can you instead use Sequel Pro, Navicat, HeidiSQL, or any other client?

**Comment by javimaravillas** [comment]
Sounds good!
