### ISSUE TITLE
No Machine id

### ISSUE THREAD

**Issue by ivanvillacreative** [scotch-io/scotch-box#136]
I am running into an issue when I first try to Vagrant Up, In the documentation it says that it should be downloading box/scotch, but it doesn't seem to do it. 
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Removing hosts
==> default: No machine id, nothing removed from /etc/hosts
==> default: Checking for host entries
```

**Comment by ncerminara** [comment]
What version of Vagrant are you running

**Comment by ivanvillacreative** [comment]
I'm Running Vagrant 1.7.4

**Comment by ivanvillacreative** [comment]
Alright I figured out what was causing my  **vagrant up** to fail. In the vagrantfile this line
```
config.vm.hostname = "scotchbox"
```
is causes vagrant to not work, I  commented it out and vagrant up worked. Seems like a vagrant error, in combination with me upgrading to El Capitan on my mac.

what exactly does this do? is it important?

**Comment by ncerminara** [comment]
It's not that important. It just sets the hostname of the box
