### ISSUE TITLE
MySQL 5.7, PHP 5.6.15 etc released

### ISSUE THREAD

**Issue by slaFFik** [scotch-io/scotch-box#137]
Is it possible to get those things updated?

PHP is not that critical, but MySQL got some really cool things in (see http://mysqlserverteam.com/whats-new-in-mysql-5-7-generally-available/) so it will be really cool to have it on board.

**Comment by ncerminara** [comment]
Yeah, I probably will.

The problem is that version of MySQL requires a bit more memory than the default Vagrant setup. `512mb and 1 processor`. So I would be forced to append the Vagrantfile and use more of people's resources.

Which leaves me unsure if it's worth adding. Thoughts?

**Comment by brendanmckeown** [comment]
+1
I needed to upgrade MySQL on scotch-box from 5.5 to 5.6 in order to install Magento 2

**Comment by Eoler** [comment]
+1 for MySQL 5.6 (did anyone try to Composer-install a contemporary framework? VM with 512MB  is not enough anymore...)

**Comment by sdwalden** [comment]
I agree that a 5.7 version is needed. Developers need to be able to use the latest MySQL features - json for one.

**Comment by aleshh** [comment]
I'm running into errors MySQL errors running my Dreamhost site locally. Are there instructions somewhere I could use to upgrade my ScotchBox MySQL to 5.6?

**Comment by grngc** [comment]
+1 I agree that upgrading to MySQL 5.6 is be necessary.
First of all congrats for your initiative.. Scotch box is awesome.
But upgrades are required soon enough.
MySQL 5.6 is a requirement for both **Magento** and **WP 4.6+** and will soon become a requirement for **Larval** framework also.

Thanks.

**Comment by slaFFik** [comment]
PHP 7.0.11 already released.

**Comment by tomscholz** [comment]
Still an issue!

**Comment by vernard** [comment]
This is an issue for me as well. This all depends on the principles of scotch box.

Being as simple and lean vs being latest and cater to advanced developers.

Is there a fork that we can use with the latest PHP and MySQL?

**Comment by pronuz** [comment]
I'm here to help us all 🥇 hehe...

**Step 1: Change your VM to have at least 2 GB ram and 2 -4 vCPU cores (else this will get SLOW..)**
You can change this in VirtualBox .. should be an easy task..

**Step 2: Did you say "We want to have MySQL 5.7"?**
Run:

- wget http://dev.mysql.com/get/mysql-apt-config_0.8.0-1_all.deb
- sudo dpkg -i mysql-apt-config_0.8.0-1_all.deb
- sudo apt-get update
- sudo apt-get install mysql-server

In the command "dpkg" remember to change first line when it asks you to mysql 5.7 and press ok.
(Click first line when asked, change to 5.7, click enter, click ok..)

**Step 3: Did you say "We want to have PHP7.0"?**
Run:

- sudo apt-get update
- sudo add-apt-repository ppa:ondrej/php
- sudo apt-get install php7.0
- sudo apt-get update
- sudo apt-get install php7.0-mysql libapache2-mod-php7.0
- sudo a2dismod php5
- sudo a2enmod php7.0
- sudo apachectl restart
- sudo apt-get update && sudo apt-get upgrade -y;
- sudo apt-get install php7.0-xml php7.0-zip htop phpmyadmin
- sudo apt-get install php-mbstring
- sudo service apache2 restart

Step 4: Did you say "We want latest phpunit functions"?
Run:

- wget https://phar.phpunit.de/phpunit.phar
- chmod +x phpunit.phar
- sudo mv phpunit.phar /usr/local/bin/phpunit
- phpunit --version

I hope this help at least some of you :)

**Comment by jkusachi** [comment]
thank you @pronuz !

**Comment by pronuz** [comment]
@jkusachi if phpmyadmin fails to run some of the functions, i have updated my list of commands to get the latest mbstring, this should fix some of the issues (at least the ones i found).

**Comment by juancarlosqr** [comment]
+1 to update MySQL to at least 5.6, Woocommerce requires it. The idea is not having outdated tools, right? Thanks for this, really useful great work

**Comment by whatnickcodes** [comment]
FYI we have this in the new updating releasing this week
