### ISSUE TITLE
You don't have permission to access / on this server.

### ISSUE THREAD

**Issue by oliwerhelsen** [scotch-io/scotch-box#138]
Hey Guys,

I keep getting "You don't have permission to access / on this server." everytime a use Scotch box with Laravel. Sometimes it can work for 5 - 10 minutes and after that it gives me this message.

Anyone with the same problem with a solution?

Thanks in advance!

//O

**Comment by oliwerhelsen** [comment]
Solved! 
I had 4 machines running at the same time. Closed them all and now it works just fine!

**Comment by ncerminara** [comment]
Haha! You should be able to run multiple machines at the same time, but for Scotch Box, I recommend suspending each of them before switching a project.
