### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by coderontheroad** [scotch-io/scotch-box#139]
I love scotch-box and i was using it for every project. But last 3-4 days i can't use anymore. When i type vagrant up it gives error like output:
"default: Warning: Authentication failure. Retrying..."
And the vm can't connect to github or wordpress.org.

How can i solve it?

**Comment by ncerminara** [comment]
I think you'll to reinstall. You can add this to your Vagrantfile:

```
config.ssh.username = "vagrant"
config.ssh.password = "vagrant"
```

**Comment by coderontheroad** [comment]
Ok after adding your config variables to vagrantfile it works, i didn't see authentication failure. But still wordpress core can't connect to internet.

**Comment by ncerminara** [comment]
Can you open a separate issue for that? Try removing the box and adding it
