### ISSUE TITLE
Change public to public_html

### ISSUE THREAD

**Issue by andriansandi** [scotch-io/scotch-box#14]
Hi,

I have a problem that my application map public_html as a webroot. How to change public to public_html in scotch-box?

Thanks

**Comment by knynkwl** [comment]
Is there a way to add this to a settings file, so when I start a new project I don't have to ssh in and change this manually?

**Comment by djkush** [comment]
Adding server config would be so useful, shame it can't go in the Vagrantfile

**Comment by ncerminara** [comment]
It probably can... Let me get you an example soon

**Comment by ncerminara** [comment]
@djkush here you go

```ruby
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

    config.vm.provision "shell", inline: <<-SHELL
        mv /var/www/public /var/www/public_html
        sudo sed -i s,/var/www/public,/var/www/public_html,g /etc/apache2/sites-available/000-default.conf
        sudo sed -i s,/var/www/public,/var/www/public_html,g /etc/apache2/sites-available/scotchbox.local.conf
        sudo service apache2 restart
    SHELL

end
```

**Comment by ncerminara** [comment]
This will automatically change the public folder for you and do all the server stuff. Pretty simple stuff

**Comment by ncerminara** [comment]
Also I updated the article: https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#changing-/public-to-/public_html

**Comment by djkush** [comment]
Thanks ncerminara. Some good tips in that article.
