### ISSUE TITLE
Help Vhosts

### ISSUE THREAD

**Issue by netopvh** [scotch-io/scotch-box#140]
How do I set VHosts in ScotchBox ?? Can anyone help me?

**Comment by ncerminara** [comment]
What are you trying to do?

**Comment by netopvh** [comment]
I managed to solve , thank you.

**Comment by ncerminara** [comment]
https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#multiple-domains-(virtual-hosts)
