### ISSUE TITLE
Timezone in php.ini

### ISSUE THREAD

**Issue by mikegyi** [scotch-io/scotch-box#141]
Hey, 
 
I've set the timezone to "Europe/London" in the php.ini file, but when I run phpinfo.php there is still 'no value'. (see image attached).

This is after restarting the server by running <code>sudo service apache2 restart</code>

Any clues why the changes in scotchbox are not being displayed in the phpinfo.php file? I've changed other properties in the php.ini file to test and no edits are being reflected on the server.

Specifically I am trying to install MODx Revo onto the server and the following error occurs: 

 'FATAL ERROR: MODX Setup cannot continue.

To use PHP 5.3.0+, you must set the date.timezone setting in your php.ini. Please do set it to a proper timezone before proceeding. A list can be found here.'

Thanks!

<img width="1116" alt="screen shot 2015-11-21 at 21 51 59" src="https://cloud.githubusercontent.com/assets/8915359/11320707/9d10aedc-909a-11e5-9242-24260ad4af1b.png">

**Comment by ncerminara** [comment]
Try putting it here:

```
vagrant ssh
sudo vim /etc/php5/apache2/conf.d/user.ini
```

**Comment by mikegyi** [comment]
Thanks @ncerminara 

Spent a fair few hours trying to sort this!
