### ISSUE TITLE
"npm install" is installing excessive amount of modules

### ISSUE THREAD

**Issue by pessato** [scotch-io/scotch-box#143]
Using scotch-box 2.5

I have a package.json file which has the following: 

```
{
  "name": "dev",
  "version": "1.0.0",
  "devDependencies": {
    "gulp": "~3.9.0",
    "gulp-sass": "~2.0.4",
    "gulp-minify-css": "~1.2.0",
    "gulp-concat": "~2.6.0",
    "gulp-uglify": "~1.2.0",
    "gulp-sourcemaps": "~1.5.2",
    "gulp-if": "~1.2.5",
    "gulp-notify": "~2.2.0",
    "gulp-rimraf": "~0.1.1",
    "browser-sync": "~2.8.2"
  }
}
```

When running `npm install` in the directory with the package.json file I end up with a node_modules directory containing hundreds of modules.

Running `gulp` I then get a `EACCES` error.

This has not happen on previous versions of Scotchbox and everything has worked correctly. Perhaps node 5.0.0 has something to do with it?

**Comment by isellsoap** [comment]
This has nothing to do with Node or scotch-box. It’s because since npm version 3 dependencies are installed in a [flat manner](http://www.felixrieseberg.com/npm-v3-is-out-and-its-a-really-big-deal-for-windows/).
