### ISSUE TITLE
Any tips to improve performance?

### ISSUE THREAD

**Issue by comunidademagento** [scotch-io/scotch-box#144]
Hello,

See this issue.

https://github.com/joshuaswarren/magescotch/issues/1

The box vagrant created with base Scotch-Box work, but is very slow.

My host machine is Ubuntu 15.10.

Any tips to improve performance?

Thanks!!!

**Comment by ncerminara** [comment]
This should help. Add this to the Vagrantfile.

```
   config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end
```

**Comment by cjke** [comment]
@comunidademagento One thing that makes a world of difference for our machines (not just scotch, but vagrant in general) is:

    config.vm.synced_folder "./", "/var/www", type:"nfs", mount_options:["nolock,vers=3,udp,noatime,actimeo=1"]

Note that the `[` onwards is to resolve an issue around sync'ing, and might not offer a speed increase. The nfs certainly does on our machines.

**Comment by Mizner** [comment]
@whatnickcodes & @cjke both additions seemed to speed things up for me, thank you!

**Comment by gitressa** [comment]
They do work very well, thanks!  :+1:

**Comment by hahnmg** [comment]
Thanks guys!
