### ISSUE TITLE
Public Network

### ISSUE THREAD

**Issue by modocan** [scotch-io/scotch-box#145]
First of all I have to say thank you for your great work. It's an awesome box, full of required features.

I just have a problem trying to open a public network interface. It's imposible for me. I reach a public connection, but when I reload the box it's lost.

With other boxes I've not this issue. It's only with this one. I figure that it's in relation to apache or something like that, but I can't find a solution. Any help?

**Comment by ncerminara** [comment]
I tried this a while ago and faced issues. I currently use `vagrant share` for public SSH and HTTP access now.

I'll leave this open in case I can revisit or someone else.

**Comment by juslinguo** [comment]
Anyone experience this problem where the vm have not outgoing network?

**Comment by Braunson** [comment]
Options:

1. Using `vagrant share`
2. https://www.vagrantup.com/docs/networking/public_network.html
3. http://stackoverflow.com/questions/18051760/how-to-access-vagrant-box-in-public-network

**Comment by palibaacsi** [comment]
You can use "public_network", but the IP address will need to be within the DHCP range of your router. I usually start a dev environment with the default Vagrantfile, then I change to public_network and the IP address. That is, my change will look like:

```
#    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.network "public_network", ip: "10.0.0.20"
```

since my router is at 10.0.0.1

**Comment by ncerminara** [comment]
Awesome - thanks for help Paul. Going to close. I'll add this info to next release as I've been wondering about this for a while.
