### ISSUE TITLE
Document how to change configuration settings

### ISSUE THREAD

**Issue by whatnickcodes** [scotch-io/scotch-box#146]
- PHP, etc

**Comment by ncerminara** [comment]
PHP Settings Here
```
vagrant ssh
sudo vim /etc/php5/apache2/conf.d/user.ini
```

**Comment by jzohrab** [comment]
Should that be part of this project, or is that more the responsibility of the dev to understand how to use Vagrant and the various parts?  The README already has a note about `vagrant ssh`.

**Comment by ncerminara** [comment]
Half / half. Might as well document how to do it so more people can figure it out quickly.

**Comment by ncerminara** [comment]
@jzohrab Going to leave this open so I can update https://box.scotch.io.

**Comment by jzohrab** [comment]
:+1: Thanks @ncerminara.

**Comment by dstollie** [comment]
I dont know what is going on but somehow I can not manage to enable opcache. I tried adding

`opcache.enable=1` to:

 `/etc/php5/apache2/conf.d/user.ini`, 
 `/etc/php5/apache2/conf.d/05-opcache.ini`,
 `/etc/php5/apache2/php.ini`

and of course i restarted my apache several times: `service apache2 restart` and to be 100% also `/etc/init.d/php5-fpm restart`

But unfortunately nothing gets my opcache on according `phpinfo()`. Can someone help me out?

**Comment by dstollie** [comment]
Ok i managed to fixed it by running `sudo service apache2 restart` unfortunately I dont see any difference in running my app with opcache enabled or not. Does anyone of you know if this is some some misconfiguration in the box?

**Comment by whatnickcodes** [comment]
Documentation is in the new release launching this week
