### ISSUE TITLE
virtualbox versions

### ISSUE THREAD

**Issue by SamuelHill** [scotch-io/scotch-box#147]
Currently, I get this error when trying to run this machine in virtualbox 5.0.10:

> "The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:
Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:
4.0, 4.1, 4.2, 4.3"

I went ahead and downloaded 4.3 and everything is building so far but could this be extended to work on the new version?

**Comment by ncerminara** [comment]
What version of Vagrant are you running

**Comment by fsociety79** [comment]
@Sam
I'm currently running VirtualBox 5.0.10 r104061 and vagrant runs great.
Regards,Julian

Date: Thu, 3 Dec 2015 12:08:16 -0800

**Comment by ncerminara** [comment]
I'm almost positive you're not running the latest version of Vagrant

**Comment by SamuelHill** [comment]
I was on vagrant version 1.6.3, after switching to 1.7.4 everything worked perfectly! Thanks.
