### ISSUE TITLE
Scotch-box completely broke

### ISSUE THREAD

**Issue by jawittdesigns** [scotch-io/scotch-box#148]
I ran vagrant provision and it completely broke the entire thing. I can't access any sites or databases. OMG HELP!!!

How can I retrieve the databases.

**Comment by fsociety79** [comment]
Can you open the guest in VirtualBox itself?
Date: Thu, 3 Dec 2015 15:34:36 -0800

**Comment by jawittdesigns** [comment]
Yeah, it all seems to be working, but everything is gone. I go into mysql and there's nothing there. I;m not an expert on vagrant, but I don't think running provision should wipe everything.I have a bad feeling that I just lost everything and have to start over.

**Comment by fsociety79** [comment]
If you're just testing things why not use an import file to initialize the database. That way if it goes down then at least you can just re-create the database and then import once again.

Date: Thu, 3 Dec 2015 16:12:07 -0800

**Comment by ncerminara** [comment]
Quick note to anyone who reads this:

Not sure why the databases went missing.

Running `vagrant provision` should not clear your databases. The database files will be lost if you destroy the VM though. It would be a good idea to somehow run backups or to dump the database when periodically.

It's also best practice to do one site per VM (aka, per Scotch Box). This way your eggs aren't in one basket.
