### ISSUE TITLE
mongo php module

### ISSUE THREAD

**Issue by SamuelHill** [scotch-io/scotch-box#150]
The _mongo_ php module is apparently the deprecated version. There is a new one called _mongodb_ that should work for this box (all requirements are satisfied, PHP > 5.4, and it is housed by pecl). Are you considering updating this module?

**Comment by ncerminara** [comment]
Good call. I'll update in the next version. Going to leave this open until I do

**Comment by gsolak** [comment]
^ Yes. please do asap. This is the main reason I decided to go with the scotch box! thanks!

**Comment by whatnickcodes** [comment]
This is fixed in the updating that's being released this week!
