### ISSUE TITLE
Anyone experience this problem where the vm have not outgoing network?

### ISSUE THREAD

**Issue by juslinguo** [scotch-io/scotch-box#151]
I have a strange problem, i have no outgoing network when I ssh into the scotch-box

**Comment by ncerminara** [comment]
Hey @juslinguo. Can you explain this a bit more?

**Comment by juslinguo** [comment]
sorry, i got it fix...had to put a line in my vagrantfile

	config.vm.provider :virtualbox do |vb|
  		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	end

**Comment by ncerminara** [comment]
Awesome
