### ISSUE TITLE
scotchbox login:

### ISSUE THREAD

**Issue by alexeightsix** [scotch-io/scotch-box#154]
What is the default login and password if trying to login through virtual box itself?

scotchbox login: _

??

**Comment by timganter** [comment]
@alexeightsix Did you ever figure out the username/pass? 

My box was hanging when trying to vagrant up. So, I edited the vagrantfile to bootup in gui mode so I could see if it was getting stuck somewhere. I'm getting stuck at the login prompt. 

Scotchbox worked fine yesterday when I first installed it. Second time booting it up and it's hanging.

-Tim

**Comment by alexeightsix** [comment]
vagrant vagrant its in the scotchbox docs

On Monday, 18 January 2016, Tim Ganter <notifications@github.com> wrote:

> @alexeightsix <https://github.com/alexeightsix> Did you ever figure out
> the username/pass?
>
> My box was hanging when trying to vagrant up. So, I edited the vagrantfile
> to bootup in gui mode so I could see if it was getting stuck somewhere. I'm
> getting stuck at the login prompt.
>
> Scotchbox worked fine yesterday when I first installed it. Second time
> booting it up and it's hanging.
>
> -Tim
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scotch-io/scotch-box/issues/154#issuecomment-172710986>
> .
>


-- 
Sent from Gmail Mobile

**Comment by timganter** [comment]
@alexeightsix Got it! Thanks man! =)
