### ISSUE TITLE
Sequel Pro not connecting

### ISSUE THREAD

**Issue by pengimo** [scotch-io/scotch-box#155]
I can't get Sequel Pro to connect to the Scotch Box MySQL server.

I've tried all of the suggestions mentioned in issue 38 but none of then work for me.

When I try and connect for the first time, I get a authenticity message (which I answer Yes) then get the following after a few seconds..

"The SSH Tunnel could not authenticate with the remote host. Please check your password and ensure you still have access"

I've tried with both the password (vagarant) and using the private key.

It seems that i'm not the only one having this issue "out of the box" so a resolution would be good and improve the end user experience.

Here is the full error message:

Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -i /Users/Matt/Code/ScotchBox/.vagrant/machines/default/virtualbox/private_key -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 vagarant@192.168.33.10 -L 49926:127.0.0.1:3306

OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Control socket " none" does not exist
debug1: Connecting to 192.168.33.10 [192.168.33.10] port 22.
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /Users/Matt/Code/ScotchBox/.vagrant/machines/default/virtualbox/private_key type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/Matt/Code/ScotchBox/.vagrant/machines/default/virtualbox/private_key-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3 pat OpenSSH_6.6.1* compat 0x04000000
debug1: Authenticating to 192.168.33.10:22 as 'vagarant'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:GSgnPlYwWHAjE9wiWCK9KuB0Y865EOvTO1oVn+BD1PA
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
Warning: Permanently added '192.168.33.10' (ECDSA) to the list of known hosts.
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Trying private key: /Users/Matt/Code/ScotchBox/.vagrant/machines/default/virtualbox/private_key
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: password
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
debug1: Authentications that can continue: publickey,password
debug1: No more authentication methods to try.
Permission denied (publickey,password).

**Comment by kevinmann** [comment]
We are suffering the same issue. We are using scotchbox on El Capitan, the error message is the same. We can connect intermittently but the connect is often lost.

**Comment by rafaelcpalmeida** [comment]
Same issue here :cry:

**Comment by ncerminara** [comment]
Can you do:

```
vagrant ssh
```
 
Does http://192.168.33.10 event work?

If so, just do:

```
vagrant ssh-config
```

And connect via those settings.

**Comment by rafaelcpalmeida** [comment]
@ncerminara I've successfully connected to Vagrant's MySQL server after I logged in the server and edited my.cnf file, changing 

`bind 127.0.0.1`

 to 

`bind 0.0.0.0`

**Comment by rafaelcpalmeida** [comment]
@pengimo @kevinmann @ncerminara  Here's my solution

I've sucessfully connected by doing:

- Editing the /etc/mysql/my.cnf and commenting the line 47 from:
`bind-address           = 127.0.0.1`
to
`#bind-address           = 127.0.0.1`

- Updated MySQL user table doing:
`mysql> UPDATE user SET host='%' WHERE user='root' AND host='127.0.0.1';`

Now I can acess ScotchBox MySQL server without anyproblem.

**Comment by gr33k01** [comment]
Hey @whatnickcodes,  Can we add @rafaelcpalmeida 's solution to the readme? What a blessing that would be.

**Comment by whatnickcodes** [comment]
Pull request!

**Comment by rafaelcpalmeida** [comment]
@whatnickcodes @gr33k01 Do you want me to update the README file and make a Pull Request with the instructions above?

**Comment by gr33k01** [comment]
@rafaelcpalmeida Please do!! We can iterate on what that looks like in the PR. I've hunted down this issue a couple times when configuring my apps on scotchbox :)
