### ISSUE TITLE
wrong folder synced

### ISSUE THREAD

**Issue by kevincam3** [scotch-io/scotch-box#156]
line 9 in the Vagrantfile should have "/var/www" changed to "/var/www/public" prior to doing that it didn't work.

**Comment by ncerminara** [comment]
This is not really true. This will work with the original setup and is actually recommended

**Comment by kevincam3** [comment]
Ok,

But it didn't work for me. I had to make the change for it to start working

**Comment by fuzzy76** [comment]
That is probably because you didn't put your project in a "public" sub-folder. This just bit me as well.
