### ISSUE TITLE
PHP7 install instructions

### ISSUE THREAD

**Issue by fabianhenzler** [scotch-io/scotch-box#157]
Any chance we're getting on PHP7 soon? :)

**Comment by pquerner** [comment]
+1

**Comment by AdamKyle** [comment]
+1 to the power of 8 trillion

**Comment by fabianhenzler** [comment]
https://puphpet.com did a great job on achieving this :) @jtreminio

**Comment by chrisdeeming** [comment]
If it helps, it's pretty easy to update your own scotch-box to PHP 7:

https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-ubuntu-14-04

**Comment by chrisdeeming** [comment]
The exact steps:

```sudo add-apt-repository ppa:ondrej/php-7.0
sudo apt-get update
sudo apt-get install php7.0
sudo apt-get install php7.0-mysql```

I had to manually enable the mysqli extension in php.ini which, for reference, is available at `/etc/php/7.0/apache2/php.ini` after the above steps have been completed.

**Comment by cjke** [comment]
-1 . Not yet - it makes little sense considering it's not even part of an official repo for ubuntu yet, and most people are still using 5.4, 5.5 or 5.6 in production. It's super easy to upgrade yourself, place @chrisdeeming 's lines inside your provision script and you are done.

**Comment by AdamKyle** [comment]
That's a stupid reason to minus one something

**Comment by cjke** [comment]
Is it?- "stupid" is a bit strong, but thanks for letting me know. I thought mirroring common production environments made sense.

I guess in my opinion it's easier for people to upgrade to 7 if needed, than for all the people already using scotchbox to downgrade to 5.6. 

Honestly it depends on scotchbox's core philosophy (I'm not sure what that is) - do they, as a team, want to provide a stable easy to set up box, or do they want a provide a box with the latest and greatest?  Both types of boxes have their own respective place don't you think?

**Comment by THenkeDE** [comment]
i think their strategy is good. but maybe they could add some little scripts to "switch" oder "upgrade" php versions.

Delivering the 5.6 in stock image but ppl could use a "install-php7.sh" script to switch to php7 in a scotch box creator tested way.

I would like this.

**Comment by verenion** [comment]
I've been trying to use scotch as a base to build some PHP7 envioronments for testing and porting.

I've used the code above - thanks @chrisdeeming. It doesnt actually seem to load for me now. When provisioning, it does actually install php 7 and upgrade 5. No errors, but the web server is then unreachable and nothing seems to load.Anyone else having this issue?

**Comment by verenion** [comment]
Just to add some community spirit.Anyone wanting to do this can either run the commands from @chrisdeeming , which after a bit of tinkering,is working fine. Or, I've forked the repository and just added the Vagrantfile change to add the provision script, and the actual script itself.

https://github.com/verenion/scotch-box

Hope this helps someone.

**Comment by THenkeDE** [comment]
I updated scotchbox myself to php7 + mysql 5.6 without any problems, but i did not put the update in the provisioning but made it manually ...

sudo add-apt-repository ppa:ondrej/php-7.0
sudo apt-get update
sudo apt-get install -y php7.0
sudo apt-get install -y php7.0-*
sudo apt-get upgrade -y
/etc/init.d/apache2 restart

sudo apt-get install mysql-server-5.6

Maybe it's because you did not setup the modules aswell?

**Comment by drawcard** [comment]
If I may add my 2¢, I agree with @cjke - it's trivial for anyone to upgrade their box to PHP7 if needed. But PHP5.x is still the status quo and it would be a pain for the rest of us to have to downgrade to 5.x in order to simulate a typical prod environment. 

Sure, if PHP7 when php the norm, then the box should follow, but today it just doesn't make sense with only 1% of servers running PHP7 globally right now.

**Comment by ncerminara** [comment]
@drawcard Agree

**Comment by fuzzy76** [comment]
> I thought mirroring common production environments made sense.
Yes, but PHP7 is not that common in production environments yet.

As far as I can tell, scotch box is following the latest Ubuntu LTS release. Which means it uses whatever 14.04 uses now, and might get PHP7 when 16.04 is out.

Currently, it looks like Ubuntu 16.04 will ship with both PHP 5.6 (as default) and PHP7 as alternatives for the "PHP" virtual package. I guess this makes sense considering PHP 5.6 will receive security fixes longer than PHP 7.0 according to http://php.net/supported-versions.php

**Comment by cjke** [comment]
@fuzzy76 I think you are quoting me - and I actually believe we are saying the same thing

**Comment by fuzzy76** [comment]
Oh, you're right. I misread you. :)

**Comment by ncerminara** [comment]
I know a lot of people want this, but I'm kind of against the idea right now. Homestead also forked regarding this issue. Definitely check that out here: https://atlas.hashicorp.com/laravel/boxes/homestead-7

Also, quick note: Scotch Box is geared generally more towards beginners and quick app development.

Going to close this. What is probably going to happen is the next release will have an optional provisioning script for updating the box to PHP7 versus implementing it directly right now.

**Comment by arthur-olafsson** [comment]
I just tried to follow the above instructions and the PPA seemed to have replaced by ppa:ondrej/php, which allows co-installable versions of PHP. Here's what I wound up running:

   add-apt-repository ppa:ondrej/php
   apt-get install php7.0 libapache2-mod-php7.0
   a2dismod php5
   a2enmod php7.0
   apachectl restart

Apache in Scotch Box is now running php7.

**Comment by Mizner** [comment]
I've tested this over and over with clean scotchbox installs, php7 w/ mysql 5.6, working great for my local wordpress installs

<pre>
sudo apt-get update
sudo add-apt-repository ppa:ondrej/php
sudo apt-get install php7.0
sudo apt-get update
sudo apt-get install php7.0-mysql libapache2-mod-php7.0
sudo a2dismod php5
sudo a2enmod php7.0
sudo apachectl restart
</pre>

**Comment by samlittler** [comment]
@Mizner I've followed your commands after a fresh launch of scotchbox and I get 500 errors from apache2. Any ideas?

**Comment by ekandreas** [comment]
+1

**Comment by whatnickcodes** [comment]
Reopenng until someone resolves

**Comment by drawcard** [comment]
Have you checked your error logs for any clues?

**Comment by maxpou** [comment]
@whatnickcodes I answer here: https://github.com/scotch-io/scotch-box/issues/210

> Hi,
> 
> if you want, here's my full [install guide for PHP7 in scotchbox](https://github.com/maxpou/scotch-box/blob/master/pimpMyBox/php7.md)
> 
> **Install PHP7 (will remove php5)**
> 
> 1. Update package list
> 
>     ```sh
>     sudo apt-get install python-software-properties
>     sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
>     ```
> 
> 2. Install PHP7 and remove PHP5
> 
>     ```sh
>     sudo apt-get update
>     sudo apt-get purge php5-common -y
>     sudo apt-get install -y \
>         && php7.0 \
>         && php7.0-fpm \
>         && php7.0-mysql \
>         && php-curl \
>         && libapache2-mod-php7.0 \
>         && php7.0-mbstring
>     sudo apt-get --purge autoremove -y
>     ```
> 
> 3. Set timezone (i.e. date.timezone = Europe/Paris)
> 
>     ```sh
>     sudo vi /etc/php/7.0/cli/php.ini
>     sudo vi /etc/php/7.0/apache2/php.ini
>     ```
> 
> 4. Restart apache service
> 
>     ```sh
>     sudo a2enmod php7.0
>     sudo service apache2 restart
>     ```

**Comment by XedinUnknown** [comment]
@maxpou, thank you, will try this out. I'm very interested in being able to run ScotchBox with PHP7. Is this safe to put inside an install script?
I would love to see some kind of switch that would make `vagrant up` provision the environment with a developer-tested script.

**Comment by Mizner** [comment]
Okay, so after a few months of running into little bugs and stuff:

Here's a gist of my usual process to update scotchbox to PHP7 (I've done it on 50+ project all wordpress related and seemingly stable with the necessary packages)

https://gist.github.com/Mizner/24b70924d10766ac70c9d367ccc88d68

Copy, pasta from gist for the lazy

<pre>
List of PHP 7 Packages: https://launchpad.net/ubuntu/+source/php7.0

Disclaimer: I get unreliable results when I don't run these commands seperately and in order.

vagrant ssh

sudo apt-get update
sudo add-apt-repository ppa:ondrej/php
sudo apt-get install php7.0
sudo apt-get update
sudo apt-get install php7.0-mysql libapache2-mod-php7.0 php7.0-fpm php7.0-json php7.0-xmlrpc php7.0-cgi php7.0-opcache php7.0-zip php7.0-imap php7.0-curl php7.0-xml php7.0-gd

sudo a2enmod proxy_fcgi setenvif
sudo a2enconf php7.0-fpm

sudo a2dismod php5
sudo a2enmod php7.0
sudo apachectl restart
sudo service apache2 reload
</pre>

**Comment by cbaykam** [comment]
Hi check this one out. I had mongo issues with updated php and coded a simple provisioner shell. 
https://github.com/cbaykam/scotchbox-update-php/
Just run `vagrant up`

**Comment by ac-coding** [comment]
I've been trying to install it but I use Mac and homebrew. I have been trying to find the way to do it, but I couldn't find a solution because I keep getting a simple "No command 'brew' found" every time I try something as homebrew is neither part of Scotch Box.

Does anyone have a solution or idea for this?

**Comment by maxpou** [comment]
*"I use Mac and homebrew"*

Man, you are inside a virtual machine... Brew is a packet manager for **Mac**. Scotchbox is a virtual box which run on Ubuntu. So everything is normal!
If you want to install something, use `apt-get` command (as described in the comments below).

I'm not sure if you really understand what is a vagrant box. This article (from scotch.io) is for you: https://scotch.io/tutorials/get-vagrant-up-and-running-in-no-time

Kind regards.

@XedinUnknown : sorry, It's probably too late... but yes it's safe!

**Comment by ac-coding** [comment]
Yeah, I know, I know. But I can promise I tried it few times before and it didn't work. Now I've just started from scratch.... and It's all fine. What a shame of myself... ¬¬'

Anyway, thanks for taking your time replying back. Somehow that reply was the solution because it made me try once again from scratch and I found out I was the issue, hehehe.

**Comment by maxpou** [comment]
You're welcome :)

**Comment by XedinUnknown** [comment]
@maxpou, I tried this today, and it didn't work, presumably because it installed PHP 7.1 instead of 7.0.
```
==> default: sed: can't read /etc/php/7.0/cli/php.ini: No such file or directory
==> default: sed: can't read /etc/php/7.0/apache2/php.ini: No such file or directory
==> default: ERROR: Module php7.0 does not exist!
/etc/php$ ls
7.1
```

Any idea on how I can install specifically 7.0? Didn't really find anything online about that. Everywhere says that this should install 7.0, but it doesn't. Perhaps, 7.0 is no longer supported for installation on Ubuntu 14?

**Comment by cbaykam** [comment]
provision with this one :  
https://gist.github.com/cbaykam/849d3a3deb89a3c11c637dcd4cb4a4c8

**Comment by XedinUnknown** [comment]
@cbaykam thanks for the reply. However, one thing worries me: I don't really need so many updates. I could live without latest Composer, ImageMagick, etc. There seem to be so many things getting installed. Do I really need to run all that?

**Comment by cbaykam** [comment]
Should be better now check again I removed the packages. 
You don't need that many packages that was my configuration and just sent it with removing the elasticsearch :)

**Comment by XedinUnknown** [comment]
@cbaykam, could you explain how it is any different from that provided by @maxpou? There are just fewer dependencies to install; it seems to not take into account certain edge cases that @maxpou did account for. Otherwise, it uses the same `php7.0` packages from Ondrej's PPA, which for me resulted in PHP 7.1 being installed.

Now, strictly speaking, I could do with PHP 7.1 just fine; however, the below doesn't work:
```bash
sudo sed -i 's/^;\(date\.timezone\) =\s*$/\1 = "Europe\/Paris"/g' /etc/php/7.1/cli/php.ini
sudo sed -i 's/^;\(date\.timezone\) =\s*$/\1 = "Europe\/Paris"/g' /etc/php/7.1/apache2/php.ini
```
Because for some reason, `/etc/php/7.1/apache2` does not exist :/ Any advice?

**Comment by cjke** [comment]
It's been over a year since I last replied to this thread, where I voiced my opinion that 5.6 should remain the baseline for the box. I stand by that statement made at that time. At the time 7 has just just entered active support. 

However since then, 5.6 has entered "security patches" only. It might not be last legs, but it is the next (equally to 7.0) to have it head on the chopping block.

It short, maybe its time to reevaluate the original stance. 

http://php.net/supported-versions.php

**Comment by XedinUnknown** [comment]
[Here](https://github.com/scotch-io/scotch-box/files/912280/switch-to-php7.txt) is what worked for me. At one point I realized that there's something odd about the syntax of `apt-get install`, and I corrected that; I'm not a Bash expert, and still don't understand why @maxpou wrote it like that, but according to the manual, the list of packages must be simply space-separated. Also, for some reason, the Apache config of PHP 7.0 came with `short_open_tag = Off`, so I fix that too, which should make Distillery's default `WPSeed` theme work straight away.

**Comment by maxpou** [comment]
Scotch box still run under Ubuntu 14.04.
According to this doc, I'm it gonna be a bit tricky to keep your box up to date. That's why I'd recommend you to upgrade Ubuntu to the latest LTS version.

BTW, I cannot really help you, I'm not using vagrant anymore.



> m not a Bash expert, and still don't understand why @maxpou wrote it like that

...because I'm also not a Bash expert 😄  
I setup this lines to avoid some warnings when the timezone isn't set. Maybe the default file is different with PHP 7.1

**Comment by XedinUnknown** [comment]
@maxpou, I meant the `apt-get install`. You are not giving it the packages; instead, you are just running install without package names, and then running *commands* like `php7.0`. Which are not commands ;) It's either that, or I don't understand anything :D

**Comment by maxpou** [comment]
> @maxpou, I meant the apt-get install. You are not giving it the packages; instead, you are just running install without package names, and then running commands like php7.0. Which are not commands ;) It's either that, or I don't understand anything :D

You mean this part:

```sh
sudo apt-get install -y \
    && php7.0 \
    && php7.0-fpm \
    && php7.0-mysql \
    && php-curl \
    && libapache2-mod-php7.0 \
    && php7.0-mbstring
```

This is for a bash script. If you wanna run everything separately in CLI, it should be something like this:
```sh
sudo apt-get install -y && php7.0 && php7.0-fpm && php7.0-mysql && php-curl && libapache2-mod-php7.0 && php7.0-mbstring
```

**Comment by XedinUnknown** [comment]
Bash and CLI is the same thing, essentially, AFAIK.

Could you explain what in your opinion that first part does the one with many `&&`?

**Comment by maxpou** [comment]
Don't worry about that. It come from a [Docker good practice](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#minimize-the-number-of-layers)

**Comment by XedinUnknown** [comment]
Nowhere there do they attempt to run package names as commands, @maxpou ;)

**Comment by arthur-olafsson** [comment]
Hint: Those `&&`s should probably be removed. That leaves you with a neat, multi-line apt-get command. Otherwise, it's interpreted as multiple commands.

**Comment by whatnickcodes** [comment]
New box update coming this week (finally!)

**Comment by mitchazj** [comment]
Any update on this?

**Comment by gitressa** [comment]
October CMS will require PHP 7 from July 2017: https://octobercms.com/support/article/rn-9

**Comment by adriangordon1231** [comment]
The most recent version of scotch box IS running php7 be default. I downloaded it today.

**Comment by gitressa** [comment]
I just created a fresh Scotch Box, as you can see it says `5.6.14`:
```
vagrant@scotchbox:~$ php -v
PHP 5.6.14-1+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```
Do you get another result?

**Comment by whatnickcodes** [comment]
For anyone who didn't realize:

'''
vagrant destroy
vagrant box update
'''

Make sure to backup first!

**Comment by drawcard** [comment]
> Make sure to backup first!

Just checking this action nukes any MySQL DB that a box would contain? Ie it's equivalent to formatting a server HD?

**Comment by whatnickcodes** [comment]
To my knowledge, yes. I'm not sure how Vagrant exactly handles updates but I would treat it as if a brand new image is being used

**Comment by drawcard** [comment]
Good to know!
