### ISSUE TITLE
Update WP-CLI for WordPress 4.4

### ISSUE THREAD

**Issue by kjohnson** [scotch-io/scotch-box#158]
The WP-CLI released compatibility updates for WordPress 4.4.

Source: http://wp-cli.org/blog/versions-0.21.1-and-0.20.4.html

**Comment by Lindstromer** [comment]
Would be lovely to have this fixed? Any status on when the box could be updated?

**Comment by luukdv** [comment]
Waiting for this too, any news?

**Comment by ncerminara** [comment]
In the next Scotch Box update (which there isn't anything super urgent for). Are you guys familiar how to update this yourself in the meantime?

**Comment by fuzzy76** [comment]
Yeah, this basically breaks wp-cli. Do a ```vagrant ssh``` and copy-paste this when standing in your home folder to upgrade:

```
curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && sudo mv wp-cli.phar /usr/local/bin/wp
```

**Comment by cclass** [comment]
@fuzzy76 tried this command and it failed with:

`Warning: Failed to create the file wp-cli.phar: Permission denied`
`curl: (23) Failed writing body (0 != 15639)`

**Comment by Lindstromer** [comment]
Have you tried it with sudo in front @cclass?

**Comment by cclass** [comment]
@Lindstromer @fuzzy76 running with sudo works, thanks

`sudo curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && sudo chmod +x wp-cli.phar && sudo mv wp-cli.phar /usr/local/bin/wp`

**Comment by kjohnson** [comment]
Thank, @fuzzy76 and @Lindstromer. Up to date.

**Comment by flurinduerst** [comment]
`sudo wp cli update --allow-root` should do the job aswell :)

**Comment by whatnickcodes** [comment]
This is fixed in the updating that's being released this week!
