### ISSUE TITLE
Multiple Installs

### ISSUE THREAD

**Issue by zackcote** [scotch-io/scotch-box#159]
I usually run multiple installs of scotch box by changing the IPs and Hostnames, but this still only allows me to run one at a time. What is the best way to configure multiple installs running simultaneously?

**Comment by jzohrab** [comment]
@zackcote, are you referring to running multiple scotch box VMs from the same vagrantfile?  If yes, ref https://docs.vagrantup.com/v2/multi-machine/index.html.

Below is a sample Vagrantfile:

    Vagrant.configure("2") do |config|
    
        config.vm.box = "scotch/box"
        config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    
        config.vm.define "n1" do |n1|
          n1.vm.network "private_network", ip: "192.168.33.10"
          n1.vm.hostname = "box1"
        end
    
        config.vm.define "n2" do |n2|
          n2.vm.network "private_network", ip: "192.168.33.11"
          n2.vm.hostname = "box2"
        end
    
    end

After running that, I have 2 separate VMs running:

    $ vagrant status
    Current machine states:
    n1                        running (virtualbox)
    n2                        running (virtualbox)

And I can ssh into each separately: `vagrant ssh n1` etc.

**Comment by zackcote** [comment]
Apologies for not closing this sooner -- I had an issue with vagrant and ssh port forwarding that interfered. Appreciate the thorough response though!
