### ISSUE TITLE
Option to allow more than 40GB storage capacity

### ISSUE THREAD

**Issue by dandonahoe** [scotch-io/scotch-box#160]
I'm importing a SQL dump file that's ~100GB, but the scotch-box appears to have a fixed size of 40GB. When I attempt most of the advice online of running:

``` bash
VBoxManage modifyhd "/Users/[name]/VirtualBox VMs/vagrant_default_1450926405979_88764/box-disk1.vmdk" --resize 128000
```

I get the error:

```
0%...
Progress state: VBOX_E_NOT_SUPPORTED
VBoxManage: error: Resize hard disk operation for this format is not implemented yet!
```

Is it possible to put the desired storage size in the Vagrant file?

**Comment by Braunson** [comment]
@dandonahoe Yes it is, havn't done it myself but..

```
config.vm.provider "virtualbox" do |vb|
  vb.customize "pre-boot", ["modifyhd", "disk id", "--resize", "size in megabytes"]
end
```

**Alternatively..**

You can resize the box itself like so: https://github.com/mitchellh/vagrant/issues/2339#issuecomment-112402297

Ref: https://github.com/mitchellh/vagrant/issues/2339

**Comment by zacker330** [comment]
@Braunson I got these errors with this config:

`
==> hadoop-namenode: Running 'pre-boot' VM customizations...
A customization command failed:

["modifyhd", :id, "--resize", 8096]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyhd", "c389bcec-a4ae-407c-972f-4e671fac9358", "--resize", "8096"]

Stderr: VBoxManage: error: The given path 'c389bcec-a4ae-407c-972f-4e671fac9358' is not fully qualified
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
>

Please fix this customization and try again.
`

**Comment by Braunson** [comment]
@zacker330 Have you instead tried option #2 resizing the box? https://github.com/mitchellh/vagrant/issues/2339#issuecomment-112402297

**Comment by ncerminara** [comment]
Adding this to the docs in next release. Thanks guys
