### ISSUE TITLE
Unable to download scotch box!

### ISSUE THREAD

**Issue by punyaruchal** [scotch-io/scotch-box#161]
While downloading scotch box getting this error.
![download-error](https://cloud.githubusercontent.com/assets/3156932/12062922/77202be2-afcd-11e5-94f4-e17106ce37db.png)

Any Idea what this happening?

**Comment by ncerminara** [comment]
Not sure what is happening. You can manually download the box here:

```
https://drive.scotch.io/scotchbox/2.5.0/
```

The resources is live and available

**Comment by punyaruchal** [comment]
Thanks @ncerminara the box was downloaded.

**Comment by Braunson** [comment]
:heart:  the animation here haha https://drive.scotch.io/

**Comment by punyaruchal** [comment]
Woww! nice love it.
