### ISSUE TITLE
PHP OPcode caching Not enabled

### ISSUE THREAD

**Issue by punyaruchal** [scotch-io/scotch-box#163]
I have enabled the OPchase in php.ini file, but still show the warning error when I was trying to install Drupal 8. it shows in a requirements review page:
"PHP OPcode caching Not enabled
PHP OPcode caching can improve your site's performance considerably. It is highly recommended to have OPcache installed on your server."

![php-opcache](https://cloud.githubusercontent.com/assets/3156932/12087696/2da514cc-b2fd-11e5-90e8-d9767d1702b2.jpg)

please help me what is this happening.

**Comment by ncerminara** [comment]
It's disabled for dev only. You can easily turn it back on. Do:

```
vagrant ssh
cd /etc/php5/apache2/conf.d
vim /etc/php5/apache2/conf.duser.ini
```

Just change the obvious line in there

**Comment by punyaruchal** [comment]
thank you very much!
