### ISSUE TITLE
Synced folder issue

### ISSUE THREAD

**Issue by jimlongo56** [scotch-io/scotch-box#166]
Great tool.

As stated in this issue https://github.com/scotch-io/scotch-box/issues/156

Out of the box the Vagrantfile worked fine for me (OS X 10.11.2), but when I tried to sync a folder it could not find the URL until I added /public like so

    # config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    config.vm.synced_folder "/Volumes/Dev/Code/", "/var/www/public", :mount_options => ["dmode=777", "fmode=666"]

**Comment by ncerminara** [comment]
This is intentional

**Comment by ncerminara** [comment]
(I think) what you have here is custom and unique and not necessarily and issue
