### ISSUE TITLE
Vagrant issue on El Capitan?

### ISSUE THREAD

**Issue by latwelve** [scotch-io/scotch-box#168]
It's not an exclusive issue to Scotch but I can't find a solution... NFS enabled, SSD selected for storage and the local environment is still much slower than a tiny do droplet... it's not my system it's top spec i5 and 16gb of ram with nothing else going on... 

How are people finding vagrant a usable environment on el capitan? it'd be quicker for me to rsync to a live server! I was hoping to drop mamp for a speed improvement on vagrant but it's even worse :/

**Comment by ncerminara** [comment]
Vagrant is pretty snappy for me. This isn't a Scotch Box issue though, so I'm going to close this one.

Also see this: https://github.com/scotch-io/scotch-box/issues/144
