### ISSUE TITLE
Web server at 192.168.33.10 does not work.

### ISSUE THREAD

**Issue by gemblue** [scotch-io/scotch-box#169]
Scotch box is successfully installed. 

Vagrant up -> Done
Vagrant ssh -> Done, i have entered shell. 

After that i try to check the running web server and access 192.168.33.10, but scotch box welcome page is not found. I also check 127.0.0.1, not found too.

Any suggestion? thank you..

**Comment by dasmikko** [comment]
Same thing here.

**Comment by gemblue** [comment]
thanks @dasmikko . It works :+1:

**Comment by cjduncana** [comment]
I have this same problem, but the solution provided here did not help.

**Comment by vbroskas** [comment]
Did we ever find a solution to this problem? I'm getting the same error (page is timing out) and disconnecting the wifi didnt work

**Comment by wickywills** [comment]
Same issue, no working solution.

**Comment by hirushacooray** [comment]
same here. disconnecting wifi didn't work.
