### ISSUE TITLE
can't connect to MySQL using Workbench or Terminal

### ISSUE THREAD

**Issue by staadecr** [scotch-io/scotch-box#170]
I'm new to MySQL.  I've installed both the server and workbench.  In System Preferences, it shows that MySQL is actively connected.  However, when attempting to connect to the server using Workbench, I get: "Failed to Connect to MySQL at localhost:3306"

I've read a million threads but cannot find any solution.  Some help would be greatly appreciated.

I'm on a Mac.

**Comment by fuzzy76** [comment]
Sounds like #155 ?

**Comment by ncerminara** [comment]
You need to SSH tunnel first.
