### ISSUE TITLE
database disappeared

### ISSUE THREAD

**Issue by ianrobertdouglas** [scotch-io/scotch-box#171]
I've used Scotchbox for a while for different projects. It's great, but yesterday I encountered a critical problem.

Recently I was building a Wordpress site, and all was fine. Yesterday I start up that Scotchbox install as usual (via Vagrant Manager under OSX10.11.2) and go to my custom url (example.dev) and I get the initial window you find in Wordpress before a database has been created.

I immediately halted the Scotchbox VM.

Opening Virtualbox, I can see (for reasons unknown) three VMs with the name I chose for the project: one whose name I edited in Virtualbox, and the other two with "name_default_xxxxxxxxxxxxxx".

What I hope is that for some reason Vagrant Up is starting the wrong box, and that in one of those VMs is my database.

When I start up the VM from Vagrant Manager, and then use Sequel Pro to SSH into the database via my custom private network IP, I can get in, see the database (named scotchbox, as in the default name), open it, but there's no tables there.

But again, maybe Vagrant is starting up the wrong VM, though how this happened I have no idea.

So: 1) Is there a way to repoint my Vagrantfile so it starts up, in turn, the other two VMs that show up in Virtualbox? That way, I can start them up and see if my Wordpress site is alive in one of them.
2) Is there any other way of physically tracing my database in my file system, or even the file system of the three VMs? Where does Scotchbox store databases?

I'm pretty screwed if I lost that database. I didn't (stupidly) take a backup within Wordpress. I can think of no reason or action that would wipe it. But I did update Virtualbox itself, and the Extension Pack. But that's pretty much all I changed recently.

Worryingly, my other Scotchbox installs appear to be okay.

Any thoughts, help or guidance much appreciated!

**Comment by ianrobertdouglas** [comment]
So, continuing to research and try to answer my own question, I come across this thread that seemed to suggest that you can replace the file "id" in project_ folder/.vagrant/machines/default/virtualbox/

I was able to get the UUIDs of the three VMs that relate to my project by running the Terminal command `VBoxManage list vms` when in the directory that contains the Vagrantfile of my project.

I then created three files with the name "id" in folders on my Desktop, by running the following command in each folder successively:

`echo -n '<UUID number>' > id`

The UUID looks something like this: 9926dcae-cd93-4ca5-b8ca-48a92c239d2d

I was concerned not to make a bad situation worse by making extra mistakes, but after waiting for a while I went ahead and instead of moving the id files to project_ folder/.vagrant/machines/default/virtualbox/ I used the following command on what I thought was the most likely VM UUID:

echo -n "<VM UUID here>" > .vagrant/machines/default/virtualbox/id

Then I ran vagrant up and it worked. My database is back, and my site. No idea why Vagrant replaced it with an empty duplicate ...

**Comment by ncerminara** [comment]
Awesome - And nice, nice save.

- So I would run a backup now of everything.
- Destroy all the VMs
- Restart them

**Comment by ianrobertdouglas** [comment]
Thank you, Nick. That's exactly what I'll do.

**Comment by ncerminara** [comment]
I've had similar scares with the databases being lost with the VM. Some things (Laravel) have database migrations and seeding so it really doesn't matter.

But with WordPress everything's tied to the DB. It might make sense to have a script dump the database to `dump.sql`. Then you can just run this real quick before suspending your machine.

Even cooler, you can have that script execute on `vagrant suspend` via this plugin: https://github.com/emyl/vagrant-triggers

**Comment by ianrobertdouglas** [comment]
By the way, in my VVV install, [Vagrant Triggers](https://github.com/emyl/vagrant-triggers) automatically runs a script in the VVV configuration that dumps a DB backup in a normal folder. Is there a way to do this with Scotchbox? It shouldn't replace being diligent, in my case taking backups from within Wordpress. But it would sure help, in case of emergencies, like the one I faced.

This is the description from the [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) page:

> By default, if vagrant-triggers is installed, a db_backup script will run on halt, suspend, and destroy that backs up each database to a dbname.sql file in the {vvv}/database/backups/ directory. These will then be imported automatically if starting from scratch. Custom scripts can be added to override this default behavior

**Comment by ncerminara** [comment]
Something like this:

```
 # run some script before the guest is destroyed
  config.trigger.before :suspend do
    info "Backing up scotchbox db"
    run_remote  "bash /var/www/backup.sh"
  end
```

Then `backup.sh` could be like this:

```
mysqldump -u root -proot scotchbox > "/var/www/dump.sql"
```

Would need to test/verify everything though

**Comment by ncerminara** [comment]
Also I should note, I try not to use plugins to be dependency free and avoid things breaking get out of date. But this might be a good use case for you

**Comment by ianrobertdouglas** [comment]
We had the same thought simultaneously :) My next question would be, given that I don't in general rename the database from your own default (scotchbox), and I have multiple projects that use Scotchbox, would it possible, for example, to dump the database in my project folder, or relative to the Vagrantfile in question, so as to keep database backups separate and not have them potentially overwritten, given that they would have the same file name?

**Comment by ncerminara** [comment]
Why not just have this in each of your project folders? I would do it like this:

![Thoughts](http://i.imgur.com/Avc2mTB.png)

1 VM per project. Copy the bash script for each new project.

**Comment by ianrobertdouglas** [comment]
That would be perfect. Sorry, I'm just an idiot with code. 

`run_remote  "bash /var/www/backup.sh"`

I'm stumbling on the directory structure here. And also here:

`mysqldump -u root -proot scotchbox > "/var/www/dump.sql"`

My project is in ~/Home/Scott

In that folder is my Vagrantfile and public. I just need to be clear where to create the backup.sh file, and what directory structure should be in it that matches where I drop it.

Or ... wait a minute. The VM thinks my actual directory is /var/www/ ?

**Comment by ncerminara** [comment]
I would need to look. But **I think** the script is executed from inside the VM (not your local machine). That's why the paths are setup that way.

**Comment by ncerminara** [comment]
To explain even further. If you ssh into the VM. 

```
cd /var/www
ls -al
```

You should see `Vagrantfile`, `public/`, etc.

**Comment by ianrobertdouglas** [comment]
It works perfectly! I created the backup.sh file with the following command:

`echo -n 'mysqldump -u root -proot scotchbox > "/var/www/dump.sql"' > backup.sh`

Then I put the other code in my Vagrantfile, saved and reloaded vagrant, and then ran Vagrant suspend.

The script executed and I have a dump.sql file in my project folder. Fantastic! I ran Vagrant up and Vagrant suspend again, and it overwrote that file with an updated version. Excellent. Thank you so much, Nick! For this and all your work.

One final thing: I often do Vagrant halt, as I keep my VMs on a USB SSD drive that I often disconnect. So I guess I feel that's safer somehow. Should I duplicate the trigger command as follows:

```
 # run some script before the guest is destroyed
  config.trigger.before :halt do
    info "Backing up scotchbox db"
    run_remote  "bash /var/www/backup.sh"
  end
```

Or is there a more elegant way of having that one code line look for suspend, halt and destroy all at once?

**Comment by ncerminara** [comment]
Awesome. I'm going to mess with this and add it to the docs in 3.0.

Doing twice isn't elegant, but it works. I don't know Ruby that well but I think you can also try:

```
  config.trigger.before [:suspend, :halt] do
    info "Backing up scotchbox db"
    run_remote  "bash /var/www/backup.sh"
  end
```

Or maybe this:

```
{
    :suspend,
    :halt,
}.each do |command, trigger|
    config.trigger.before :halt do
      info "Backing up scotchbox db"
      run_remote  "bash /var/www/backup.sh"
    end
end
```

Probably test and check syntax

**Comment by ncerminara** [comment]
I would add destroy too to be safe haha

**Comment by ianrobertdouglas** [comment]
:) Why not. This syntax works perfectly on halt, so I'm sure destroy works too.

```
 config.trigger.before [:suspend, :halt, :destroy] do
   info "Backing up scotchbox db"
   run_remote  "bash /var/www/backup.sh"
 end
```

Thank you so much, Nick, for taking the time with me on this, and for this great solution! I really appreciate it!

**Comment by ncerminara** [comment]
No problem!

**Comment by ianrobertdouglas** [comment]
Hi Nick. Sorry to bump this old thread, but the code I was using above now fails after I was obliged to update to Vagrant 2.1.5 (I had to update Virtualbox to run under Mojave, and this required also updating Vagrant). 
I get the following error:
`Message: undefined method "info" `
Removing this code snippet allows Vagrant Up to work fine.
Perhaps it has to do with the vagrant triggers plugin moving into Vagrant core. I believe some syntax changed.
Would you happen to know, off hand, how to amend this code snippet so I can continue to grab backups on suspend, halt and destroy?
