### ISSUE TITLE
Change ServerName/ServerAlias to anything except *.local in the scotchbox.conf

### ISSUE THREAD

**Issue by cjke** [scotch-io/scotch-box#172]
Mac OS X uses .local for it's bonjour service. Although this doesn't _always_ cause an issue, it can often cause very long latency for requests. 

Changing it almost definitely causes request latency to drop off completely. 

Not sure what the alternative be, possible .dev, .scotch, .internal, .anything (?)

**Comment by Braunson** [comment]
@cjke I've had the same issue on Mac with this, ended up using .dev :smile:

**Comment by cjke** [comment]
@Braunson Ya, it's a bit of a silent issue, as it's doesn't (for me anyway) always cause issues, but sometimes I notice the latency increasing and increasing. It took me a while to track down as I didn't even consider the .local would be impacting the box.

**Comment by ncerminara** [comment]
I thought .local was the official standard?

**Comment by cjke** [comment]
I'm not sure of any official standard to be honest. This isn't an issue particular to scotch box, but any development environment that may use .local. 

Best info I could find was here:
http://stackoverflow.com/questions/10064581/how-can-i-eliminate-slow-resolving-loading-of-localhost-virtualhost-a-2-3-secon (second answer)

https://www.bram.us/2011/12/12/mamp-pro-slow-name-resolving-with-local-vhosts-in-lion-fix/

**Comment by ncerminara** [comment]
A lot of people use `.app` or `.dev`. The only reason I didn't was because I was under the impression that the "standard" is/was `.local`.

**Comment by cjke** [comment]
Sorry I can't really comment on the standard - I haven't really come across one. 

Honestly happy to close this off as a "not really worth it" - but at least if someone stumbles across the issue when searching for "slow" they should see this conversation and can manually change it to ".somethingelse"

**Comment by ncerminara** [comment]
Okay - I'm closing this. Thanks for flagging for everyone who faces this issue.

Even if it is an "official" standard, it really doesn't matter. I'll consider swapping this in the next release
