### ISSUE TITLE
Performance Issues?

### ISSUE THREAD

**Issue by Braunson** [scotch-io/scotch-box#173]
I've just downloaded scotch box, put a fresh WP install and it took 19.9 seconds to load.. I've edited the `Vagrantfile` with

```
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
```

But it doesn't really make much of a difference (yes I did vagrant provision/vagrant reload).

Any thoughts on this? It only seems to be slow on ScotchBox.. I tried it on a PuPHPET config vagrant box and it was much quicker (but PuPHPET is much less reliable when it comes to updates)

**Comment by jesse9212** [comment]
Having this issue on Windows. I've also tried 

        v.memory = 4096
        v.cpus = 4

**Comment by ncerminara** [comment]
This wouldn't really be a Scotch Box issue. Try enabling NFS
