### ISSUE TITLE
Mysql will not start

### ISSUE THREAD

**Issue by mattkaye** [scotch-io/scotch-box#174]
Randomly, mysql is not able to start. I get job failed error. I found this thread on stackoverflow and these steps did fix the problem for a few hours:

sudo service mysql stop
sudo rm /var/lib/mysql/ib_logfile0
sudo rm /var/lib/mysql/ib_logfile1

But now it's back and won't start even after I try those steps. Is this a scotchbox thing or a vagrant thing? Can anyone help me out here?

**Comment by ncerminara** [comment]
It probably doesn't have enough memory. Try provisioning with this in your `Vagrantfile`:

```
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
```

**Comment by mattkaye** [comment]
Where exactly do I place that code in the Vagrant file?

**Comment by ncerminara** [comment]
Middle

**Comment by mattkaye** [comment]
No difference. Here is my file:

`# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

    config.vm.provision "shell", inline: <<-SHELL

        ## Only thing you probably really care about is right here
        DOMAINS=("ustaflorida.afteractivestage.dev" "cityofwinterpark.org.dev" "moorewomenartists.org.dev" "kybella.dev")

        config.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 2
        end

        ## Loop through all sites
        for ((i=0; i < ${#DOMAINS[@]}; i++)); do

            ## Current Domain
            DOMAIN=${DOMAINS[$i]}

            echo "Creating directory for $DOMAIN..."
            mkdir -p /var/www/$DOMAIN/public

            echo "Creating vhost config for $DOMAIN..."
            sudo cp /etc/apache2/sites-available/scotchbox.local.conf /etc/apache2/sites-available/$DOMAIN.conf

            echo "Updating vhost config for $DOMAIN..."
            sudo sed -i s,scotchbox.local,$DOMAIN,g /etc/apache2/sites-available/$DOMAIN.conf
            sudo sed -i s,/var/www/public,/var/www/$DOMAIN/public,g /etc/apache2/sites-available/$DOMAIN.conf

            echo "Enabling $DOMAIN. Will probably tell you to restart Apache..."
            sudo a2ensite $DOMAIN.conf

            echo "So let's restart apache..."
            sudo service apache2 restart

        done

    SHELL

end
`

**Comment by ncerminara** [comment]
Firstly, it's typically a bit better doing 1 VM per project versus the multiple domains thing. I only really added that for people with very low storage computers or projects with multiple URLs.

Open Virtual Box, what does it read for your memory?

**Comment by mattkaye** [comment]
But i thought a new VM for each project would be huge amounts of space taken from my hard drive. Am I wrong on that? My VM has a base memory of 2048MG and is running 2 processors

**Comment by ncerminara** [comment]
It's like I think 2-4gb per project. So not that many. If a project is dormant/completed. I usually just backup the DB and destroy the VM to free the space.

I'm not sure why your MySQL keeps crashing though. My only thoughts were it was running out of memory because some crazy huge DB, table, or intensive query.
