### ISSUE TITLE
Scotch Box won't download / not found

### ISSUE THREAD

**Issue by ncerminara** [scotch-io/scotch-box#178]
Been getting a lot of comments about this. We are looking into.

Our server isn't down:

![screenshot](http://i.imgur.com/oFuijwO.png?1)

**Comment by ncerminara** [comment]
My thoughts:

- Our server is blocking Hashicorp
- Something weird with Vagrant
- Something weird with Hashicorp/Vagrantcloud/Atlas

**Comment by ncerminara** [comment]
Direct download can be found here: https://drive.scotch.io/scotchbox/

Here's an example of what to add to your Vagrantfile:

```
config.vm.box = "scotch/box"
config.vm.box_url = "https://drive.scotch.io/scotchbox/2.5.0/scotch.box"
```

Or to add it locally:

http://stackoverflow.com/questions/22065698/how-to-add-a-downloaded-box-file-to-vagrant

**Comment by alomsimoy** [comment]
I've resolved the problem by replacing the curl.exe binary from vagrant with the one manually downloaded from the [curl download page](https://curl.haxx.se/download.html) as described here:

[http://stackoverflow.com/questions/34556929/vagrant-box-add-fail-solved](http://stackoverflow.com/questions/34556929/vagrant-box-add-fail-solved)

**Comment by minimalchaos** [comment]
The problem is not with your server. The culprit is the curl binary shipped with vagrant. Replacing it with the latest binary like mentioned by @alomsimoy fixes the download issue.

**Comment by ncerminara** [comment]
Well that's frustrating. Going to close this though

**Comment by saikatm** [comment]
@whatnickcodes i was looking for a direct download link for scotch, thanks man.

**Comment by saikatm** [comment]
@whatnickcodes i was looking for a direct [download link](https://drive.scotch.io/scotchbox/), thanks man! ​:thumbsup:​ :smiley:
