### ISSUE TITLE
Scotch Box And Jekyll

### ISSUE THREAD

**Issue by juicymark** [scotch-io/scotch-box#18]
Hi

I have downloaded scotch box and got it setup nicely with additional apache virtual hosts and wish to use this box as my main development box.

However i also wish to develop jekyll sites on this box,, so i installed the jekyll gem and can create a new jekyll site.

However for the life of me i cannot view the generated site on my local browser

i have added a line to the Vagrantfile to forward the ports and have tried 

config.vm.network :forwarded_port, host: 4000, guest: 4000
and
config.vm.network :forwarded_port, host: 8080, guest: 4000

then going to my local browser, trying the following

http://127.0.0.1:4000
http://127.0.0.1:8080
http://0.0.0.0:4000
http://0.0.0.0:8080

But i cannot view the generated site.

Regards

Mark

**Comment by justinluk** [comment]
For anyone else running into this issue, I found that running jekyll like this: 
jekyll serve --host 0.0.0.0

Allowed the portforwarding to work. Then you can access the jekyll server inside the VM from outside in browser by going http://hostname:4000 (change the port to be whatever you have it set to in your Vagrantfile)
