### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by andrecastelo** [scotch-io/scotch-box#182]
I have a number of APIs under development that I wanted to bring over from XAMPP to ScotchBox. They are consumed by Angular apps, with Gruntfiles that create local servers (for livereload, watch, injects, etc), so I run those on the host machine - with the APIs on Scotch Box. 

But it doesn't work. I've tried fiddling with the hosts file (I'm in Windows) to no avail. 

It works in production and with Xampp. I'm sending the CORS headers. Here are the requests from Firefox and the same request made using Postman:

![image](https://cloud.githubusercontent.com/assets/726360/12878161/d483337c-ce06-11e5-854c-485cba732a8e.png)

**Comment by ncerminara** [comment]
Just setup hostnames or CORS
