### ISSUE TITLE
host not working

### ISSUE THREAD

**Issue by hoppities** [scotch-io/scotch-box#183]
Hi,

I cloned Scotch Box 2.5 into a new directory, added a new folder in public to `<?= 'hello, world.'; ?>`, and I added a new entry in sites-available:

```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ServerName gotential.local
        ServerAlias www.gotential.local
        DocumentRoot /var/www/public/gotential
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

I ran `sudo a2ensite gotential.local.conf`, and then I ran `service apache2 reload`.

This is the relevant hosts file
`192.168.33.10   helpr.dev`
`192.168.33.10   scotchbox.local`
`192.168.33.10   beanstalkd.console.local`
`192.169.33.10   gotential.local`

helpr.dev works, but that was created in a different directory on an older version of Scotchbox. Since then, I have updated that box, and it has the same issue.

Any idea why I can't get these urls to resolve? On my new box, scotchbox.local works, but nothing else will.

**Comment by ncerminara** [comment]
Just tested and this definitely works. This is likely a misconfiguration.

It's just like any server. Here's how to do it automatically with provisioning: https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#multiple-domains-(virtual-hosts)

Also, here's the exact steps I took to just get it working replicate:

```
git clone https://github.com/scotch-io/scotch-box testing123
cd testing123
vagrant up
vagrant ssh
cd /etc/apache2/sites-available
sudo cp scotchbox.local.conf whatever.local.conf
# Then use vim or whatever to replace all instances of "scotchbox.local" with "whatever.local". Make sure to also set the path to /var/www/public/whatever and save that
sudo a2ensite whatever.local
# Make sure the directory /var/www/public/whatever exists. Put a file in there as index.php
sudo apache2 restart
```

Then in your hosts file do:

```
192.168.33.10 scotchbox.local
192.168.33.10 whatever.local
```


This will work. Also:

- Your hosts file has a different IP address on one of them for whatever reason. That's probably a type or wrong. Scotch Box is 1 IP

**Comment by PrawnSkunk** [comment]
192.169.33.10 should be 192.168.33.10.

**Comment by codeulardev** [comment]
Somehow my hosts keep getting commented out. I am not sure if this is Scotch Box or Vagrant related but I enable the hosts and after a while everything comes to a halt then I check the hosts and they are commented out again. Anyone else experiencing the same issue?
