### ISSUE TITLE
Scotch Box Vagrant Error.

### ISSUE THREAD

**Issue by rnaby** [scotch-io/scotch-box#189]
Hello,

I'm trying to install Scotch Box. But I'm getting this error. Can you please help.
I'm in Windows 8.1 machine.
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

I've tried several things but not worked out for me. It would be great if you guys can help.

**Comment by cjduncana** [comment]
Hi there! Even though I am using Ubuntu, I had the same problem. I came across [this article](https://scotch.io/bar-talk/announcing-scotch-box-2-5), and suggested me to add the following to the Vagrantfile:

```
config.ssh.username = "vagrant"
config.ssh.password = "vagrant"
```
Now it works fine. I know it does not solve the problem, but at least now you can use the box.

**Comment by kshamsuddin** [comment]
Hi, I'm having the same problem. Then I added below to vagrantfile 
     config.ssh.username = "vagrant"
     config.ssh.password = "vagrant"
and vagrant up. However, I got the following error:

    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Importing base box 'scotch/box'...
    ==> default: Matching MAC address for NAT networking...
    ==> default: Checking if box 'scotch/box' is up to date...
    ==> default: Setting the name of the VM: local-server_default_1457198371829_7646
    ==> default: Clearing any previously set network interfaces...
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
        default: Adapter 2: hostonly
    ==> default: Forwarding ports...
        default: 22 (guest) => 2222 (host) (adapter 1)
    ==> default: Booting VM...
    There was an error while executing `VBoxManage`, a CLI used by Vagrant
    for controlling VirtualBox. The command and stderr is shown below.
    
    Command: ["startvm", "47af6fe7-aa62-4aa6-89d8-e2518f364183", "--type", "headless"]
    
    Stderr: VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
    VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

My OS: Windows 10
Varant: 1.8.1
VirtualBox: 5.0.15 r105836

I have removed and reinstalled vagrant and different version of VB. Yet no luck. Really appreciate your help. 

MAny thanks.

**Comment by satinrichu** [comment]
Please assist as i seem to have similar issues
