### ISSUE TITLE
Scotch Box from Atlas repository with non-functioning Apache

### ISSUE THREAD

**Issue by cjduncana** [scotch-io/scotch-box#190]
I originally downloaded the Scotch Box 2.5 from the Atlas repository, and it was not working out-of-the-box. It had that odd authentication problem, but I could get around it with the suggestion at [Scotch Box](box.scotch.io). Once I had the box running, I went to the IP address provided, but the connection timed out. Since I already found this website, I tried the instructions found here, and this box does function out-of-the-box.

I do not see why one box is different from the other.

**Comment by ncerminara** [comment]
Scotch Box is simply a pre-provisioned Vagrant LAMP box
