### ISSUE TITLE
Vagrant Share a virtual host in Scotch Box

### ISSUE THREAD

**Issue by cjduncana** [scotch-io/scotch-box#191]
Using the instructions found in [this article](https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved), I was able to set up multiple sites in Scotch Box. I want to share one of the sites, but when I `vagrant share` only the content of public is shown. For example, I have a site at test.dev and its content are stored at test.dev/public, but I do not know how to share using `vagrant share`. Is this possible?

**Comment by palibaacsi** [comment]
You'll have to set up an account on Hashicorp, then after running **vagrant up**, you'll login to your account from the command line with **vagrant login**.  Check out:

[(https://www.vagrantup.com/docs/getting-started/share.html)]

**Comment by ncerminara** [comment]
Not sure exactly how that will work with Atlas. You're better off doing one project per VM, IMO
