### ISSUE TITLE
How to use MailCatcher

### ISSUE THREAD

**Issue by palibaacsi** [scotch-io/scotch-box#194]
I'm trying to check outgoing email in a local environment using WordPress and the plugin Check Email. The plugin tells me that my path is:

SendMail path (UNIX): /usr/bin/env /home/vagrant/.rbenv/shims/catchmail -f dev@scotchbox.local

in Terminal when I check, which mailcatcher, I get

 /usr/bin/mailcatcher

I've tried enabling it with mailcatcher --http-ip=0.0.0.0.

What am I doing wrong?

**Comment by ncerminara** [comment]
Hey Paul, long time.

Did you figure this out? PHP mail function should just work without having to do any configuration. All the emails are captured in mailcatcher only after it's enabled.

**Comment by maxpou** [comment]
Hi,

Before all, run : 

```
mailcatcher --http-ip=0.0.0.0
```

Try to execute this basic script: (pick from: http://php.net/manual/fr/function.mail.php)

```php
<?php
//mail.php
mail('test@example.com', 'Hello world', 'wohoo!');
```

Make sure that PHP is sending mail thought smtp://127.0.0.1:1025 (check into php.ini).
And visit http://192.168.33.10:1080/

If everything works, open issue in another github repo (WordPress / plugin Check Email).
You can also erase php.ini with ini_set function (but it's ugly)

```php
ini_set('SMTP','127.0.0.1');
ini_set('smtp_port',1025);
```

**Comment by deadstar1** [comment]
@whatnickcodes how can I use exim4 instead of mailcatcher?? I have added this line in php.ini to use exim4 as default but does not work.
`sendmail_path="/usr/sbin/exim4 -t -i"`
