### ISSUE TITLE
Vagrant error on Windows 10

### ISSUE THREAD

**Issue by kshamsuddin** [scotch-io/scotch-box#195]
Hi, 
I have tried to use the scotch box in my windows 10 machine for last two days. Every time I git clone and vagrant up I'm getting the following error: 

    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Importing base box 'scotch/box'...
    ==> default: Matching MAC address for NAT networking...
    ==> default: Checking if box 'scotch/box' is up to date...
    ==> default: Setting the name of the VM: local-server_default_1457198371829_7646
    ==> default: Clearing any previously set network interfaces...
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
        default: Adapter 2: hostonly
    ==> default: Forwarding ports...
        default: 22 (guest) => 2222 (host) (adapter 1)
    ==> default: Booting VM...
    There was an error while executing `VBoxManage`, a CLI used by Vagrant
    for controlling VirtualBox. The command and stderr is shown below.
    
    Command: ["startvm", "47af6fe7-aa62-4aa6-89d8-e2518f364183", "--type", "headless"]
    
    Stderr: VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
    VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

My OS: Windows 10
Varant: 1.8.1
VirtualBox: 5.0.16

I have removed and reinstalled vagrant and different version of VB. Yet no luck. Can anybody please advise. 
Many thanks.

**Comment by minimalchaos** [comment]
Virtualization is disabled from your bios. You will need to enable it in your bios settings before running the same.

**Comment by gere** [comment]
I just solved this problem and for me it wasn't the virtualization disabled in the bios, but Windows Hyper-V that **must be disabled** in Control Panel -> Program And Features -> Turn Windows Features on or off.

**Comment by kshamsuddin** [comment]
Thanks. Turning on the visualization settings from bios did the trick for me.

**Comment by satinrichu** [comment]
I am having similar issues. I have HYPER-V disabled and dont see any option for checking virtualization, Please advise.

**Comment by Manjitsingh** [comment]
No HYPER-V in system, what should i do to resolve the issue ?

**Comment by indrakaw** [comment]
@Manjitsingh be sure IIS is disabled.

**Comment by Manjitsingh** [comment]
Forget it :+1: I have shifted to Linux though

**Comment by aquibiqbal** [comment]
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'hashicorp/precise64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'hashicorp/precise64' is up to date...
==> default: There was a problem while downloading the metadata for your box
==> default: to check for updates. This is not an error, since it is usually due
==> default: to temporary network problems. This is just a warning. The problem
==> default: encountered was:
==> default:
==> default: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
==> default:
==> default: If you want to check for box updates, verify your network connection
==> default: is valid and try again.
==> default: Setting the name of the VM: amiqba_default_1470672999758_24287
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "0b5a2447-4a5c-46ea-a63d-81b765b92205", "--type", "headless"]

Stderr: VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

I tried to resolve this issue , I dont find HYPER-V in my system and the virtualization is already enabled in it

**Comment by tiagodurante** [comment]
On BIOS, you need to enable the virtualization. In my case, this propriety calls 'Intel Virtualization'. [Image](http://vsphere-land.com/wp-content/uploads/bios1.png)

**Comment by JCHutchinson** [comment]
gere's comment solved the issue for me. But I had to do one more thing, and that was to stop hyper-v from loading when the machine is booted.

run the commands found at this link in the Command Prompt as Administrator

https://blogs.technet.microsoft.com/gmarchetti/2008/12/07/turning-hyper-v-on-and-off/

**Comment by mnpenner** [comment]
To be clear, gere is referring to this setting:

![](http://i.imgur.com/ZjP2KIC.png)

Disable/uncheck that. Worked for me. You have to reboot afterwords.

**Comment by galdiolo** [comment]
![image](https://cloud.githubusercontent.com/assets/448620/23822994/4ab0e0fa-0626-11e7-8505-1bca0206a45c.png)
@mnpenner is right, Vagrant with VirtualBox cannot work with Docker at the same time.

**Comment by hsilvest** [comment]
Enable "Intel Virtualizaton" on BIOS Works for me thank you @minimalchaos you save me some hours of researching

**Comment by indrakaw** [comment]
does it effect of dual-boot or grub?

**Comment by nylonjed** [comment]
Windows 8 (Microsoft Windows [Version 6.3.9600]) - without uninstalling Hyper-V (assuming you have virtualization enabled in your BIOS).

Open CMD as Administrator:
**Disable**
dism.exe /Online /Disable-Feature:Microsoft-Hyper-V
Reboot
**Enable**
dism.exe /Online /Enable-Feature:Microsoft-Hyper-V
Reboot

There are other ways. I tested this and vagrant loaded up without the error.

**Comment by arunmlvtec** [comment]
@nylonjed 
I am running vagrant and virtual box on Windows 10.  I am also stuck at the same issue. Screenshot as below:
![image](https://cloud.githubusercontent.com/assets/8803326/24931706/1fed6e5a-1ec3-11e7-90a4-f488dc2449e9.png)

I followed your instruction which is for Windows 8 just to see if that could help, but it didn't. Screenshot below:
![image](https://cloud.githubusercontent.com/assets/8803326/24931650/dfdbd950-1ec2-11e7-81d4-3c8813b71ddc.png)

If there is any suggestion from your side to resolve this issue, please feel free to share.

**Comment by nhjiejan** [comment]
I was still getting the problem after I enabled virtualisation on the BIOS. downgarding to 1.9.3 seemed to work for me

**Comment by frutality** [comment]
For me it was Windows 10 Creators Update. VirtualBox become broken completely. Even VB UI wasn't working. Hyper-V was disabled, virtualisation in BIOS was enabled.

There is what helped:
1. Uninstalling VirtualBox 
2. Downloading and installing latest version of VirtualBox

**Comment by indrakaw** [comment]
@frutality, don't forget:

1. b. Restart PC

**Comment by frutality** [comment]
@indrakaw actually, I didn't restart my PC, it started to work right after installing latest VirtualBox. But good advise still.

BTW, if you are using Guest Additions, you also need to upgrade it by downloading from website OR launching VB GUI. If latter, VB offers you to upgrade Guest Additions.

**Comment by petertflem** [comment]
I the same problem as some of the others here:
`There was an error while executing `VBoxManage`, a CLI used by Vagrant                        
for controlling VirtualBox. The command and stderr is shown below.                            
                                                                                              
Command: ["startvm", "c3f29697-e429-40a1-8491-659ea5363324", "--type", "headless"]            
                                                                                              
Stderr: VBoxManage.exe: error: The virtual machine 'dev' has terminated unexpectedly during st
artup with exit code 1 (0x1).  More details may be available in 'C:\Users\pettol\VirtualBox VM
s\dev\Logs\VBoxHardening.log'                                                                 
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMa
chine`

I'm on Windows 7.

I solved it by updating VirtualBox.

**Comment by glebsts** [comment]
Solved by uninstall-restart-install VB. Just upgrade didn't help. HyperV was disabled, and it was windows update who broke it.

**Comment by eborremans** [comment]
FWIW: i usually get these problems after a windows update. updating to the latest version of both Vagrant and VMBox usually solves the issue. Not sure if your 'different' version is indeed the latest version.

**Comment by guptap11** [comment]
I am also facing the same issue 
Stderr: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
I have disabled Hyper-V , restarted my machine, have the latest version on Vagrant and VB as well. Still I am getting the same error. Any suggestion how to make it work ?

**Comment by eborremans** [comment]
@guptap11 did you enable virtualization in your Bios?

**Comment by bensonism** [comment]
Windows update broke my VBox also. Installing vbox over the top without uninstalling and deleting the machine.lock file in vagrant.d/data fixed my issue.

**Comment by guptap11** [comment]
@eborremans Yes virtualization is enabled in bios.

**Comment by eborremans** [comment]
@guptap11 I checked [ VT-x is not available... ](http://druss.co/2015/06/fix-vt-x-is-not-available-verr_vmx_no_vmx-in-virtualbox/). Last possibility I can think of is 'Your CPU doesn’t support VT-x or AMD-V virtualization'. If that is the case I am afraid there is no immediate solution other than replace your CPU. Other than that I am afraid I am out of suggestions.

**Comment by whatnickcodes** [comment]
Make sure to check Vagrant's Issues too for similar reasons since this isn't specific to scotch box 

https://github.com/mitchellh/vagrant

**Comment by JayOwl** [comment]
The newest windows update changed my path map away from my virtual box. A reinstall and update of virtual box reset the mappings to the correct location. My current windows version is Windows 10 Pro 1703

**Comment by albertompz** [comment]
Disabled Hyper-V. Now works

**Comment by detool** [comment]
@frutality thanks!, works for me; updated from 5.0.26 to 5.1.28 in Windows 10

**Comment by hilleer** [comment]
I had a similar issue on windows 10. 
I fixed it by **updating** vagrant to version `2.0.0` and virtualbox to `5.1.30`.

**Comment by sandeshchaudhari** [comment]
I'm running following versions of virtualbox and vagrant but when i run vagrant up i'm getting an error.

$ vboxmanage --version
5.0.40r115130


$ vagrant --version
Vagrant 1.9.0


sandesh@DESKTOP-P6MBIE2 MINGW32 /c/homestead (master)
$ vagrant up
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Clearing any previously set forwarded ports...
==> homestead-7: Clearing any previously set network interfaces...
==> homestead-7: Preparing network interfaces based on configuration...
    homestead-7: Adapter 1: nat
    homestead-7: Adapter 2: hostonly
==> homestead-7: Forwarding ports...
    homestead-7: 80 (guest) => 8000 (host) (adapter 1)
    homestead-7: 443 (guest) => 44300 (host) (adapter 1)
    homestead-7: 3306 (guest) => 33060 (host) (adapter 1)
    homestead-7: 4040 (guest) => 4040 (host) (adapter 1)
    homestead-7: 5432 (guest) => 54320 (host) (adapter 1)
    homestead-7: 8025 (guest) => 8025 (host) (adapter 1)
    homestead-7: 27017 (guest) => 27017 (host) (adapter 1)
    homestead-7: 22 (guest) => 2222 (host) (adapter 1)
==> homestead-7: Running 'pre-boot' VM customizations...
==> homestead-7: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "7df473db-c437-4c7d-b8db-d3f57096bbd8", "--type", "headless"]

Stderr: VBoxManage.exe: error: Could not open the medium 'C:\Users\sandesh\VirtualBox VMs\homestead-7\box-disk1.vmdk'.
VBoxManage.exe: error: VMDK: inconsistency between grain table and backup grain table in 'C:\Users\sandesh\VirtualBox VMs\homestead-7\box-disk1.vmdk' (VERR_VD_VMDK_INVALID_HEADER).
VBoxManage.exe: error: VD: error VERR_VD_VMDK_INVALID_HEADER opening image file 'C:\Users\sandesh\VirtualBox VMs\homestead-7\box-disk1.vmdk' (VERR_VD_VMDK_INVALID_HEADER)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MediumWrap, interface IMedium

**Comment by Manuel-Aullo** [comment]
I'm having some issues over here as well:
Vagrant version 2.0.1
VBox version 5.1.30r
Hyper-V was disabled
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'scotch/box'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'scotch/box' is up to date...
==> default: Setting the name of the VM: etk_default_1510129685884_50959
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "3525a37b-9025-424a-ad59-e14e4845b8fb", "--type", "headless"]

Stderr: VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

**Comment by Manuel-Aullo** [comment]
No problem.
Just have to activate VT.x..... as can be readed in the log.
Thanks anyway!!!

**Comment by mrdinkelman** [comment]
Yet another solution which worked for me. If you're using 'suspend' and then install Windows Updates (usually Windows installed it in background wirhout asking you:)) - you just need to halt & up your machines.

**Comment by zach007** [comment]
i got the same  problem 
vagrant version : 1.9
virtualbox : 5.1

and then ,i try installed the lasted vagrant and virtualbox ，and problem seem to be fine ,but when i "vagrant ssh" and i got  the error : 
 tput: No value for $TERM and no -T specified
 tput: No value for $TERM and no -T specified
 tput: No value for $TERM and no -T specified

please help me fix it thanks a lot 

![5zey 1jml7zl_ 6b f5 76d](https://user-images.githubusercontent.com/7594289/33851589-66e58078-def2-11e7-9478-2deecf1c050a.png)

**Comment by tonitim13** [comment]
I opened the virtualbox and manually turn off the image. Then start the vagrant (vagrant up) and everything worked ok

**Comment by webpriest** [comment]
I did the following to resolve the issue (thanks to the advice of @frutality):

- Downloaded latest version of Virtual Box
- Uninstalled the current version of Virtual Box
- Restarted the PC
- Installed the download version of Virtual Box
- Downloaded and installed latest version of Vagrant (i was prompted to upgrade, because the new Virtual box was not compatible with my current version of Vagrant)
- vagrant up --provision
- VAGRANT_PREFER_SYSTEM_BIN=1 vagrant ssh (couldn't use the regular 'vagrant ssh' for some reason after running Windows Update)

Hope this helps Windows users

**Comment by angelburov** [comment]
I had the same problem after Windows 10 Creators update (1709).
Installing the latest version of VirtualBox and Vagrant solved the issue.
It's possible to need some plugin repair after that: `vagrant plugin repair`

**Comment by KingAnton** [comment]
Reinstall Virtual box with remove Virtual box files from:
C:\Users\myuser\VirtualBox VMs
C:\Users\myuser\AppData
This worked for me

**Comment by RemusSino** [comment]
I have disable Hyper V in Windows, enabled Virtualization in BIOS and updated Virtual Box. This worked for me.

**Comment by vjvaib** [comment]
I am getting error as below - I reinstalled vagrant as well as switched to virtual box version 5.1 which seems to be compatible , still below is the issue
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "697b4255-f4ef-448c-9a58-6e4aa683af2a", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'vagrant_default_1554800022343_23370' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\joshi\VirtualBox VMs\vagrant_default_1554800022343_23370\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

**Comment by chrisrana** [comment]
I facing same issue in ubuntu. Virtualization is set to full.
any suggestion.Do i need to change virtualization type to VT-X in this case ?

Error:
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "aea2fe3d-dec5-4de7-adb8-8515fbd3118a", "--type", "headless"]

Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
```


**Ubuntu Machine detail:**
```

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             8
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Model name:            Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz
Stepping:              2
CPU MHz:               3066.775
BogoMIPS:              6133.55
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0-7
```

**Comment by eborremans** [comment]
chrisrana, you may want to check [https://www.howtogeek.com/213795/how-to-enable-intel-vt-x-in-your-computers-bios-or-uefi-firmware/](https://www.howtogeek.com/213795/how-to-enable-intel-vt-x-in-your-computers-bios-or-uefi-firmware/)

in short, the proper virtualization settings are often disabled by default in the BIOS. have you checked your bios settings?

**Comment by ghost** [comment]
> ![image](https://cloud.githubusercontent.com/assets/448620/23822994/4ab0e0fa-0626-11e7-8505-1bca0206a45c.png)
> @mnpenner is right, Vagrant with VirtualBox cannot work with Docker at the same time.

but hyper-v manager vm's is working

**Comment by anabeto93** [comment]
Sometimes the problem is with the OS or vagrant box. I faced similar issues using ubuntu/xenial64 until I switched to centos/7 and all those problems disappeared.

**Comment by padraicbaker** [comment]
I ran into this problem as well. I didn't need to completely uninstall Virtualbox. I downloaded the latest Virtualbox installer for Windows, running it presents an option to repair the current installation. That worked for me.

**Comment by soulwa** [comment]
ran into this issue, ran `bcdedit /set hypervisorlaunchtype off` in my `cmd` shell as admin and rebooted, was able to run vagrant fine.
