### ISSUE TITLE
Update Curl to 7.41.1

### ISSUE THREAD

**Issue by andygambles** [scotch-io/scotch-box#197]
We need to update Curl to 7.41.1 but struggling to do this on the Scotchbox. Any pointers?

**Comment by maxpou** [comment]
Hi,
As far as I'm concerned, I think **you can't**.
Scotchbox run on Ubuntu 14.04 LTS a.k.a. **Trusty**.
Checkout https://curl.haxx.se/download.html : the latest version for CURL is 7.35 for Ubuntu Trusty.

You have to migrate scotchbox to Ubuntu 16.04 LTS (latest version is 7.47).

**Comment by whatnickcodes** [comment]
Fixed in new release. Look out for the update this week
