### ISSUE TITLE
MySQL connect on Laravel 5.2

### ISSUE THREAD

**Issue by marcelo2605** [scotch-io/scotch-box#198]
Can't run artisan migrate. This error appear:

>  [PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)

Here is a partial of my .env file:

```
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=scotchbox
DB_USERNAME=root
DB_PASSWORD=root
```

Running ` mysqladmin -u root -p status` on SSH return this:

> Uptime: 1308  Threads: 3  Questions: 131  Slow queries: 0  Opens: 48  Flush tables: 1  Open tables: 41  Queries per second avg: 0.100

If I change DB_PASSWORD to '', the system cannot find the table:

>  [PDOException]
  SQLSTATE[HY000] [1049] Unknown database 'scotchbox'

**Comment by ncerminara** [comment]
The user isn't `homestead`. It's `root`. 

SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)

Your configuration is incorrect when connecting to the DB.

**Comment by marcelo2605** [comment]
Sorry Nicholas, I post the wrong message. But the error continues.

**Comment by jordanboston** [comment]
Anyone get this figured out?

**Comment by marcelo2605** [comment]
Hi @jordanboston. I believe I was running migrate command in wrong local. As I'm using Vagrant, need to run migrate in VM (`vagrant ssh`).

**Comment by jordanboston** [comment]
Ok, thanks.  I ended up using Homestead which I don't use normally but works better with Laravel Spark for me.
