### ISSUE TITLE
Changing database name

### ISSUE THREAD

**Issue by chrisVdd** [scotch-io/scotch-box#200]
Hi everybody!

Is it possible to rename the database? For the moment, it's scotchbox
Thanks ;-)

**Comment by ncerminara** [comment]
You can just create a new one. The user "root" has access to do so.

If you're using Sequel Pro or Navicat, just click "Create New"

**Comment by chrisVdd** [comment]
Thank you for the very quick reply!
I had not thought of that, thank you it's done;-)
