### ISSUE TITLE
Access denied to MySQL using root/root

### ISSUE THREAD

**Issue by sanxac** [scotch-io/scotch-box#201]
Tried from Sequel Pro and vagrant ssh & got Access denied in both cases.  using root/root, fresh install of 2.0 on El Capitan

`vagrant@scotchbox:~$ mysql -u root -p
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
vagrant@scotchbox:~$`

**Comment by ncerminara** [comment]
Weird... If you're SSH'd into the box that should work and shouldn't matter what system you're on.

Also, there's a `.my.cnf` setup, so you should be able to just do this once SSH'd in:

```
mysql
```

**Comment by sanxac** [comment]
`vagrant@scotchbox:~$ mysql

ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`

also i have 2.5 not 2.0 and i got some messages about "The guest additions on this VM do not match the installed version"

In ~/.my.cnf: 

`[mysql]

user=root

password="root"`

Any other ideas?

**Comment by sanxac** [comment]
Figured it out - I was importing a sql dump file which had some user settings I wasn't aware of.  They were overriding root/root.
