### ISSUE TITLE
Downgrade PHP Version

### ISSUE THREAD

**Issue by michalovadia** [scotch-io/scotch-box#202]
I saw a thread regarding upgrading my PHP version to PHP 7.  
Is there a way to do the opposite?  I need to downgrade to version 5.4.27.

Thanks

**Comment by julestruong** [comment]
+1

**Comment by whatnickcodes** [comment]
Can you use the older boxes?

- http://drive.scotch.io/scotchbox/1.0.0/scotch.box
- http://drive.scotch.io/scotchbox/1.0.1/scotch.box
- http://drive.scotch.io/scotchbox/1.0.2/scotch.box
- http://drive.scotch.io/scotchbox/1.5.0/scotch.box
- http://drive.scotch.io/scotchbox/2.0.0/scotch.box
- http://drive.scotch.io/scotchbox/2.5.0/scotch.box
- http://drive.scotch.io/scotchbox/3.0.0/scotch.box

**Comment by Cromian** [comment]
@whatnickcodes sorry how do we go about using the older box?

**Comment by whatnickcodes** [comment]
Check the older docs to see what is what. I think the one you of them will definitely be 5.4.

You just add one of these to your Vagrantfile:

```
config.vm.box_version = 1.0.0
config.vm.box_version = 1.0.1
config.vm.box_version = 1.0.2
config.vm.box_version = 1.0.5
config.vm.box_version = 2.0.0
config.vm.box_version = 2.5.0
config.vm.box_version = 3.0.0
```

Or, you can specify a URL:

```
config.vm.box_url = https://drive.scotch.io/scotchbox/1.0.0/scotch.box
```

Etc.

**Comment by whatnickcodes** [comment]
Looks like 1.0.5 is probably the one you want

**Comment by Cromian** [comment]
Thanks! Looks like I was overcomplicating it. Keep up the great work!

**Comment by arzurchris** [comment]
1.0.5 doesn't exists, it's not :
`config.vm.box_version = "1.0.5" `
but :
`config.vm.box_version = "1.5.0"`

Available versions: 1.0.0, 1.0.1, 1.0.2, 1.5.0, 2.0, 2.5, 3.0

PHP version on box 1.5.0 is 5.5.23

**Comment by whatnickcodes** [comment]
These are all versions

**Comment by XedinUnknown** [comment]
Broken [link](http://drive.scotch.io/scotchbox).

**Comment by whatnickcodes** [comment]
Oh, sorry guys. I moved to HashiCorp's servers

* https://app.vagrantup.com/scotch/boxes/box/versions/3.0/providers/virtualbox.box
* https://app.vagrantup.com/scotch/boxes/box/versions/2.5/providers/virtualbox.box
* https://app.vagrantup.com/scotch/boxes/box/versions/2.0/providers/virtualbox.box
* https://app.vagrantup.com/scotch/boxes/box/versions/1.5.0/providers/virtualbox.box
* https://app.vagrantup.com/scotch/boxes/box/versions/1.0.2/providers/virtualbox.box
* https://app.vagrantup.com/scotch/boxes/box/versions/1.0.1/providers/virtualbox.box
* https://app.vagrantup.com/scotch/boxes/box/versions/1.0.0/providers/virtualbox.box

**Comment by malcomio** [comment]
This page seems to be the best source of the details of what's in each box:
https://app.vagrantup.com/scotch/boxes/box
