### ISSUE TITLE
Enhancement - Install and configure XDebug out of the box

### ISSUE THREAD

**Issue by spetz83** [scotch-io/scotch-box#203]
I would contend that XDebug is a must have tool for PHP Developers, regardless of Framework, CMS, or whatever is being worked on. It would be nice to have that up and running out of the box.

**Comment by ncerminara** [comment]
No immediate plans to install XDebug guys. Here's how (very easy)

- https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#installing-xdebug
- http://rocinantesoftware.blogspot.com.es/2015/07/phpstorm-xdebug-scotchbox-20.html
