### ISSUE TITLE
Missing phpunit

### ISSUE THREAD

**Issue by jackdpeterson** [scotch-io/scotch-box#206]
This should come as a default. Let's help promote development best practices by not requiring folks to install it!

**Comment by ncerminara** [comment]
True.

**Comment by JustAWebDev** [comment]
Is this something you want to add to the Vagrant file for provisioning, or do you want to build it into the VM?  I ask because I'm going to be forking the project probably and adding it to the Vagrant file.  Just checking if I should submit a pull request.

**Comment by daniel-rees** [comment]
+1

**Comment by rfair404** [comment]
+1 - just figured out that the box doesn't have this by default, which surprised me.

**Comment by ajay-qburst** [comment]
+1

**Comment by whatnickcodes** [comment]
Woof - okay added this to the new release coming this week

**Comment by mattkoch614** [comment]
Is PHPUnit only available in the pro version?

**Comment by mattkoch614** [comment]
Bump for good measure...

**Comment by jackdpeterson** [comment]
At this point, I'm rescinding my original opinion that this should be included by default ... Recent versions of PHPUnit have some differences in certain interface versus what you project may have. This can result in weird inclusion errors. Perhaps the best practice, after all, is to instead include it directly in your project and then execute php vendor/bin/phpunit relative to your project's root folder.
