### ISSUE TITLE
Add all locales for multi-language web applications

### ISSUE THREAD

**Issue by mraerino** [scotch-io/scotch-box#208]
## Problem

When using php-gettext the only way to set the language for the gettext translations is via `setlocale` in php.
In order for `setlocale` to work, that locale has to be installed in the system.
## Proposal

Could you please consider to install all ubuntu language packs into your box?
## How-To

Because there is no `locales-all` package in ubuntu, a script like this is needed:
https://gist.github.com/specialunderwear/1218856

**Comment by mraerino** [comment]
I'm using the following shell provisioner as a workaround:
```sh
cd /var/lib/locales/supported.d
ln -s /usr/share/i18n/SUPPORTED all
locale-gen
```

**Comment by whatnickcodes** [comment]
How much larger does this make the box?

I'm trying to keep it slim. So this worries me a bit. Maybe I can just add it to the docs?
