### ISSUE TITLE
Using ruby gem in provisioning script (shell)

### ISSUE THREAD

**Issue by dnaber-de** [scotch-io/scotch-box#209]
Hi everyone,

I'm trying to set up a VM using scotch-box as base and want to install Jekyll. I can easily connect via SSH to the VM and run `$ gem install jekyll`, that works very well. Now I want to automate this process in the provisioning process, so I created a shell script like so:

```
#!/usr/bin/env bash
gem install jekyll
```

But this leads to the following errors:

```
==> default: stdin: is not a tty
==> default: bash: gem: command not found
```

So I updated the provisioning script to make sure it's actually used as the user `vagrant`:

```
#!/usr/bin/env bash
sudo -H -u vagrant bash -c "gem install jekyll"
```

This doesn't solve the problem.

Here is my Vagrantfile:

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "scotch/box"
  # Jekyll port 4000
  config.vm.network "forwarded_port", guest: 4000, host: 4000
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "my-host"
  config.vm.synced_folder "/var/www", "/var/www"
  config.vm.provision "shell", path: "provisioners/apps/jekyll/jekyll.sh"
end
```

Any idea how I can solve the problem?

**Comment by veganista** [comment]
Same problem here, except i'm using an inline provision script.

**Comment by veganista** [comment]
Not really sure what happens after provisioning to make `gem` work but if you do `which gem` it gives this path `/home/vagrant/.rbenv/shims/gem`.

I've used `/home/vagrant/.rbenv/shims/gem install my-gem` and it appears to have installed my gem properly.

Possibly something to do with:

> It turns out that rbenv installs shims for all binaries, which auto-switch to the appropriate ruby version before invoking the real binary. 

From [here](https://coderwall.com/p/zvyyta/rbenv-binary-name-command-not-found)
