### ISSUE TITLE
PHP 7 install instructions 

### ISSUE THREAD

**Issue by whatnickcodes** [scotch-io/scotch-box#210]
```
sudo apt-get update
sudo add-apt-repository ppa:ondrej/php
sudo apt-get install php7.0
sudo apt-get update
sudo apt-get install php7.0-mysql libapache2-mod-php7.0
sudo a2dismod php5
sudo a2enmod php7.0
sudo apachectl restart
```

https://github.com/scotch-io/scotch-box/issues/157#issuecomment-216422285

Need to add to Docs

**Comment by ckahle33** [comment]
I could do it. Where would you want it in the readme?

**Comment by whatnickcodes** [comment]
You pick

**Comment by whatnickcodes** [comment]
Thanks. Leaving this open so I remember to update the website too

**Comment by ckahle33** [comment]
Glad to help! Thanks for creating this awesome box. Is the website public? If so I could also knock that out too.

**Comment by whatnickcodes** [comment]
No but it should be...

On Thu, May 5, 2016 at 2:28 PM, Craig <notifications@github.com> wrote:

> Glad to help! Thanks for creating this awesome box. Is the website public?
> If so I could also knock that out too.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scotch-io/scotch-box/issues/210#issuecomment-217234737>
>



-- 
Nicholas V. Cerminara
T: 702.485.0853
E: nick@scotch.io

**Comment by vodou** [comment]
I had to add a `sudo apt-get update` after the `sudo add-apt-repository ppa:ondrej/php` line to make it work on my freshly-installed Scotch box, FYI.

**Comment by maxpou** [comment]
Hi,

if you want, here's my full install guide for PHP7 in scotchbox

# Install PHP7 (will remove php5)

1. Update package list

    ```sh
    sudo apt-get install python-software-properties
    sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
    ```

2. Install PHP7 and remove PHP5

    ```sh
    sudo apt-get update
    sudo apt-get purge php5-common -y
    sudo apt-get install -y \
        && php7.0 \
        && php7.0-fpm \
        && php7.0-mysql \
        && php-curl \
        && libapache2-mod-php7.0 \
        && php7.0-mbstring
    sudo apt-get --purge autoremove -y
    ```

3. Set timezone (i.e. date.timezone = Europe/Paris)

    ```sh
    sudo vi /etc/php/7.0/cli/php.ini
    sudo vi /etc/php/7.0/apache2/php.ini
    ```

4. Restart apache service

    ```sh
    sudo a2enmod php7.0
    sudo service apache2 restart
    ```

**Comment by mcordingley** [comment]
If you're doing this in a provision script, step three becomes:

    sudo sed -i "s/date.timezone = foo /date.timezone = Europe\/Paris/g"

Just make that first `date.timezone = foo` match whatever is in the files by default and that second `date.timezone = Europe\/Paris` match your desired timezone. Note the use of `\` as an escape character, too.

**Comment by whatnickcodes** [comment]
# FIXED

PHP 7 is now in the box by default. Upgrade the box!
