### ISSUE TITLE
Docker and Packer

### ISSUE THREAD

**Issue by thomas-miele** [scotch-io/scotch-box#211]
It would be a good thing to make an official docker image of scotch-box with a Docker Hub repository.

A sub directory with :
- a Vagrantfile who replace atlas box by Docker Hub image
- a Dockerfile for build image itself
- maybe a docker-compose.yml file for orchestration

Publish Packer instruction on this repository can also be a good thing that can help for contribution of this feature.

**Comment by whatnickcodes** [comment]
Soon... 3.0 this is most likely going to happen

**Comment by ted-piotrowski** [comment]
I'm attempting to migrate scotch/box configuration onto Docker. Does an equivalent Docker image exist somewhere? If not, is there a place I can find the Vagrantfile configuration used to build the Hashicorp scotch/box .box so I can use it as a guide to creating an equivalent Dockerfile? Thank you.

**Comment by whatnickcodes** [comment]
I have shell scripts for the new Scotch Box that we're releasing this week. Should make creating a docker image easier

**Comment by thomas-miele** [comment]
And we must pay license for have custom builds ! WTF ! So box 3.0 is irrevelant !

**Comment by whatnickcodes** [comment]
It's only $15 to support the project. Not trying to make a killing on this...

If you spend 5 minutes trying, you can probably find the build scripts without paying
