### ISSUE TITLE
PHPloy tool and php.ini [always_populate_raw_post_data]

### ISSUE THREAD

**Issue by paulocamboim** [scotch-io/scotch-box#214]
Hi, 

I'm just sending a shell script that changes a configuration line on PHP.ini and also install PHPploy.
I hope that can help someone.

When running PHP scripts I noticed a warning about "always_populate_raw_post_data" as shows below. I just use a SED command to change the php.ini

_Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will
be removed in a future version. To avoid this warning set
'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream
instead. in Unknown on line 0_

One tool that I included on my box is the PHPloy tool that can send git repository to a FTP.

```
#!/usr/bin/env bash
# Install PHPloy - Deploy repository to FTP
sudo wget https://github.com/banago/PHPloy/raw/master/bin/phploy.phar -O /usr/local/bin/phploy
sudo chmod +x /usr/local/bin/phploy

# SET PHP always_populate_raw_post_data To -1 to avoid a warning
sed -i 's/.*always_populate_raw_post_data.*/always_populate_raw_post_data = -1/' /etc/php5/apache2/php.ini 
```

**Comment by dstollie** [comment]
This line should be added by default in the scotch box. Posts request in Laravel now always fail

```bash
# SET PHP always_populate_raw_post_data To -1 to avoid a warning
sed -i 's/.*always_populate_raw_post_data.*/always_populate_raw_post_data = -1/' /etc/php5/apache2/php.ini 
```
