### ISSUE TITLE
ubuntu user password?

### ISSUE THREAD

**Issue by IgorNadj** [scotch-io/scotch-box#215]
Hi, I am using scotch-box 2.5 and it comes with an ubuntu user.

Typically I don't need this user as the user vagrant can sudo and this gives me everything I need. However after installing ubuntu-desktop, it keeps asking me to login as the ubuntu user (e.g. for installing chrome through the package manager). 

What is the password for the ubuntu user?

Thanks!

**Comment by paulocamboim** [comment]
You can try to change the ubuntu user password using the root.
`sudo passwd ubuntu`

**Comment by IgorNadj** [comment]
Great that works thanks!

(sudo passwd ubuntu is different from sudo -u ubuntu -i, passwd because it does not ask for the old password)
