### ISSUE TITLE
How to set the file in the folder "public" to be excutable? 

### ISSUE THREAD

**Issue by fangd123** [scotch-io/scotch-box#216]
My OS is Win10, and I prepared to use the  test framework "codeception", after importing the files by composer, I found that the file "codecept" could not be excutable, although I tried to use the command "chmod", it still was no use.

So what should I do to let my files excutable?

**Comment by paulocamboim** [comment]
Fang,

In your Vangrantfile edit this line:

> config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

To

> config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=777"]

In this way all your files will have permissions set to 777
