### ISSUE TITLE
PDO Driver issue on PHP?

### ISSUE THREAD

**Issue by RobQuistNL** [scotch-io/scotch-box#217]
I can't seem to get Laravel to work. Somehow the artisan migrate function did work and didn't return errors. But when I run this code;

``` php
<?php
error_reporting(-1);
ini_set('display_errors', 1);
$db = new PDO('mysql:host=localhost;dbname=scotchbox;charset=utf8mb4', 'root', 'root');
var_dump($db);
phpinfo();
die;
```

I get the following error:

```
Fatal error: Uncaught exception 'PDOException' with message 'could not find driver'
```

The PDO modules and drivers do seem to be included by default..

**Comment by Blessings9** [comment]
running into something similar......was a solution ever found?

**Comment by RyanHipkiss** [comment]
Anyone get a solution?

**Comment by RobQuistNL** [comment]
I believe I went with PuPHPet but thats not the answer you'd like ;P

**Comment by RyanHipkiss** [comment]
@RobQuistNL Just took a quick look, that looks to be a good project - I may need to get round to setting up a box at some point. Cheers.

**Comment by whatnickcodes** [comment]
Weird. New update coming this week which should address
