### ISSUE TITLE
vagrant-cachier plugin support

### ISSUE THREAD

**Issue by giankdm** [scotch-io/scotch-box#218]
We can add support for the plugin vagrant-cachier very easily. It speeds up provisioning of the VM.

- In README.md suggest 

`vagrant plugin install vagrant-cachier`

- in Vagrantfile consider adding lines as per "Quickstart" in 

[vagrant-cachier](https://github.com/fgrehm/vagrant-cachier)

- in Vagrantfile consider adding

`config.vm.provision "shell", path: "provisioner.sh"`

- in project directory consider adding a file called

provisioner.sh

with this content

`# provisioner.sh is a script that will be executed at the end of the installation and is provided empty. Enjoy!`
In README.md suggest 

provisioner.sh is a script that will be executed at the end of the installation and is provided empty. Enjoy!

**Comment by whatnickcodes** [comment]
Cachier is amazing, but no plugins unfortunately. Scotch Box is supposed to be dead simple / dependency free / most likely to never to break
