### ISSUE TITLE
vagrant-hostmanager

### ISSUE THREAD

**Issue by giankdm** [scotch-io/scotch-box#220]
Consider adding in README.md

`vagrant plugin install vagrant-hostmanager`

Consider adding in Vagrantfile

`config.hostmanager.enabled = true`
`config.hostmanager.manage_host = true`
`config.hostmanager.manage_guest = true`
`config.hostmanager.ignore_private_ip = false`
`config.hostmanager.include_offline = true`

**Comment by whatnickcodes** [comment]
Hey hey. Purpose of Scotch Box is to be dead simple and dependency free. Unfortunately that means no plugins
