### ISSUE TITLE
Warning: Remote connection disconnect. Retrying...

### ISSUE THREAD

**Issue by ethanbeyer** [scotch-io/scotch-box#221]
I've been using Scotchbox for a couple weeks now and I have had no problems up to this point. A couple of days ago I added my Vagrantfile to a repo and a colleague cloned the repo, and ran `vagrant up`. As the box was booting, he received this error several times:

```
default: Warning: Remote connection disconnect. Retrying...
```

Until then, I had never seen that error while booting a machine, so I wasn't quite sure what it was. The best two resources on this problem are [StackOverflow](http://stackoverflow.com/questions/22575261/vagrant-stuck-connection-timeout-retrying) and [a blog post](http://www.thisprogrammingthing.com/2016/fixing-vagrant-connection-error/).

It seemed that there were some SSH issues, but also on my colleague's computer, I needed to run the box with a GUI so I could tell it to complete the boot sequence. I found that odd.

Then in the past two days I've been getting the error too, on boxes that have never had trouble before. Is there an issue with having multiple instances of Scotch-box installed?

Here's how my current boot sequence looks for one of the boxes in question:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'scotch/box' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
    default: Adapter 3: bridged
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: password
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.28
    default: VirtualBox Version: 5.0
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/Ethan/Sites/3sm.dev
    default: /var/www/public => /Users/Ethan/Sites/3sm.dev
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
```

**Comment by ethanbeyer** [comment]
Update: This appears to be an issue with Virtualbox 5.0.20.

After downgrading to 5.0.18, my boxes boot perfectly fine. I will update this space as I know more.

ref: https://github.com/mitchellh/vagrant/issues/7306

**Comment by baptistelinel** [comment]
Sometime, when I don't properly shutdown my VM I also have this issue. I wait and then, few seconds later it works fine. I have multiple instances of Scotch-box installed but I don't think it has an impact with our connection issue.

**Comment by ethanbeyer** [comment]
I can confirm that shutting down my computer without halting vagrant causes issues, but it appears the the consistent disconnectivity loop was caused by the most recent VirtualBox update.

**Comment by Netw0rkeu** [comment]
Same issue here. Using Virtual Box 5.0.16

**Comment by stormherz** [comment]
Same here, Virtual Box 5.1.8 on MacOS Sierra

**Comment by Braunson** [comment]
Any updates on this?

**Comment by Dynatrace-Adam-Gardner** [comment]
Bug verified on Version 5.1.8 r111374 (Qt5.5.1) Win10

**Comment by omfgtora** [comment]
Having this issue on Version 5.1.20, Linuxmint 18.1

**Comment by erick-jeronimo** [comment]
Hey guys! This issue is related to different versions of GuestAdditions between guest and host... check these links for more info:

https://github.com/dotless-de/vagrant-vbguest
https://github.com/dotless-de/vagrant-vbguest/issues/224

Hope this helps!
