### ISSUE TITLE
Permission denied trying to access apache error logs

### ISSUE THREAD

**Issue by viveleroi** [scotch-io/scotch-box#222]
Looking in `/var/logs` I see the `apache2` directory but it's locked to a user group the `vagrant` user doesn't have access to.

**Comment by paulocamboim** [comment]
Mike,
If you execute: 
`$ ls -l /var/log | grep apache2` it will return: 

>  drwxr-x---  2 root      adm       4.0K Jul 10  2015 apache2

You can see that only the **root** have full access to this folder (rwx) and the group **adm** can (rx). And others users can't do nothing. If you are not root or do not belongs to adm group you can't do nothing. To check which groups you belongs run this command on the bash: 
`$ groups`

The solution for you access the folder and files it's becoming root using sudo:
`$ sudo su`
`$ cd /var/log/apache2`
`$ vim access.log`

Hope this helps!

**Comment by viveleroi** [comment]
Thanks, I knew the permissions were excluding the vagrant user but I didn't realize I could `sudo su` for root since this box was preconfigured.
