### ISSUE TITLE
Drush installation not working

### ISSUE THREAD

**Issue by erinclerico** [scotch-io/scotch-box#223]
This does not appear to be a Scotchbox issue - I think it has something to do with the current release of Composer - so please forgive this post here I just hope to get some help to get Drush operational:

Here is the command I am using to install Drush:
`composer global require drush/drush:dev-master`

And here is the error I get:
`- Installation request for drush/drush dev-master -> satisfiable by drush/drush[dev-master].
    - drush/drush dev-master requires codegyre/robo ~1.0.0-beta1 -> satisfiable by codegyre/robo[1.0.0-beta1] but these conflict with your requirements or minimum-stability.`

I see a few other folks are having the this trouble but I can't get any of the solutions to work - any ideas?

Thank you.

**Comment by erinclerico** [comment]
Whoops - I was using `composer global require drush/drush:dev-master` - once I got off that and used  plain old `composer global require drush/drush` it worked perfectly. Sorry for the noise.

**Comment by trishul** [comment]
Thanks it saved my time :+1:
