### ISSUE TITLE
Why doesn't the up and down arrows move through the history?

### ISSUE THREAD

**Issue by ericol** [scotch-io/scotch-box#224]
As per the title. I thought that was the default in Linux / Ubuntu.

**Comment by ethanbeyer** [comment]
This might help: http://unix.stackexchange.com/a/85397

**Comment by ericol** [comment]
@ethanbeyer I just created it, so I think I do, yes.
BTW, the solution in there does not wor k - as in, everything is set up correctly in the box re: history - but oddly it seems to be a problem with the way I'm accessing the box. I use Console 2 on Windows, and, althought everything works correctly in the other vagrant boxes I have, it doesn't in this one.

But I solved it by logging into the box using putty.

Thanks for your help!

**Comment by ethanbeyer** [comment]
No problem! Glad you got it figured out.
