### ISSUE TITLE
Vagrant SSH Connection refused

### ISSUE THREAD

**Issue by jasperf** [scotch-io/scotch-box#225]
When I do a `vagrant ssh` the connection is refused. When I do a `ssh vagrant@192.168.33.10` and enter the password vagrant I am in again. Any ideas why the standard vagrant ssh does not work?

**Comment by maxpou** [comment]
Hi,
Please, provide more informations like host OS, Vagrant version and installed plugins, provider (e.g. VirtualBox, VMware, AWS...) ...
Does it works on other boxes?

We're not in your brain ;-)
(I think that it's not especially related to scotchbox.)

**Comment by whatnickcodes** [comment]
Try adding this too to the Vagrantfile if you recently upgraded boxes:

```
config.ssh.username = "vagrant"
config.ssh.password = "vagrant"
```
