### ISSUE TITLE
Using Composer

### ISSUE THREAD

**Issue by moshemo** [scotch-io/scotch-box#227]
Perhaps I'm missing something, but Composer doesn't seem to be loaded.  

I just cloned scotch box and ran vagrant up.  Everything seems to work just fine -- if I go to 192.168.33.10 I see the Scotch Box index.php page. 

However, composer doesn't seem to work.  If I type 'composer' in the command line then I get the following message:

> 'composer' is not recognized as an internal or external command,
> operable program or batch file.

Is there something else I'm supposed to do? 

In short, how can I get composer to work?

Btw, I'm using cmder on Windows 10, for what's it's worth.

Thanks.

**Comment by maxpou** [comment]
As far as I'm concerned, Composer natively work on my scotchbox (I'm using Windows 10 & **Cmder**).

Try to reinstall it.

**Comment by moshemo** [comment]
That was the problem -- I had not typed vagrant ssh.

Thanks for the help.
