### ISSUE TITLE
Unable to forward MongoDB port

### ISSUE THREAD

**Issue by cbovis** [scotch-io/scotch-box#230]
By default you're unable to forward the MongoDB port 27017 from the guest machine to the host. You have to manually edit the mongo configuration as detailed in http://randomgeekery.org/post/2014/mongo-vagrant-connect/ to allow remote connections.

Would it be possible to enable this by default so that we can use tools like Robomongo from the host machine without having to manually reconfigure the vagrant machine after provisioning?

**Comment by maxpou** [comment]
You're **not** *"Unable to forward MongoDB port"* because you did it. And, as you mentioned, it's pretty easy to adapt the vagrant file according to your external tools.

As far as I'm concerned, I don't think it's a good idea. Scotch box must stay a clean box. 
Read #205

**Comment by whatnickcodes** [comment]
Boom! Thanks
