### ISSUE TITLE
Vagrant up problem on windows 10

### ISSUE THREAD

**Issue by tusar-nill** [scotch-io/scotch-box#231]
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'laravel/homestead'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'laravel/homestead' is up to date...
==> default: Setting the name of the VM: homestead-7
==> default: Clearing any previously set network interfaces...
There was an error while executing VBoxManage, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "3edf52a7-f514-4d17-a014-d07afa80047f", "--nic2", "none", "--nic3", "none", "--nic4", "none", "--nic5", "none", "--nic6", "none", "--nic7", "none", "--nic8", "none", "--nic9", "none", "--nic10", "none", "--nic11", "none", "--nic12", "none", "--nic13", "none", "--nic14", "none", "--nic15", "none", "--nic16", "none", "--nic17", "none", "--nic18", "none", "--nic19", "none", "--nic20", "none", "--nic21", "none", "--nic22", "none", "--nic23", "none", "--nic24", "none", "--nic25", "none", "--nic26", "none", "--nic27", "none", "--nic28", "none", "--nic29", "none", "--nic30", "none", "--nic31", "none", "--nic32", "none", "--nic33", "none", "--nic34", "none", "--nic35", "none", "--nic36", "none"]

Stderr: VBoxManage.exe: error: Invalid NIC number 9
VBoxManage.exe: error: Invalid NIC number 10
VBoxManage.exe: error: Invalid NIC number 11
VBoxManage.exe: error: Invalid NIC number 12
VBoxManage.exe: error: Invalid NIC number 13
VBoxManage.exe: error: Invalid NIC number 14
VBoxManage.exe: error: Invalid NIC number 15
VBoxManage.exe: error: Invalid NIC number 16
VBoxManage.exe: error: Invalid NIC number 17
VBoxManage.exe: error: Invalid NIC number 18
VBoxManage.exe: error: Invalid NIC number 19
VBoxManage.exe: error: Invalid NIC number 20
VBoxManage.exe: error: Invalid NIC number 21
VBoxManage.exe: error: Invalid NIC number 22
VBoxManage.exe: error: Invalid NIC number 23
VBoxManage.exe: error: Invalid NIC number 24
VBoxManage.exe: error: Invalid NIC number 25
VBoxManage.exe: error: Invalid NIC number 26
VBoxManage.exe: error: Invalid NIC number 27
VBoxManage.exe: error: Invalid NIC number 28
VBoxManage.exe: error: Invalid NIC number 29
VBoxManage.exe: error: Invalid NIC number 30
VBoxManage.exe: error: Invalid NIC number 31
VBoxManage.exe: error: Invalid NIC number 32
VBoxManage.exe: error: Invalid NIC number 33
VBoxManage.exe: error: Invalid NIC number 34
VBoxManage.exe: error: Invalid NIC number 35
VBoxManage.exe: error: Invalid NIC number 36

How to fix vagrant up problem?
I'm using
*windows 10 64bit
*virtualbox 5.0.21.7994-win
*vagrant 1.8.3
Please, I need help. I'm a newbie.

**Comment by jco137** [comment]
To solve this problem you must edit the following file :+1: 

C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.3\plugins\providers\virtualbox\driver\base.rb

you must change the value of the max_network_adapters from 36 to 8
