### ISSUE TITLE
WordPress setup script for Scotch Box

### ISSUE THREAD

**Issue by flurinduerst** [scotch-io/scotch-box#232]
I love Scotch Box and I work with WordPress. To save time when creating a new project i wrote this Scotch Box WordPress setup. Thought this could be useful for people using Scotch Box + WordPress as well so I made it public :) Feel free to add a link to it if you want to.

https://github.com/flurinduerst/ScWPSetup

After adding your preferred theme, plugins and environment variables into config.yml you simply execute setup.sh and it will
- download/install/configure WordPress
- install/activate your favorite WP Theme (default WPSeed).
- install/activate the Plugins you defined in the config
- define WordPress options
- clean WordPress defaults (contents, plugins, themes, readme, license)

You can then re-use your config.yml for every other project and save a lot of time clicking, dragging, editing and configurating.

Not sure if the issues tab is right way to inform you about this, sorry if not!

Got feedback? Feel free to send me a massage :)

**Comment by whatnickcodes** [comment]
This is cool. Tweeting it from the Scotch account now.

Can you email me nick@scotch.io?
