### ISSUE TITLE
Mapping domain name to a folder

### ISSUE THREAD

**Issue by gradosevic** [scotch-io/scotch-box#234]
Hi,

I was previously using Laravel Homestead, and I like the feature to map domain name to a particular folder in Homestead configuration file. Is there a way to do such mapping in Scotch Box? I would like to use domain names that I create in my local DNS hosts file instead of subfolders. Thanks!

**Comment by Guerrerohgp** [comment]
If what you want is to have a domain for a specific folder you can add this to your vagrant file:
`
	config.vm.provision "shell", inline: <<-SHELL

        ## Only thing you probably really care about is right here
        DOMAINS=("domaina.dev" "domainb.dev" "domainc.dev")

        ## Loop through all sites
        for ((i=0; i < ${#DOMAINS[@]}; i++)); do

            ## Current Domain
            DOMAIN=${DOMAINS[$i]}

            echo "Creating directory for $DOMAIN..."
            mkdir -p /var/www/$DOMAIN/public

            echo "Creating vhost config for $DOMAIN..."
            sudo cp /etc/apache2/sites-available/scotchbox.local.conf /etc/apache2/sites-available/$DOMAIN.conf

            echo "Updating vhost config for $DOMAIN..."
            sudo sed -i s,scotchbox.local,$DOMAIN,g /etc/apache2/sites-available/$DOMAIN.conf
            sudo sed -i s,/var/www/public,/var/www/$DOMAIN/public,g /etc/apache2/sites-available/$DOMAIN.conf

            echo "Enabling $DOMAIN. Will probably tell you to restart Apache..."
            sudo a2ensite $DOMAIN.conf

            echo "So let's restart apache..."
            sudo service apache2 restart

        done

    SHELL` 

And vagrant reload --provision
the domains added in the array will create the folders and all, you need to add those to your host file and that's it. 

But if what you want is to map a folder to include that folder no matter where the folder is, then right now you will need to open virtualbox or vmware, and configure a shared folder.

**Comment by FlashPapa** [comment]
Hi,
It can also be done manually

## On your vagrant machine
on command line to duplicate **scotchbox.local.conf**
`sudo cp /etc/apache2/sites-available/scotchbox.local.conf /etc/apache2/sites-available/test.local.conf`

Edit this file **test.local.conf**
`sudo nano /etc/apache2/sites-available/test.local.conf`

put this line : 
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ServerName test.local
        ServerAlias www.test.local
        DocumentRoot /var/www/public/Nexus
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

Active the vhost : 
`sudo a2ensite /etc/apache2/sites-available/test.local.conf`

Restart apache : 
`sudo service apache2 reload`

## On your local machine
Now on your local machine manage your hosts  (macosX) :
`sudo nano /private/etc/hosts `

Add this line (with ip access of your vagrant machine): 
```
192.168.33.10 test.local
192.168.33.10 www.test.local
```

Now test in the browser : **http://www.test.local** or **http://test.local**

Enjoy !
