### ISSUE TITLE
Gmail SMTP error

### ISSUE THREAD

**Issue by lopezchairez** [scotch-io/scotch-box#235]
I can't connect to **gmail** using **TLS**

**Zend 1.x error:** 
Unable to connect via

**PHPMailer error:** 
PHP Warning:  stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /var/www/mailer/vendor/phpmailer/phpmailer/class.smtp.php on line 355

**[UPDATE]**
I changed from TLS to SSL and got a SMTP connect() failed error so I think I'm getting close. Also I can connect to gmail using telnet.

This is my setup

```
$mail->isSMTP();
$mail->Host = 'smtp.gmail.com';
$mail->Username = 'user@example.com';
$mail->Password = 'secret';
$mail->SMTPSecure = 'ssl';
$mail->Port = 465;
```

**Comment by whatnickcodes** [comment]
Your exact same code works on another environment that's not Scotchbox?
