### ISSUE TITLE
 Recurring issue with chmod when ssh'd

### ISSUE THREAD

**Issue by dxvargas** [scotch-io/scotch-box#236]
I have this issue https://github.com/scotch-io/scotch-box/issues/61 in v2.5
$ chmod +x filename.sh
  ... is ignored.

This is completely blocking, because I can't run phing etc...

I already tried these:

`config.vm.synced_folder ".", "/var/www", mount_options: ['dmode=777','fmode=666']`
`config.vm.synced_folder ".", "/var/www", owner: "vagrant", group: "_www", :mount_options => ["dmode=777", "fmode=774"]`
`config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]`

**Comment by dxvargas** [comment]
Just moved the local.dev folder outside of /vagrant/public/ , like this I can manage permissions without problems. Should I close the issue? I still think this is a problem that should be addressed.

**Comment by XedinUnknown** [comment]
Not having the docroot being synced would completely destroy the workflow for me and thousands of other users. Not being able to execute scripts in that dir is completely blocking, because I can't run the app's install script.

**Comment by veganista** [comment]
Have you tried the NFS option?

    config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

That has worked for me, on Windows and OSX. Seems to fix a few permissions problems, not 100% sure of the side effects though

**Comment by dxvargas** [comment]
Thanks @veganista , I tried that and it didn't solve the problem.
I guess I should first follow the instructions here: https://www.vagrantup.com/docs/synced-folders/nfs.html
But, sorry, I am not really comfortable with all the needed nfs configurations.
