### ISSUE TITLE
Help installing Z-Ray

### ISSUE THREAD

**Issue by a-h-abid** [scotch-io/scotch-box#238]
Hi, I've been trying to install Z-Ray on your vagrant box but have been unsuccessful. I followed the guide given at [Zend Site (Manual Apache)](http://files.zend.com/help/Z-Ray/content/installing_z-ray_on_linux.htm) but it didn't worked properly. When I run `php -v` in cli, it shows that is was installed successfully, but when I run in the browser at `192.168.33.10` It doesn't show the bar.

Can you help me out where I'm missing things here? Let me know if more info needed from me...

**Comment by whatnickcodes** [comment]
Sounds like you need to install and restart apache? Sorry I'm unfamiliar
