### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by saurabhgayali** [scotch-io/scotch-box#239]
whenever i try to start vagrant file it sayd 403 error. following is screenshot.
I am running WIndows 7, Virtualbox 5.0 and Github 3.0.17.0 and vagrant installed on system. please help.
![temp](https://cloud.githubusercontent.com/assets/13806535/16486763/6d94bc40-3ee4-11e6-8a51-615355d89302.png)

**Comment by maxpou** [comment]
Hi,
Try to download Scotchbox directly here: https://drive.scotch.io/scotchbox/2.5.0/
Then, use `vagrant box add` command.

**Comment by saurabhgayali** [comment]
Thank you.
This should work for now.
But, why the URL hasnt been modified. I am planning to package this with softwares which can be ontained online. I thought I would simply write codes in vagrant files to do that, but now this .box link will cost me few more pages of documentation.
Is it possible to integrate htis url within vagrantfile
