### ISSUE TITLE
Generate my.cnf to allow access to mysql from command line without providing username and password every time

### ISSUE THREAD

**Issue by bobojo** [scotch-io/scotch-box#24]
Since Scotch Box is all about ease of use, setting up some sort of my.cnf file with the root username and password predefined would allow users to log into the command line mysql by just typing `mysql` without `-u` or `-p`. I can add the file manually, but including it as part of the box would be even better!

**Comment by ncerminara** [comment]
Great tip, this is finally added! Run: `vagrant box update`
