### ISSUE TITLE
running gulp 

### ISSUE THREAD

**Issue by DawoudIO** [scotch-io/scotch-box#240]
per items listed at https://box.scotch.io/ gulp is pre-installed but when i run 

`gulp`

i get the following error (note i'm on windows 10)

```
vagrant@scotchbox:/vagrant$ gulp
[03:12:45] Local gulp not found in /vagrant
[03:12:45] Try running: npm install gulp
```

**Comment by flurinduerst** [comment]
This is the error when executing gulp without a `gulpfile.js` in the current folder. Gulp is installed at /usr/lib/node_modules/gulp. Try running gulp inside the folder containing your `gulpfile.js`.

**Comment by johnpitchko** [comment]
I am receiving this same error as well when I run gulp in my `/public` folder containing gulpfile.js:

```
vagrant@scotchbox:/var/www/public$ ls
css  gulpfile.js  img  index.html  index.html.original  js  less  LICENSE  mail  package.json  README.md  scss   vendor
vagrant@scotchbox:/var/www/public$ gulp
[05:09:30] Local gulp not found in /var/www/public
[05:09:30] Try running: npm install gulp
vagrant@scotchbox:/var/www/public$
```

**Comment by flurinduerst** [comment]
Now I see your problem. As I said gulp is installed at `usr/lib/node_modules/gulp`. But when executing `$ gulp` you're trying to make use of [gulp’s cli](https://www.npmjs.com/package/gulp-cli) which is not installed. try running `npm install --global gulp-cli` on the VM and try again.

**Comment by DawoudIO** [comment]
npm install needs to be done as `sudo pm install --global gulp-cli` but even with that, it is still not working

```
vagrant@scotchbox:~$ cd /vagrant/
vagrant@scotchbox:/vagrant$ vi gulpfile.js
vagrant@scotchbox:/vagrant$ gulp hello
[14:22:56] Local gulp not found in /vagrant
[14:22:56] Try running: npm install gulp

```

**Comment by flurinduerst** [comment]
Forgot about the `sudo`, sure. After installing gulp-cli like that it worked fine on my environment.  I guess your gulpfile is located inside the `public` folder? In this case try running the gulp command at `vagrant@ scotchbox:/var/www/public$`

**Comment by DawoudIO** [comment]
without sudo the command errors out... the command will not work as my gulpfile.js is not in my public dir but in the root of my project which is in the /vagrant dir.
