### ISSUE TITLE
Default scotch box page is displayed when accessing the server at http://192.168.33.10/ instead of php site

### ISSUE THREAD

**Issue by Javi-er** [scotch-io/scotch-box#241]
In /var/www I have all the files of my site, I also setup a virtual host in Apache for this site and added an entry in my computer hosts file but nothing have helped, when I access the domain at x.local or the ip address at 192.168.33.10 sometimes I get my site and most of the times I get the default scotch box start website.

Does anyone know what the problem is?

**Comment by flurinduerst** [comment]
the correct folder structure is 'var/www/public/index.php', 

If this doesn't help: can you show your vagrantfile, folder/file structure,

**Comment by Javi-er** [comment]
I have the project in my local at /User/name/project
"project" folder contains both my project files (including index.php) and the vagrant file too, you say that I should move my project files to /User/name/project/public instead before doing vagrant up ?

**Comment by flurinduerst** [comment]
> you say that I should move my project files to /User/name/project/public ?

yes :) did you give it a try?

**Comment by Javi-er** [comment]
Thanks, that fixed it. I don't remember having read on the documentation that I need to place the project file inside "public" folder.

**Comment by flurinduerst** [comment]
You're welcome. @whatnickcodes maybe we should add a line to the documentation to make this clear?

**Comment by vatnoise** [comment]
Is that only for one website? Is it possible to add multiple websites? At the moment mine are synched and appear like:

    /var/www/domain.name/index.php
    /var/www/anotherdomain.name/index.php

**Comment by maxpou** [comment]
@vatnoise Checkout: https://github.com/maxpou/scotch-box/blob/master/pimpMyBox/custom-vhost.md

**Comment by sumnermic** [comment]
Hello,

Has this issue been resolved already?

**Comment by whatnickcodes** [comment]
Thanks guys
