### ISSUE TITLE
Use rvm as default version manager for Ruby instead of rbenv

### ISSUE THREAD

**Issue by realdubb** [scotch-io/scotch-box#242]
I needed version 2.2.5 of ruby for my project but the version of  rbenv that comes with scotch-box didn't have that so it recommended doing the following to update

```
If the version you need is missing, try upgrading ruby-build:

  cd ~/.rbenv/plugins/ruby-build && git pull && cd -
```

However the remote url for that repo not up to date. I also learned `rbenv` is seperate from it's`rbenv install` module -- more things to keep updated

Long story short - to keep scotch-box as _Vagrant LAMP Stack That Just Works™_, I'd recommend packaging it with rvm

That's what I ended up doing instead of re-configuring rbenv

**Comment by whatnickcodes** [comment]
Thanks. For the new box coming out this week...

We are using RVM (and NVM)
