### ISSUE TITLE
VirtualHosts sometimes being overridden by the default web root

### ISSUE THREAD

**Issue by TomWright** [scotch-io/scotch-box#243]
In my project I have 2 public directories: `public_ui` and `public_api`. The related url for each is `finances.local` and `api.finances.local`.

My project structure looks like this:

    - public
    --- index.php -- Only here to enable me to confirm my suspicions that this was being used instead of the associated vhost
    - public_api
    --- index.php
    - public_ui
    --- index.php
    - Vagrantfile

The contents of my Vagrantfile are as follows:

    # -*- mode: ruby -*-
    # vi: set ft=ruby :
    Vagrant.configure("2") do |config|

        config.vm.box = "scotch/box"
        config.vm.network "private_network", ip: "192.168.33.11"
        config.vm.hostname = "finances.local"
        config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.manage_guest = true
        config.hostmanager.ignore_private_ip = false
        config.hostmanager.include_offline = true
        config.hostmanager.aliases = %w(api.finances.local)

        config.vm.provision "shell", path: "provision/provision.sh"

        config.vm.provision "shell", inline: <<-SHELL

            DOMAINS=("finances.local" "api.finances.local")
            DOMAIN_DIRS=("public_ui" "public_api")

            ## Loop through all sites
            for ((i=0; i < ${#DOMAINS[@]}; i++)); do

                ## Current Domain
                DOMAIN=${DOMAINS[$i]}
                ## Current Domain vHost Dir
                DOMAIN_DIR=${DOMAIN_DIRS[$i]}

                echo "Creating directory for $DOMAIN..."
                #mkdir -p /var/www/$DOMAIN/public

                echo "Creating vhost config for $DOMAIN..."
                sudo cp /etc/apache2/sites-available/scotchbox.local.conf /etc/apache2/sites-available/$DOMAIN.conf

                echo "Updating vhost config for $DOMAIN..."
                sudo sed -i s,scotchbox.local,$DOMAIN,g /etc/apache2/sites-available/$DOMAIN.conf
                sudo sed -i s,/var/www/public,/var/www/$DOMAIN_DIR,g /etc/apache2/sites-available/$DOMAIN.conf

                echo "Enabling $DOMAIN. Will probably tell you to restart Apache..."
                sudo a2ensite $DOMAIN.conf

            done

            echo "So let's restart apache..."
            sudo service apache2 restart

        SHELL

    end

The problem is that when visiting either `finances.local` or `api.finances.local`, 50% of the time I get to the correct vhost directory, but then something happens (I have no idea what.. I'm not triggering it that I am aware of) and both of `finances.local` and `api.finances.local` both start getting pointed to public instead of the related ui/api directory.

This has happened right after calling `vagrant up`, `vagrant provision`, and also a mixture of seconds or minutes after running `vagrant up` and having it work as expected.

**Comment by jeremiecook** [comment]
Hello,

I just got stucked for a day with the same strange issue.
In my case, I had 2 virtual machines running at the same time (Don't how it happened, though)

Opening VirtualBox and closing all running machines solved the problem.

Hope it helps,
Jérémie

**Comment by TomWright** [comment]
Hi Jeremie,

Thanks for the help!

It looks like I had a similar issue, except it wasn't quite as easily solved. I had to manually remove the machines from VirtualBox as they were "inaccessible". I probably messed things up a while ago - it's been a while since I've used it.

Anyway... all seems well now so I am going to close this issue.
