### ISSUE TITLE
Enhancement: Add XDebug

### ISSUE THREAD

**Issue by mcordingley** [scotch-io/scotch-box#244]
With these additional configuration values in both php.ini files:

    xdebug.remote_enable=1
    xdebug.remote_host=192.168.33.1
    xdebug.remote_autostart=1

This way, the VM side of things comes set up out of the box for interactive debugging. It will attempt to connect to the host on each script execution. If there is no debugger listening on the host, it will continue with script execution without issue or delay.

**Comment by maxpou** [comment]
:warning:  Take care, xdebug may impact runtime performance (i.e. tools like Composer).

Read this: http://nikic.github.io/2012/01/19/Careful-XDebug-can-skew-your-performance-numbers.html

**Comment by mcordingley** [comment]
True, but Scotchbox is intended for development purposes, not production systems. Same goes for XDebug. You wouldn't run it on a production system. The performance overhead that XDebug would incur should be small enough that it wouldn't even be noticed in a development setting. What's a few more milliseconds when there's only the one user?

**Comment by whatnickcodes** [comment]
- https://github.com/scotch-io/scotch-box/issues/203
- https://github.com/scotch-io/scotch-box/issues/90
- https://github.com/scotch-io/scotch-box/issues/7

No plans for this guys! Sorry
