### ISSUE TITLE
How do I enable enchant?

### ISSUE THREAD

**Issue by vatnoise** [scotch-io/scotch-box#245]
Need enchant for my project, is there a way to enable it?

**Comment by maxpou** [comment]
```
sudo apt-get install enchant
sudo apt-get install libenchant-dev
sudo apt-get install php7.0-enchant
```

doesn't work?

**Comment by vatnoise** [comment]
> sudo apt-get install php7.0-enchant

Forgot to mention it's PHP 5.* :)

**Comment by vatnoise** [comment]
I think it installed `enchant` ok but threw errors on `libenchant-dev` and `php5-enchant`:

	vagrant@scotchbox:~$ php -v
	PHP 5.6.14-1+deb.sury.org~trusty+1 (cli)
	Copyright (c) 1997-2015 The PHP Group
	Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
	    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies




	vagrant@scotchbox:~$ sudo apt-get install enchant
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	The following extra packages will be installed:
	  aspell aspell-en dictionaries-common hunspell-en-us libaspell15
	  libenchant1c2a libhunspell-1.3-0
	Suggested packages:
	  aspell-doc spellutils wordlist emacsen-common jed-extra hunspell
	  openoffice.org-hunspell openoffice.org-core libenchant-voikko
	The following NEW packages will be installed:
	  aspell aspell-en dictionaries-common enchant hunspell-en-us libaspell15
	  libenchant1c2a libhunspell-1.3-0
	0 upgraded, 8 newly installed, 0 to remove and 6 not upgraded.
	Need to get 1,345 kB of archives.
	After this operation, 5,507 kB of additional disk space will be used.
	Do you want to continue? [Y/n] Y
	Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libaspell15 amd64 0.60.7~20110707-1ubuntu1 [335 kB]
	Get:2 http://archive.ubuntu.com/ubuntu/ trusty/main dictionaries-common all 1.20.5 [232 kB]
	Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main aspell amd64 0.60.7~20110707-1ubuntu1 [78.4 kB]
	Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main aspell-en all 7.1-0-1 [267 kB]
	Get:5 http://archive.ubuntu.com/ubuntu/ trusty/main hunspell-en-us all 20070829-4ubuntu3 [248 kB]
	Get:6 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libhunspell-1.3-0 amd64 1.3.2-6ubuntu2.1 [108 kB]
	Get:7 http://archive.ubuntu.com/ubuntu/ trusty/main libenchant1c2a amd64 1.6.0-10ubuntu1 [64.7 kB]
	Get:8 http://archive.ubuntu.com/ubuntu/ trusty/main enchant amd64 1.6.0-10ubuntu1 [12.2 kB]
	Fetched 1,345 kB in 0s (2,418 kB/s)
	Preconfiguring packages ...
	Selecting previously unselected package libaspell15.
	(Reading database ... 94189 files and directories currently installed.)
	Preparing to unpack .../libaspell15_0.60.7~20110707-1ubuntu1_amd64.deb ...
	Unpacking libaspell15 (0.60.7~20110707-1ubuntu1) ...
	Selecting previously unselected package dictionaries-common.
	Preparing to unpack .../dictionaries-common_1.20.5_all.deb ...
	Adding 'diversion of /usr/share/dict/words to /usr/share/dict/words.pre-dictionaries-common by dictionaries-common'
	Unpacking dictionaries-common (1.20.5) ...
	Selecting previously unselected package aspell.
	Preparing to unpack .../aspell_0.60.7~20110707-1ubuntu1_amd64.deb ...
	Unpacking aspell (0.60.7~20110707-1ubuntu1) ...
	Selecting previously unselected package aspell-en.
	Preparing to unpack .../aspell-en_7.1-0-1_all.deb ...
	Unpacking aspell-en (7.1-0-1) ...
	Selecting previously unselected package hunspell-en-us.
	Preparing to unpack .../hunspell-en-us_20070829-4ubuntu3_all.deb ...
	Unpacking hunspell-en-us (20070829-4ubuntu3) ...
	Selecting previously unselected package libhunspell-1.3-0:amd64.
	Preparing to unpack .../libhunspell-1.3-0_1.3.2-6ubuntu2.1_amd64.deb ...
	Unpacking libhunspell-1.3-0:amd64 (1.3.2-6ubuntu2.1) ...
	Selecting previously unselected package libenchant1c2a:amd64.
	Preparing to unpack .../libenchant1c2a_1.6.0-10ubuntu1_amd64.deb ...
	Unpacking libenchant1c2a:amd64 (1.6.0-10ubuntu1) ...
	Selecting previously unselected package enchant.
	Preparing to unpack .../enchant_1.6.0-10ubuntu1_amd64.deb ...
	Unpacking enchant (1.6.0-10ubuntu1) ...
	Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
	Processing triggers for postgresql-common (154ubuntu1) ...
	Building PostgreSQL dictionaries from installed myspell/hunspell packages...
	  en_us
	Removing obsolete dictionary files:
	Setting up libaspell15 (0.60.7~20110707-1ubuntu1) ...
	Setting up dictionaries-common (1.20.5) ...
	Setting up libhunspell-1.3-0:amd64 (1.3.2-6ubuntu2.1) ...
	Processing triggers for dictionaries-common (1.20.5) ...
	aspell-autobuildhash: processing: en [en-common]
	aspell-autobuildhash: processing: en [en-variant_0]
	aspell-autobuildhash: processing: en [en-variant_1]
	aspell-autobuildhash: processing: en [en-variant_2]
	aspell-autobuildhash: processing: en [en-w_accents-only]
	aspell-autobuildhash: processing: en [en-wo_accents-only]
	aspell-autobuildhash: processing: en [en_CA-variant_0]
	aspell-autobuildhash: processing: en [en_CA-variant_1]
	aspell-autobuildhash: processing: en [en_CA-w_accents-only]
	aspell-autobuildhash: processing: en [en_CA-wo_accents-only]
	aspell-autobuildhash: processing: en [en_GB-ise-w_accents-only]
	aspell-autobuildhash: processing: en [en_GB-ise-wo_accents-only]
	aspell-autobuildhash: processing: en [en_GB-ize-w_accents-only]
	aspell-autobuildhash: processing: en [en_GB-ize-wo_accents-only]
	aspell-autobuildhash: processing: en [en_GB-variant_0]
	aspell-autobuildhash: processing: en [en_GB-variant_1]
	aspell-autobuildhash: processing: en [en_US-w_accents-only]
	aspell-autobuildhash: processing: en [en_US-wo_accents-only]
	Setting up aspell (0.60.7~20110707-1ubuntu1) ...
	Setting up hunspell-en-us (20070829-4ubuntu3) ...
	Setting up libenchant1c2a:amd64 (1.6.0-10ubuntu1) ...
	Setting up enchant (1.6.0-10ubuntu1) ...
	Processing triggers for dictionaries-common (1.20.5) ...
	Setting up aspell-en (7.1-0-1) ...
	Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
	Processing triggers for dictionaries-common (1.20.5) ...




	vagrant@scotchbox:~$ sudo apt-get install libenchant-dev
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	The following extra packages will be installed:
	  libelfg0 libglib2.0-bin libglib2.0-dev libpcre3-dev libpcrecpp0
	Suggested packages:
	  libglib2.0-doc
	The following NEW packages will be installed:
	  libelfg0 libenchant-dev libglib2.0-bin libglib2.0-dev libpcre3-dev
	  libpcrecpp0
	0 upgraded, 6 newly installed, 0 to remove and 6 not upgraded.
	Need to get 1,698 kB of archives.
	After this operation, 12.7 MB of additional disk space will be used.
	Do you want to continue? [Y/n] Y
	Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libelfg0 amd64 0.8.13-5 [37.6 kB]
	Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main libpcrecpp0 amd64 1:8.31-2ubuntu2.1
	  404  Not Found [IP: 91.189.88.161 80]
	Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libglib2.0-bin amd64 2.40.2-0ubuntu1 [34.9 kB]
	Get:3 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libglib2.0-dev amd64 2.40.2-0ubuntu1 [1,322 kB]
	Err http://security.ubuntu.com/ubuntu/ trusty-security/main libpcrecpp0 amd64 1:8.31-2ubuntu2.1
	  404  Not Found [IP: 91.189.91.26 80]
	Err http://security.ubuntu.com/ubuntu/ trusty-security/main libpcre3-dev amd64 1:8.31-2ubuntu2.1
	  404  Not Found [IP: 91.189.91.26 80]
	Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main libenchant-dev amd64 1.6.0-10ubuntu1 [51.9 kB]
	Fetched 1,446 kB in 0s (2,897 kB/s)
	E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/pcre3/libpcrecpp0_8.31-2ubuntu2.1_amd64.deb  404  Not Found [IP: 91.189.91.26 80]

	E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/pcre3/libpcre3-dev_8.31-2ubuntu2.1_amd64.deb  404  Not Found [IP: 91.189.91.26 80]

	E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?




	vagrant@scotchbox:~$ sudo apt-get install php5-enchant
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	The following NEW packages will be installed:
	  php5-enchant
	0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
	Need to get 9,118 B of archives.
	After this operation, 76.8 kB of additional disk space will be used.
	Err http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ trusty/main php5-enchant amd64 5.6.14+dfsg-1+deb.sury.org~trusty+1
	  404  Not Found
	E: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/pool/main/p/php5/php5-enchant_5.6.14+dfsg-1+deb.sury.org~trusty+1_amd64.deb  404  Not Found

	E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by maxpou** [comment]
Did you read the errors messages ?

**Comment by whatnickcodes** [comment]
This will be added by default in the box release this week
