### ISSUE TITLE
Backing up MySQL databases 

### ISSUE THREAD

**Issue by gitressa** [scotch-io/scotch-box#246]
Say I have a Scotchbox, like this: /home/user/scotch-box/

Containing these files and folders:
- /home/user/scotch-box/public
- /home/user/scotch-box/.git
- /home/user/scotch-box/.vagrant
- /home/user/scotch-box/README.md
- /home/user/scotch-box/Vagrantfile
- /home/user/scotch-box/.gitignore

If I make a copy of /home/user/scotch-box/, will MySQL also be backed up, and follow along, or is there some other way of doing that?

**Comment by Netw0rkeu** [comment]
An integrated MySQL backup option would be realy nice!

**Comment by madebyaris** [comment]
Yeah I need that too

**Comment by slibbe** [comment]
You could make a script for dumping databases, and have this run automatically when shutting down the box via the Vagrantfile.

**Comment by maxpou** [comment]
@gitressa : if you want to dump your tables, simply do this : `mysqldump --all-databases > /var/www/dump.sql`. Or `mysqldump --databases aSpecificDB > /var/www/dump.sql`

:book: MySQL Doc: https://dev.mysql.com/doc/refman/5.7/en/mysqldump-sql-format.html

@slibbe : FYI, dumping DB is **slow**, so it's not a good idea to put it for everyone (try it with a >500MB DB!). But you can create your own script! You just need to put the file in  `/etc/rc6.d` and `sudo chmod +x dumpDatabaseScript`. That's all!

BTW, always start your script with a *shebang* line (`#!/bin/sh`)

**Comment by gitressa** [comment]
Thanks, I now use this to back up my Drupal site: `drush sql-dump > aSpecificDB_`date +"%m_%d_%Y_%H%M"`.sql` - where the date part prints out the current data and time.

A plain SQL version: `mysqldump --databases aSpecificDB > /var/www/public/aSpecificDB_`date +"%m_%d_%Y_%H%M"`.sql`
