### ISSUE TITLE
The uploaded file exceeds the upload_max_filesize directive in php.ini.

### ISSUE THREAD

**Issue by sumnermic** [scotch-io/scotch-box#248]
Hello,

I've received the following WordPress error:

> "The uploaded file exceeds the upload_max_filesize directive in php.ini."

This error may take place when uploading a large file through WordPress Drag-n-drop in the 'Media Library' for example, or installing a large plugin like _Backup Buddy_.

The problem is easily solvable, but this becoming quite mundane.

What would be the best solution to get rid of this issue. I had to edit `/etc/php5/apache2/php.ini` to accomplish this. 😱 

`upload_max_filesize = 64M`
`post_max_size = 10M`
`max_execution_time = 300`

I'd like to suggest a feature to have this installed in php by default if possible?

Kind regards,

sumnermic

**Comment by veganista** [comment]
Add this to your provision script:

    config.vm.provision "shell", inline: <<-SHELL
        echo 'echo "upload_max_filesize = 64M" >> /etc/php5/apache2/conf.d/user.ini' | sudo -s
        echo 'echo "post_max_size = 10M" >> /etc/php5/apache2/conf.d/user.ini' | sudo -s
        echo 'echo "max_execution_time = 300" >> /etc/php5/apache2/conf.d/user.ini' | sudo -s
        sudo service apache2 restart
    SHELL

From here: https://github.com/scotch-io/scotch-box/issues/98#issuecomment-128778843

**Comment by whatnickcodes** [comment]
Perfect! And this is now added to the docs. Watch out for the release this week

**Comment by Blindmikey** [comment]
This no longer seems to work in Scotchbox 3.0

I believe it would be
```
echo 'echo "upload_max_filesize = 64M" > /etc/php/7.0/cli/conf.d/user.ini' | sudo -s
echo 'echo "post_max_size = 10M" > /etc/php/7.0/cli/conf.d/user.ini' | sudo -s
echo 'echo "max_execution_time = 300" > /etc/php/7.0/cli/conf.d/user.ini' | sudo -s
```

**Comment by whatnickcodes** [comment]
Correct me if I'm wrong, but isn't the path

`/etc/php/7.0/cli/conf.d/user.ini`

**Comment by Blindmikey** [comment]
That's what' I've got above, though when testing this, the values from `/etc/php/7.0/cli/conf.d/user.ini` don't seem to have an effect. 

Is this the right path? it shows up in the list shown by `php --ini`

**Comment by whatnickcodes** [comment]
Oh sorru I meant:

`/etc/php/7.0/apache/conf.d/user.ini`

Or something like that

**Comment by Blindmikey** [comment]
Awesome, yes, that seems to be the right path. Thanks!

**Comment by whatnickcodes** [comment]
Woot!

**Comment by epierpont** [comment]
I am not a Vagrant expert and it took me way too long to figure out that I had to run `vagrant provision` after the change to the script.
