### ISSUE TITLE
Update NFS configuration to improve download speed

### ISSUE THREAD

**Issue by gitressa** [scotch-io/scotch-box#250]
When downloading projects with many files using NFS synced folders, the process can get really slow. I found a page with some suggestions (https://www.jverdeyen.be/vagrant/speedup-vagrant-nfs/) and adding those settings made it a lot faster:

OLD, SLOW CONFIG
`config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }`

FASTER CONFIG
`config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666", 'vers=3', 'tcp', 'fsc' ,'actimeo=2'] }`

**Comment by whatnickcodes** [comment]
Nice! Let me look into this. If I don't add this to the actual `Vagrantfile`, I'll add it to the docs

**Comment by gitressa** [comment]
I am very much looking forward to the new Scotchbox, thanks a lot for working on it!

I just did some benchmarking with some standard Drupal commands, and adding those parameters don't seem to make much difference, so perhaps it's better to just leave the Vagrantfile as it is?

**ORIGINAL config.vm.synced_folder**
_config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }_
$ drush dl drupal --debug
Returned from hook drush_pm_download [100.45 sec, 10.36 MB][debug]
Command dispatch complete [100.45 sec, 10.32 MB] 

$ drush dl redirect --debug
Returned from hook drush_pm_download [1.05 sec, 11.7 MB][debug]
Command dispatch complete [1.05 sec, 11.66 MB] 

$ rm drupal-8.3.2/ -rf
9 sekunder

**config.vm.synced_folder with vers and tcp**
_config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666", 'vers=3', 'tcp', 'fsc' ,'actimeo=2'] }_
$ drush dl drupal --debug
Returned from hook drush_pm_download [97.76 sec, 10.36 MB] [debug]
Command dispatch complete [97.77 sec, 10.32 MB] [notice]

$ drush dl redirect --debug
Returned from hook drush_pm_download [1.29 sec, 11.7 MB] [debug]
Command dispatch complete [1.29 sec, 11.66 MB]

$  rm drupal-8.3.2/ -rf
14 seconds

**Comment by whatnickcodes** [comment]
Nice. Can you explain though what your config is differently? Like what the params do?

The most important thing for Scotch Box to work on as many systems out of the box as possible. Just want to make sure

**Comment by gitressa** [comment]
My config is just the default, so with parameters I just meant **'vers=3', 'tcp', 'fsc' ,'actimeo=2'** from below. Sorry if I wasn't clear about that.

 `config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666", 'vers=3', 'tcp', 'fsc' ,'actimeo=2'] }`
