### ISSUE TITLE
Error on vagrant commands

### ISSUE THREAD

**Issue by rowboat85** [scotch-io/scotch-box#259]
Hi there,
Having issues executing any vagrant command up/halt/destroy...everything was working fine yesterday until this morning I do a vagrant up and I get the following:

An action 'up' was attempted on the machine 'default',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.

If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.

Please help!

**Comment by maxpou** [comment]
Hello @rowboat85 ,
Checkout Vagrant issues (https://github.com/mitchellh/vagrant/issues).
It doesn't seems to be related to the scotch-box itself.

Regards

**Comment by whatnickcodes** [comment]
@maxpou is right. Thanks
