### ISSUE TITLE
Enable Apache modules to support H5BP’s server configs.

### ISSUE THREAD

**Issue by Zegnat** [scotch-io/scotch-box#26]
H5BP, best known for the HTML5 Boilerplate, have published some recommended server configs over at [h5bp/server-configs-apache](https://github.com/h5bp/server-configs-apache). For these some additional Apache modules need to be turned on. The ones disabled from Scotch Box are:

* [`mod_expires.c` (expires_module)](https://httpd.apache.org/docs/current/mod/mod_expires.html)
* [`mod_headers.c` (headers_module)](https://httpd.apache.org/docs/current/mod/mod_headers.html)
* [`mod_include.c` (include_module)](https://httpd.apache.org/docs/current/mod/mod_include.html)

Could these be enabled by default?

---

For people who want to use this before a possible future Scotch Box update:

1. Connect to the server using `vagrant ssh`.
2. Do `sudo a2enmod setenvif headers deflate filter expires rewrite include` to enable all the default modules. ([Command from h5bp.](https://github.com/h5bp/server-configs-apache/wiki/How-to-enable-Apache-modules#linux))
3. Do `sudo service apache2 restart`.

**Comment by ncerminara** [comment]
Thanks for the tip!  Run: `vagrant box update`

Finally added this
