### ISSUE TITLE
Linux Mint: "The box 'scotch/box' could not be found."

### ISSUE THREAD

**Issue by StarfallProjects** [scotch-io/scotch-box#261]
I seem to be very stuck. It's all working fine on my Windows PC, but when I tried to bring it up on my Linux PC, I got this error:
The box 'scotch/box' could not be found.

I figured maybe I was messing things up by having it sharing and syncing over Dropbox (yes my dev setup is shitty, so sue me) --- though it works between different Windows PCs

So I decided to do a completely fresh install on Mint. I checked I had Vagrant and VB (correct version), did the git clone, and ran vagrant up expecting it to install. But it never tried to install/download. Just went straight to the error message.

So it looks like maybe it's failing to import the base box?

**Comment by PhoenixJam** [comment]
Had the same issue from a fresh new git clone. I'm using elementaryOS here.

**Comment by lhmoraes** [comment]
Had the same issue using MAC Sierra

**Comment by PhoenixJam** [comment]
Hey man. In my case, the default version given by apt-get of vagrant at elementary was actually very old and had to be updated. I downloaded from the site to solve my problem.
 Take a look at the version installed there

**Comment by peter-gordon** [comment]
Had the same issue on Mac. Apparently it has to do with Vagrant 1.8.7's built in curl. 
This fixed it for me: http://stackoverflow.com/questions/40473943/vagrant-box-could-not-be-found-or-could-not-be-accessed-in-the-remote-catalog

YMMV

**Comment by whatnickcodes** [comment]
You can always use the direct links which will be added to the docs later this week

https://github.com/scotch-io/scotch-box/issues/278
