### ISSUE TITLE
Add Yarn as package manager

### ISSUE THREAD

**Issue by dstollie** [scotch-io/scotch-box#264]
A week ago Facebook together with some big friends released [Yarn](https://code.facebook.com/posts/1840075619545360/yarn-a-new-package-manager-for-javascript/). Yarn is a package manager just like npm wich but way faster and reliable than npm is. Yarn is compatible with all the curent node packages and uses the npm and bower registries for getting packages. Could you add yarn by default in the scotch box so I don't have to add this in my provisioning file?

**Comment by weekend-coder** [comment]
+1 for this

**Comment by whatnickcodes** [comment]
Boom added to the new box coming out this week
