### ISSUE TITLE
IE 11 problem - keep getting 'problem with this website’s security certificate' (although works fine on Google Chrome which uses the same certificate store)

### ISSUE THREAD

**Issue by gkimpson** [scotch-io/scotch-box#266]
I am running Vagrant 1.8.6 (the latest version at the time of the post) and running this on my Windows 10 Home machine. I have setup Vagrant using the popular 'Scotchbox' configuration from this website https://box.scotch.io

I have two applications- one frontend app using Angular and another backend application using the Zend Framework each mapped to their own IP/domain name which is configured in the hosts file for both the host machine and guest machine etc.. The frontend application basically authenticates with the backend database (this db is running locally in the backend vagrant instance) and communicates to the frontend app. This all works fine and as expected on Google Chrome and Firefox but for whatever reason this never works on either Internet Explorer 11 or Microsoft Edge. I am testing in IE 11 and I keep getting the infamous message when try to access the backend IP/domain.

There is a problem with this website’s security certificate.

e.g 
http://192.168.33.10 - this IP works fine
https://192.168.33.11 - this IP doesn't (obviously related to the SSL stuff....)

I have created an apache.crt & apache.key file for the backend box basically using this guide here - https://www.digitalocean.com/community/tutorials/how-to-create-a-ssl-certificate-on-apache-for-ubuntu-14-04

I just cannot understand why this would work fine with Chrome when both browsers use the Certification Store (Firefox uses its own store that is independant to the built in Windows one) - can anyone suggest why this maybe happening and how to fix this if at all possible?

Let me know if you need any other info/logs/debugging details - it is just weird as the setup **definitely works in Chrome and Firefox**

**Comment by maxpou** [comment]
Hi, did you read this: https://support.microsoft.com/en-us/kb/2851628 ?

**Comment by whatnickcodes** [comment]
@maxpou Thanks for all help on these issues. Appreciate big time
