### ISSUE TITLE
CAKEPHP'S "bin/cake bake" command not found

### ISSUE THREAD

**Issue by Blessings9** [scotch-io/scotch-box#267]
so i have recently installed CAKEPHP on the box and it works fine but when i try to use the "bin/cake bake" command i gee the following output:

> vagrant@scotchbox:/var/www/public/MyApp$ bin/cake bake all users
> -bash: bin/cake: Permission denied
> vagrant@scotchbox:/var/www/public/MyApp$ 

and i tried to prefix the command with sudo i got the following:

> vagrant@scotchbox:/var/www/public/MyApp$ sudo bin/cake bake all users
> sudo: bin/cake: command not found
> vagrant@scotchbox:/var/www/public/MyApp$ 
> My Host machine is running Linux MInt 17 64bit

**Comment by maxpou** [comment]
Oh it's seems to be a classic permission problem.
Did you try: `sudo chmod +x bin/cake` (after a `cd /var/www/public/MyApp`) ?

**Comment by Blessings9** [comment]
yes i have tried that, the command executes but i still encounter the same problem when i execute the bin/cake bake command

**Comment by maxpou** [comment]
Can you show me the output of this command : `ls -l bin/cake` ?

**Comment by Blessings9** [comment]
That is what i get after running the commands
```
> vagrant@scotchbox:/var/www/public/myapp$ sudo chmod +x bin/cake
> vagrant@scotchbox:/var/www/public/myapp$ ls -l bin/cake
> -rw-rw-rw- 1 vagrant vagrant 1457 Oct 28 16:06 bin/cake
> vagrant@scotchbox:/var/www/public/myapp$ 
> ```

**Comment by akkaweb** [comment]
I think the issue is with your vagrant setup and not necessarily CakePHP. For example if you do `sudo chmod 600 bin/cake.bat` you will notice that the file's permission does not change. I dont know why that happens.

If this same behavior is happening with your setup, you might have to assign global permission to your synced folder in your VagrantFile or make the permission change in your machine and see it if propagates to your box.

**Comment by maxpou** [comment]
The result indicate that your file is not executable.
I don't understand why chmod isn't working. Usually `sudo` prefix isn't necessary, but according to your previous answer, if you do `chmod 777 bin/cake` it'll not change anything.

Like @akkaweb , I think that it's related to Vagrant itself.
Can you show me your vagrant file? (especially this lines: *config.vm.share_folder*)
What is your vagrant version? *(`vagrant -v` on your host)*

**Comment by Blessings9** [comment]
i am running vagrant version 1.8.6, but i had the same problem with vagrant version 1.8.1
the VAGRANT file contains the following info:


# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    
    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

end

**Comment by maxpou** [comment]
Hummm the fmode option is 666 (read&write only). The [vagrant documentation](https://www.vagrantup.com/docs/synced-folders/basic_usage.html) is very poor...  

So I've 2 options and I don't know which one is the best:
* Replace the *fmode* value by 777;
* Remove the mount_option.

After don't forget to reload your box: `vagrant reload --provision`

**Comment by maxpou** [comment]
Great! Don't forget to close this issue :)

**Comment by Blessings9** [comment]
sure thankx once again

**Comment by wopsononock** [comment]
Changing fmode=666 to fmode=766 is sufficient.  Make sure to save and run vagrant reload.
