### ISSUE TITLE
Can't connect to scotch-box on a public wifi network

### ISSUE THREAD

**Issue by iamgoodbytes** [scotch-io/scotch-box#27]
First of all, I'm a big fan of scotch box, it works fantastic when developing at home. However, when I'm on a public wifi network, I'm unable to SSH into scotchbox, probably because it can't assign an IP address? 

It hangs at "default: Warning: Connection timeout. Retrying..."

When I'm at home I don't have this problem, I tried the following with no luck:
config.vm.network "public_network"

vagrant ssh gives me the following error: 
ssh_exchange_identification: Connection closed by remote host

Any ideas if this can be solved?

Thanks for all the great work!

**Comment by ncerminara** [comment]
Some networks disable certain ports and things (SSH, IRC, etc...). If it's just happening on that network, it's probably a network issue versus a Scotch Box issue. I successfully have ran Scotch Box on tons of public networks.

**Comment by ncerminara** [comment]
Can you reopen this though if the problem persists on other networks or you have more information?

**Comment by iamgoodbytes** [comment]
Hi @ncerminara I'm at home now (where this box was working just fine the past week). I'm having the exact same issue so it wasn't the network after all. I'm confused why SSH is throwing a timeout now and not in the past few days. 

What additional information can I provide? 

Also, isn't scotchbox/vagrant a local thing when just booting up (except for checking for updates maybe). Isn't vagrant ssh a local connection instead that should work on any wifi network?

Thanks again for trying to help out!

**Comment by iamgoodbytes** [comment]
Solved by running vagrant destroy and vagrant up. I have no idea what went wrong, sorry about that!

**Comment by NeriJunior** [comment]
I've the same error!
