### ISSUE TITLE
Apache site 000-default.conf overrides scotchbox.local.conf

### ISSUE THREAD

**Issue by sloanlance** [scotch-io/scotch-box#271]
The default installation of scotch-box has both `000-default.conf` and `scotchbox.local.conf` installed in `/etc/apache2/sites-enabled/`.  They both try to configure `VirtualHost *:80`. Only `000-default.conf` is successful, because that one comes first by filename and only the first configuration of the virtual host is accepted.  Most (all?) changes to `scotchbox.local.conf` are ignored in this case.  I noticed this when I tried to use `SetEnv` in the scotch-box file, but it didn't have any effect on the environment.

One solution is to **_disable the `000-default` site_**:

```sh
sudo a2dissite 000-default
```

⚠️ However, some settings from `000-default.conf` may not be available when using only `scotchbox.local.conf`.  **_Dynamically include the default settings into the scotch-box configuration file or add them statically_**.

ℹ️ Also see issue #187, which uses `default-ssl.conf` when setting up a configuration for HTTPS support.  **_Consider adding the default SSL settings to the scotch-box configuration_**.

**Comment by whatnickcodes** [comment]
Getting rid of `scotchbox.local.conf` in the next release since I don't think it's really necessary and will use 000-default instead

**Comment by clotted** [comment]
Would be useful to update the docs for vhosts setup for SB3.0:

For latest SB this:
sudo cp /etc/apache2/sites-available/scotchbox.local.conf/etc/apache2/sites-available/$DOMAIN.conf

Should read:
sudo cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/$DOMAIN.conf

**Comment by clotted** [comment]
This solved vhost issues for me on SB3.0:
[https://github.com/scotch-io/scotch-box-pro/issues/13#issuecomment-366101698]
