### ISSUE TITLE
Existing VirtualBox installation not detected

### ISSUE THREAD

**Issue by gm-seow** [scotch-io/scotch-box#272]
I get the following message after `git clone https://github.com/scotch-io/scotch-box.git my-project` and `vagrant up`

`Provider 'virtualbox' not found. We'll automatically install it now...`

I am using Windows 10 and have VirtualBox (5.1.8 r111374) and Vagrant (1.8.1) installed (with Chocolatey for what it's worth). Both are accessible in the PATH. So I'm just a bit confused why it can't be seen.

**Comment by erronjason** [comment]
@gm-seow Does this issue occur with any vagrant box defined, or only with "scotch/box"?

The reason I ask is that I've also seen this pop up before and have had to remove/re-install virtualbox & vagrant until vagrant decides to work again (and yes, the binaries are in the path too).

**Comment by gm-seow** [comment]
I don't use Vagrant for anything else, so I should have done a bit more testing 😊 

It turns out that it's the same with every other box I tried. If you specify `vagrant up --provider virtualbox` you get:

```
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0
```

And if you just use `vagrant up` it offers to download the 'right' version for you.

There seem to be [mixed messages](https://github.com/mitchellh/vagrant/issues/5572) about exactly which version of Vagrant this has been fixed in (and some editing of config files may be required), but it's not a Scotch Box issue. My bad.

**Comment by erronjason** [comment]
No worries! Since that's the case, would you mind closing this issue?
