### ISSUE TITLE
Environment breaking escalation of #257 - Utilized PHP PPA now offline

### ISSUE THREAD

**Issue by erronjason** [scotch-io/scotch-box#273]
I'm splitting this into it's own issue due to it's global impact to all non-stock instances of Scotch Box as a whole. This post assumes you've read [my comment on #257](https://github.com/scotch-io/scotch-box/issues/257#issuecomment-259828235).

_tl;dr: installed php PPA is dead, if you wish to alter/add/change modules installed via that ppa, you're gonna have a bad time._

**Since we're at this stand-still and lots of us have work to do, I'd like to [bat-signal](http://vignette2.wikia.nocookie.net/batman/images/6/66/Bat_100.jpg) @whatnickcodes for intervention.**

This is a breaking change to most environments (any reliant on installing/altering php modules), and requires rectification as soon as possible. Due to the build process being effectively closed-source (if it's out there, I sure haven't found it), this will require direct intervention from someone with access to the aforementioned build scripts.

I am more than happy to help in any way possible. As a longtime sysadmin turned dev, I have no problem assisting with the creation/cleanup/updating. I was rolling my own vagrant customization to stock ubuntu prior to this, effectively creating the same thing until I found Scotch Box ~1.5 years ago. Since then, my team has been using it almost exclusively.

I cannot seem to find any public resources regarding the creation of the actual vagrant box from it's base machine. I see reference of the environment utilizing Chef, and Packer in the future; though a lack of the scripts themselves.

## Proposed solution going forward

_I'd like to take this time to formally propose open-sourcing the build scripts surrounding the Vagrant "scotch/box"._

With intentional regard to reducing the risk of hard forks/competing solutions, I still feel publishing the build scripts for the box would eliminate the panic and helplessness I'm feeling now.  Since the repo would optimally still be under the "scotch-io" GH organization, control (and final say) of included changes would still be handled (I assume) by Nicholas Cerminara.

The proposed solution would allow Nicholas to maintain the project's technical and creative direction, but remove the need for him to preform all legwork associated with configuration/upkeep. At the same time, fostering community around the development of Scotch Box.

I recommend that if my suggestion comes to fruition, the box's build process be placed in a separate repository than the example project repo (maintaining the low dependency nature of Scotch Box).

**Note:** _This issue is created with the intention of solving the problem with the PPA. While I do talk about it at length here, further discussion about the possibility of granting access to the build process should be carried out in a new issue (assumes there's discussion to be had)._

**Comment by whatnickcodes** [comment]
Eek about the PPA. The box is due for an upgrade.

I fully plan to provide the build scripts in the next release.

Let me try and prioritize this

**Comment by williamthe** [comment]
just wanted to try this nice box and old ppa arise. Waiting for the fixes :)

**Comment by uniacid** [comment]
This would be nice, I ran into this issue last night and just ended up manually fixing and updating my box for now but would love to have this fixed going forward, essentially you just need to remove the php 5.6 ppa repo and re-add it but use the php ppa repo: 

`rm /etc/apt/sources.list.d/ondrej-php5-compat-trusty.list`
`add-apt-repository ppa:ondrej/php`
`apt-get update`
See what you have installed that needs to be reinstalled
`dpkg --get-selections | grep -v deinstall | grep php5`
Remove prior php packages
`apt-get --purge remove php5-common`
Re-install latest packages (in my case)
`apt-get install libapache2-mod-php5.6 php5.6 php5.6-cgi php5.6-cli php5.6-common php5.6-curl php5.6-fpm php5.6-gd php5.6-intl php5.6-mcrypt php5.6-memcache php5.6-memcached php5.6-mongo php5.6-mysqlnd php5.6-pgsql php5.6-readline php5.6-redis php5.6-sqlite`
and restart Apache and PHP FPM
`service apache2 restart`
`service php5.6-fpm restart`

**Comment by erronjason** [comment]
@uniacid Correct. However, the ideal situation is not having to do this upon provision or basing a vagrant box atop scotch/box. If someone wishes to add this to the provision script and make it a pull request on this repo, I wouldn't be opposed.

**Comment by smutek** [comment]
I'm a good bit outside of my skill set here but I did this today on my fork, with the end goal of getting Xdebug installed. 

https://github.com/smutek/sassscotch/blob/master/vagrant_bootstrap/bootstrap.sh

It works when I `vagrant up` but the box takes forever to provision.

**Comment by uniacid** [comment]
@smutek I was going to do something similar but took what you had done and made a few adjustments and also made the system updates optional as that's what was adding on to the setup/provisioning time, pull request is here: #281

**Comment by gitressa** [comment]
It's been a month since ppa:ondrej/php5-5.6 were deleted ... is a new release of Scotch-box coming soon? Can anyone recommend a good alternative to Scotch-box, if a new version is not in the horizon?

**Comment by uniacid** [comment]
Not sure of any comparable vagrant box but there might be one, though it's definitely something that can be done if you know how and I'm contemplating building one but it's just the time/effort involved in keeping it maintained. That's why I'm thinking if I did it maybe it should be based off provisioning scripts instead of a full vagrant box but then that's going to add on to the setup/provision time or if anything at least share the provisioning scripts used to build the box that way updates or patches can be done in an easier manner by anyone.

**Comment by whatnickcodes** [comment]
Hey guys - This is huge priority, just damn EOY work stuff I'm dealing with. :/

I'm sorry for the delay I know this issue SUCKS

By Jan 1st I'll have updated the box and will provide scripts so people can start building your own box.

**Comment by gitressa** [comment]
Sounds good, I hope people have the patience! Is it mostly a matter of not being able to run Xdebug? I ask is because I actually have the latest version of Scotch-box up and running with Drupal, MySQL Solr and all...

**Comment by whatnickcodes** [comment]
In the meantime, check our issues and pull request. I think people wrote some scripts to squash this temporarily

**Comment by jonathanbossenger** [comment]
@whatnickcodes if there is any way I can assist please let me know.

**Comment by fbm-static** [comment]
Any update? It's March now.

**Comment by anselmdk** [comment]
I'm also really looking forward to a next release.

**Comment by vernard** [comment]
Patience is a virtue, my friends.

**Comment by mohnjatthews** [comment]
@vernard and virtue is a grace. And Grace is a little girl who doesn't wash her face.

The instructions given by @uniacid sorted my issues for now. Cheers buddy.

**Comment by erronjason** [comment]
@whatnickcodes If we could obtain access to the build scripts, we could likely allow the community to drive this a bit better. Having to re-install PHP every time you provision is a much lengthier process than it should be. You still maintain control of what makes it into the repo, thereby providing the direction for the project.

In the interim - All those wasted CPU cycles; think of the electricity man!

**Comment by anselmdk** [comment]
@whatnickcodes we've been waiting for this for more than 6 months now. I do understand you're busy, that's totally fair, just wanted to let you know that we'll be looking into other solutions now. We love Scotchbox, but it just doesn't work for us to go with an unmaintained solution.
In case you're actually planning to work on this in the foreseeable future, I'd appreciate a comment from you, in which case we'd consider sticking with Scotchbox.

Cheers

**Comment by mohnjatthews** [comment]
I think it's safe to assume that this project is now closed. It looks like Nick has a lot on his plate and don't have the time to update this repo, which it completely understandable.

It might be time to create a community edition of Scotchbox where we publicly write and design the build scripts for the vagrant box. @erronjason is that something you'd be interested in leading? I'd be happy to assist.

**Comment by whatnickcodes** [comment]
Stay tuned... I know everyone has been waiting for a big update

**Comment by erronjason** [comment]
@mohnjatthews I don't think we should consider the project closed. Simply in a state of odd limbo for a time. As Nick had mentioned there are pull requests that rectify the issue, though this is truly not ideal.

The larger issue here is six months of inaction. I don't want to deviate from this and split the community by any means, but it is currently locked to a single person's bandwidth.

I have no problem dedicating time to helping Nick open source some build scripts around the project. In this way, an issue like this can be solved by the community with minimal effort on Nick's part save for accepting the pull request and publishing the box.

@whatnickcodes Let me know your thoughts here.

**Comment by whatnickcodes** [comment]
Big update coming this week. Finished the new box over weekend

**Comment by mohnjatthews** [comment]
Any movement on this @whatnickcodes? Looks like the community's ready to help out if you're swamped with other work.

**Comment by whatnickcodes** [comment]
Yeah super soon. Probably today actually

**Comment by whatnickcodes** [comment]
Appreciate the patience

**Comment by whatnickcodes** [comment]
# FIXED

**Comment by whatnickcodes** [comment]
Update to 3.0

**Comment by anselmdk** [comment]
@whatnickcodes I can't find any licensing information for the PRO version. How does this work? Does everyone on the development team need to buy the PRO license in case we include it, or is one enough?
The idea for us to use Vagrant is that it's easy to get new developers and freelancers on the boat, I think it gets a little more complicated if new people need to buy a license before getting started.

**Comment by whatnickcodes** [comment]
It's really not strict at all. If you see how I set it it up, you might even laugh. Buy a license and find out.

I'm going to update the page to answer this though

**Comment by anselmdk** [comment]
@whatnickcodes sure, will do, just gotta figure out for a moment if I'll purchase the "single user" or "unlimited" license - I guess that's the one I need for my use case, right?
