### ISSUE TITLE
Grav: bin/gpm: Permission denied

### ISSUE THREAD

**Issue by dillonraphael** [scotch-io/scotch-box#274]
I'm trying to get Grav working within my vagrant setup. Whenever I try to run bin/gpm index or bin/gpm install admin when I'm in the SSH I get this `bin/gpm: Permission denied.`
When I SSH into the box I try setting the permission and making the gpm file executable but it doesn't stick.

When I try running bin/gpm index inside the local folder I get  `No data was found in the GPM repository stored locally.
Please try clearing cache and running the bin/gpm index -f command again
If this doesn't work try tweaking your GPM system settings.`

**Comment by erronjason** [comment]
@dillonraphael When you say you're "in the SSH", I assume you've only run `vagrant ssh`. While this will connect you to the VM, you're not a privileged user. If you run `whoami` and it returns "vagrant", you're not the root user and may run into issues attempting to set permissions.

To escalate yourself to the root user upon login, run `vagrant ssh` followed by `sudo su`. Then try to set permissions on the GPM executable.

I don't think this is an issue with Scotch Box. Now that you know how to become root, I'd seek further help from the creators/maintainers of Grav (if your issues persist)

**Comment by maxpou** [comment]
it might be related to #267 
adapt your vagrant file and let me know. If it fails, show me the `ls -l bin/gpm` result, the full path to your gpm command file, and your vagrant file.

regards

**Comment by Hielkio** [comment]
You can solve this by making **gpm** executable :)
Make sure your location is the root of your Gravsite and enter this command:
`chmod +x bin/gpm`
After that you're able to use all of the variables without using the **php**-prefix
