### ISSUE TITLE
Ondrej's repository is not reachable

### ISSUE THREAD

**Issue by bernardfuentes** [scotch-io/scotch-box#275]
Hi.

There is no way to install xdebug because the Ondrej's repository is not reachable.

Error: W: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/dists/trusty/main/binary-amd64/Packages 404 Not Found

Regards,

**Comment by aldoanizio** [comment]
Hi. I've did an provisioner script that helps to fix this bug.

I've did two scripts, one using PHP 5.5 and another using 7.0.

I couldn't get PHP 5.6 Working due to Xdebug missing package but I think you won't have any kind of problem using 5.5 instead.

Please take a look: https://gist.github.com/anonymous/a447da6a10a1964c609234dd3ccbf4a8

To use one of those scripts just add this line to your Vagrant file:

config.vm.provision "shell", path: "provisioner-{5.5 or 7.0}.sh"

Notice that those scripts also replaces MySQL to MariaDB. If you like you can remove this part.

You have to rebuild your VM to take effect. Please Backup, Backup, Backup!!

It's not a definitive solution but it helps untill a new scotch box is released.

**Comment by kadimi** [comment]
Worked fine, I had to add a missing `php` in the path:

```ruby
config.vm.provision "shell", path: "provisioner-php5.5.sh"
# config.vm.provision "shell", path: "provisioner-php7.0.sh"
```

**Comment by piquerez** [comment]
In my case, I still have an error when user composer
I had to change php5-gd to php5.5-gd in the provisioner script provided.

Here is my provisioner file (with php5.5-gd and mysql) :

#!/usr/bin/env bash

# Update PHP Repo
sudo rm /etc/apt/sources.list.d/ondrej-php5-5_6-trusty.list
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get -y update

# Remove PHP 5.6
sudo apt-get --remove purge -y php5 php5-cli php5-curl php5-gd php5-intl php5-mcrypt php5-memcached php5-mysqlnd php5-readline php5-sqlite php5-cgi php5-common php5-fpm php5-imagick php5-json php5-memcache php5-mongo php5-pgsql php5-redis php-pear
sudo apt-get -y autoremove

# Install PHP 5.5
sudo apt-get -y install php5 php5-common php5-cgi php5-fpm php5-pgsql php5-cli php5-json php5-curl php5-mcrypt php5.5-gd php5-intl php5-mysql php5-readline php5-memcached php5-memcache php5-imagick php5-xdebug php5-redis php5-mongo php5.5-mbstring php5.5-sqlite3 php5.5-zip php5.5-xml php5.5-opcache mysql-server
sudo apt-get -y install libapache2-mod-php5.5
sudo service apache2 restart

# Remove MySQL
#sudo service mysql stop
#sudo apt-get remove --purge -y mysql-server
#sudo apt-get -y autoremove

# Install MariaDB
#sudo apt-get -y install software-properties-common
#sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
#sudo add-apt-repository -y 'deb [arch=amd64,i386,ppc64el] http://mirror.ufscar.br/mariadb/repo/10.1/ubuntu trusty main'
#sudo apt-get -y update
#export DEBIAN_FRONTEND=noninteractive
#sudo debconf-set-selections <<< 'mariadb-server-10.1 mysql-server/root_password password root'
#sudo debconf-set-selections <<< 'mariadb-server-10.1 mysql-server/root_password_again password root'
#sudo apt-get install -y mariadb-server
sudo service mysql restart

# Allow ROOT access
sudo sed -i "s/bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" /etc/mysql/my.cnf
sudo echo "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root' WITH GRANT OPTION" | mysql -u root --password=root
sudo echo "GRANT PROXY ON ''@'' TO 'root'@'%' WITH GRANT OPTION" | mysql -u root --password=root
sudo service mysql restart

# We Are Champions My Friend!!!

**Comment by uniacid** [comment]
Check out pull request #281 I've added a update provision script to remove and add the proper PPA and packages as well as Xdebug, optionally you can also enable system updates if want to update your vagrant box to the latest stable packages.

**Comment by whatnickcodes** [comment]
Fixed in new release coming this week. Closing for now to tidy up the Issues. Stay tuned this week

**Comment by dnaber-de** [comment]
Having the same issue with ScotchBox 3.0

**Comment by kadimi** [comment]
It's seems there is a faulty file in `/etc/apt/sources.list.d`, delete it and then install:

```shell
# Remove faulty source. 
sudo rm /etc/apt/sources.list.d/ondrej-php5-5_6-trusty.list

# Update package list.
sudo apt-get Update

# Install Xdebug.
sudo apt-get install php-xdebug

# Enable it.
sudo phpenmod xdebug

# Verify.
php -m | grep xdebug

**Comment by kadimi** [comment]
Hey @whatnickcodes, I believe this is a bug and I suggest deleting `/etc/apt/sources.list.d/ondrej-php5-5_6-trusty.list` to fix it.

Thanks,
Nabil

**Comment by s-belichenko-sold** [comment]
My script for scotch/box 2.5.0 and php 5.6:

```
echo "======================== Xdebug ============================"

echo "==> Downloading xdebug-2.5.4"
if ! [ -L xdebug-2.5.4.tgz ]; then
  sudo rm -rf xdebug-2.5.4.tgz
fi
wget http://xdebug.org/files/xdebug-2.5.4.tgz -nv >/dev/null 2>&1

echo "==> Preparing files"
if ! [ -L xdebug-2.5.4 ]; then
  sudo rm -rf xdebug-2.5.4
fi
tar -xvzf xdebug-2.5.4.tgz >/dev/null 2>&1
cd xdebug-2.5.4

echo "==> Installing phpize"
# see more here:
# https://github.com/scotch-io/scotch-box/issues/275
# https://askubuntu.com/questions/856996/cant-install-xdebug-depends-phpapi-20121212-ubuntu-14-04
sudo rm /etc/apt/sources.list.d/ondrej-php5-5_6-trusty.list
sudo add-apt-repository --yes ppa:ondrej/php >/dev/null 2>&1
sudo apt-get update >/dev/null 2>&1
sudo apt-get install php5.6-dev -qq --force-yes >/dev/null 2>&1

echo "==> Compiling Xdebug"
sudo phpize
sudo ./configure >/dev/null 2>&1
sudo make >/dev/null 2>&1

echo "==> Installing Xdebug"
sudo cp modules/xdebug.so /usr/lib/php5/20131226 >/dev/null 2>&1
echo "zend_extension = /usr/lib/php5/20131226/xdebug.so" | sudo tee --append /etc/php5/apache2/php.ini 2>&1 >/dev/null

echo "======================= End of work ======================="

echo "==> Restarting web server"
sudo service apache2 restart
```
