### ISSUE TITLE
Downgrading PHP

### ISSUE THREAD

**Issue by laughingpaintbrush** [scotch-io/scotch-box#276]
Hi,

While scotch box does the job perfectly for every project I work on, I have one right now that requires using PHP 5.3 

I saw there was a provisioner for downgrading to 5.5 https://gist.github.com/anonymous/a447da6a10a1964c609234dd3ccbf4a8

Is there a similar one available for downgrading to 5.3?

**Comment by whatnickcodes** [comment]
Going to add this to the docs. Closing for now. Will push live this week
