### ISSUE TITLE
External Access

### ISSUE THREAD

**Issue by highlabs** [scotch-io/scotch-box#28]
Hi! :)

How I can configure Scotch box for test site with other device?

I tried to configure port forward, without sucess. Anyone already did it?

**Comment by ncerminara** [comment]
Vagrant has this "Vagrant Share" for HTTP and SSH sharing (aka local tunnels).

Check it out here: https://scotch.io/tutorials/sharing-your-virtual-machine-on-the-web-with-vagrant-share

Super easy to do
