### ISSUE TITLE
Adding PhalconPHP Framework C++ Extension

### ISSUE THREAD

**Issue by yahyaerturan** [scotch-io/scotch-box#280]
Great work! Can you add [PhalconPHP Framework C++ Extension](https://phalconphp.com/en/) ?

**Comment by whatnickcodes** [comment]
Potentially. Trying to keep the box slim. Let me look into this framework a bit first to gauge popularity

**Comment by whatnickcodes** [comment]
Hey! Decided to keep this out of the box since it's so easy to install separately for sake of keeping things slim

**Comment by yahyaerturan** [comment]
Thanks anyway.. I have decided to do my own box based on your Scothbox for my personel use.. :) Thank you.

**Comment by whatnickcodes** [comment]
Awesome!
