### ISSUE TITLE
Heidi SQL can not connect to MySQL 

### ISSUE THREAD

**Issue by michaelnguyen547** [scotch-io/scotch-box#283]
I cant connect to MySQL server using HeidiSQL

Here is the screenshot 

![heidi-sql](https://cloud.githubusercontent.com/assets/436950/21441784/2a83b95e-c857-11e6-82ab-92bd10bfdfa5.png)

**Comment by ghabxph** [comment]
First, the network type should be MySQL (SSH Tunnel)
![image](https://cloud.githubusercontent.com/assets/11975597/22069104/415cdbf2-ddd2-11e6-80ee-325914741909.png)
And then, under the SSH tunnel, this should be the credential.
![image](https://cloud.githubusercontent.com/assets/11975597/22069135/57b1dbd2-ddd2-11e6-9fd1-d23ef6a7fc78.png)
Please don't forget to download plink.exe. It is already specified in the HeidiSQL. :)

**Comment by whatnickcodes** [comment]
Try 127.0.0.1 instead of localhost
