### ISSUE TITLE
Can't install php5-imap on new box

### ISSUE THREAD

**Issue by pengimo** [scotch-io/scotch-box#285]
I've created a brand new box but I can't install php5-imap.

First I was getting the message about Ondrej's repository is not reachable so I did the following:

    sudo rm /etc/apt/sources.list.d/ondrej-php5-5_6-trusty.list
    sudo add-apt-repository -y ppa:ondrej/php
    sudo apt-get -y update

Now when I run:

    sudo apt-get install php5-imap

I get the following error:

    The following packages have unmet dependencies:
    php5-imap : Depends: phpapi-20121212

Any clues as to what I need to do next?

**Comment by fbm-static** [comment]
Use **php-imap** not **php5-imap**

**Comment by pengimo** [comment]
Ah! That was simple :)

Thanks.
