### ISSUE TITLE
How to disable services on startup?

### ISSUE THREAD

**Issue by fbm-static** [scotch-io/scotch-box#288]
Hello,

I find some services unnecessary (e.g. Mongo, redis, postgres) and it would free up a bit of memory if these services were not enabled on startup. I have tried

```
echo manual | sudo tee /etc/init/mongod.override
```
But they're still running on startup of the VM. I would appreciate your help!

**Comment by maxpou** [comment]
Hi,
not sure at all about the real gain. Unused service consume (almost) nothing
checkout 

```sh
top | grep mongo
```

If you're still not conviced, shutdown this services with the following commands and run this script on loading.

```sh
sudo service mongod stop
```

Regards
