### ISSUE TITLE
Add "~/.composer/vendor/bin folder" to PATH environment variable

### ISSUE THREAD

**Issue by bill-barron** [scotch-io/scotch-box#29]
The number one thing I do every time I start up a new scotch-box is to log in via SSH and add "~/.composer/vendor/bin" to my PATH environment variable. This lets me install Laravel and other utilities with composer via SSH. The laravel executable is stored in "~/.composer/vendor/bin" after requiring it from composer.

**Comment by ncerminara** [comment]
I'll add this to my To-Do list ASAP. I'll try and get this done this week too

**Comment by jagandecapri** [comment]
Looking forward to this automation too. Currently, added ~/.composer/vendor/bin to bashrc.

**Comment by ncerminara** [comment]
This is finally, done:  Run: `vagrant box update`
