### ISSUE TITLE
HTTPS and HTTP

### ISSUE THREAD

**Issue by gabrielchiron** [scotch-io/scotch-box#290]
Hi!

I have a website in my server in HTTP and its all OK.

But we need use the website in HTTPS too, but only is HTTP open.

How i can open 443 for my website in scotch-box?? Im noob apache user :)

TY 4all!

**Comment by gabrielchiron** [comment]
Hi guys!

I have managed to solve itI

I close the issue! :D

**Comment by WolfieZero** [comment]
@gabrielchiron Could you post how you solved this for others?

**Comment by gabrielchiron** [comment]
WolfieZero, only you need is activate SSL:

`sudo a2enmod ssl`

Restart the server:

`sudo service apache2 restart`

Create a self signed certificate:

`sudo mkdir /etc/apache2/ssl`

`sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt`

And to finish is create a virtualhost to configure apache to use SSL.
(If you need a example of my virtualhost i can copy, tell me if you need).

Remember activate the conf :D 
`sudo a2ensite default-ssl.conf`
`sudo service apache2 restart`

**Comment by WolfieZero** [comment]
:+1:

**Comment by upjoes** [comment]
@gabrielchiron can you provide the virtualhost example you are talking about here? I am just doing the setup on my Scotch Box VM.

**Comment by gabrielchiron** [comment]
`<VirtualHost *:80>
        # Especificamos el dominio que tiene acceso.
        ServerName yourdomain.com

        # Especificamos el server alias.
        ServerAlias www.yourdomain.com

        # Especificamos mail del administrador de la red.
        ServerAdmin gabriel@yourdomain.com

        # Especificamos el documento donde esta nuestro proyecto.
        DocumentRoot /var/www/yourdomain.com/public_html

        # Especificamos los directorios de los logs.
        ErrorLog /var/www/yourdomain.com/logs/error.log
        CustomLog /var/www/yourdomain.com/logs/access.log combined
</VirtualHost>


<VirtualHost *:443>
        # Especificamos el dominio que tiene acceso.
        ServerName yourdomain.com

        # Especificamos el server alias.
        ServerAlias www.yourdomain.com

        # Especificamos mail del administrador de la red.
        ServerAdmin gabriel@yourdomain.com

        # Especificamos el documento donde esta nuestro proyecto.
        DocumentRoot /var/www/yourdomain.com/public_html

        # Especificamos los directorios de los logs.
        ErrorLog /var/www/yourdomain.com/logs/error.log
        CustomLog /var/www/yourdomain.com/logs/access.log combined

        #Activamos el SSL.
        SSLEngine on

        #Le indicamos donde estan los certificados.
        SSLCertificateFile /etc/apache2/ssl/apache.crt
        SSLCertificateKeyFile /etc/apache2/ssl/apache.key

        #SSL Options.
        <FilesMatch "\.(cgi|shtml|phtml|php)$">
                SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /usr/lib/cgi-bin>
                SSLOptions +StdEnvVars
        </Directory>
        BrowserMatch "MSIE [2-6]" \
                nokeepalive ssl-unclean-shutdown \
                downgrade-1.0 force-response-1.0
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
</VirtualHost>`

Very important:
```
SSLCertificateFile /etc/apache2/ssl/apache.crt
SSLCertificateKeyFile /etc/apache2/ssl/apache.key
```

In my path of my certificate files :) (SELF SIGNED)

**Comment by jordanboston** [comment]
Those steps where really helpful @gabrielchiron --thanks!
I have a _.local_ domain for the site I'm working on, so the only difference for me was the need to create my `.crt` and `.key` using steps in this article below instead.  I am on a Mac, so not sure how this will work if on another OS.  https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/

**Comment by Shoananas** [comment]
Hello,

I just downloaded the box and I'm trying to setup the SSL for a local website on 192.168.33.10.
I somehow managed to make the website run in https but the certifiate is not seen as valid, when I check it, it's not the one I generated but the "default" one, I don't recognize any of the informations I gave to create my own certificate.

I created a default-ssl.conf file as suggested by gabrielchiron's post with the following content:

```
<VirtualHost *:80>
        ServerName 192.168.33.10
</VirtualHost>

<VirtualHost *:443>
        ServerName 192.168.33.10
        DocumentRoot "www/html"

        SSLEngine on

        SSLCertificateFile /etc/apache2/ssl/server.crt
        SSLCertificateKeyFile /etc/apache2/ssl/server.key

        #SSL Options.
        <FilesMatch "\.(cgi|shtml|phtml|php)$">
                SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /usr/lib/cgi-bin>
                SSLOptions +StdEnvVars
        </Directory>
        BrowserMatch "MSIE [2-6]" \
                nokeepalive ssl-unclean-shutdown \
                downgrade-1.0 force-response-1.0
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
</VirtualHost>
```

also the DocumentRoot does not seem to work either.
The files server.crt and server.key do exist, I used the method described in jordanboston's last post.

Help please :(
