### ISSUE TITLE
simulate real https if API needs

### ISSUE THREAD

**Issue by csimpi** [scotch-io/scotch-box#291]
Hi guys,
I've searched for a day, but i can't find the solution.
I would like to accept push notifications from google calendar.
I have to share an url, what can provide REAL https connection.
I have a lot of virtual domains within vagrant install.

localtunnel doesnt works with virtualhosts some reason. I have the newest version vagrant, and localtunnel. If I don't use -l parameter, localtunnel works, but i can't reach the required website :(

Vagrant share can't provide real https connection. I've generated an ssl key with openssl and i've made ssl virtualhost file for apache, but it doesn't works, i get Bad Request. If i use my localhost with https it works.

So what should i do? :))
I would like ti reach my local vagrant virtualhost with https. Can i? Or i can't work with google api on vagrant?

https://developers.google.com/google-apps/calendar/v3/push

Thanks,
Peter

**Comment by whatnickcodes** [comment]
Check this out by @maxpou
