### ISSUE TITLE
Unprocessed orphan inode list -- Error mounting

### ISSUE THREAD

**Issue by carlos09** [scotch-io/scotch-box#293]
I was working on something last night, then all of a sudden my box stopped working. Tried reloading it, and it would get stuck on the 'SSH auth method: private key' message. Then after a while I would get this: 
```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

Got it output in the VM and I would get this message: 
`Couldn't remount RDWR because of unprocessed orphan inode list. Please unmount/remount instead. An error occurred while mounting /.`

In any case I have to abandon this box, does anyone know how to retrieve any databases that were running on this box?

**Comment by whatnickcodes** [comment]
Seems like an issue with your Vagrant / Virtual setup / OS and not the box. Going to close this. Can you confirm that you can other boxes working or not then reopen

**Comment by conflicker** [comment]
@carlos09 were you able to fix this? I'm having the same issue.

**Comment by carlos09** [comment]
@conflicker No i was not able to fix this. I had to set up a new vagrant box. 👎🏼

**Comment by whatnickcodes** [comment]
Seems like a Vagrant issue and unrelated to the box.

Did you just run `vagrant destroy` and then `vagrant up`

**Comment by hileamlakB** [comment]
This happens when you haven't successfully closed, which also happens when your system crashes. But before destroying your virtual machine try this because it worked for me. https://superuser.com/questions/947942/unprocessed-orphan-inode-list-in-virtualbox-vm
