### ISSUE TITLE
Apache Document Root

### ISSUE THREAD

**Issue by benjamin-derepas** [scotch-io/scotch-box#299]
Hello,

I've tried this vagrant box i didn't know, it's awesome ! 
Perfect, full feature i needed, but i have a probleme and i don't find the issue !

 - My vbox has been installed on /Users/Benjamin/webserver/scotch (Mac OS)
 - in this folder i have a public folder with index.php file resuming my webserver config .
 - But all my work's folder are in /Users/Benjamin/dropbox/sites/ so, how can i change the Apache Root please ?

**Comment by FlashPapa** [comment]
Hi,

Try this Vagrantfile on your install folder /Users/Benjamin/webserver/scotch  : 

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"

    config.hostmanager.aliases = %w(scotchbox.local dev.pai)

    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder "/Users/Benjamin/dropbox/sites", "/var/www/public", :mount_options => ["dmode=777", "fmode=666"]
    
    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

end
```

Have fun

**Comment by whatnickcodes** [comment]
https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#toc-changing-public-to-public_html
