### ISSUE TITLE
VirtualBox updated and now VM wont startup

### ISSUE THREAD

**Issue by juanfernandes** [scotch-io/scotch-box#305]
This may have nothing to do with scotch-box but I don't know how to fix this, so hoping someone has come across this and can help.

I'm using:
- Ubuntu 16.04 LTS
- VirtualBox 5.0.40_Ubuntu r115130
- Vagrant 1.9.5

This is the error I get when I run vagrant up on the command line:

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg*)" at line 71 of file VBoxManageHostonly.cpp

Thanks in advance

**Comment by whatnickcodes** [comment]
ALWAYS backup before you update.

Unfortunately this looks like a Vagrant / Virtual Box issue unrelated to this box. I'm going to close this, but feel free to re-open if you can't get answers through other channels.
