### ISSUE TITLE
Warning: Authentication failure. Retrying

### ISSUE THREAD

**Issue by gitressa** [scotch-io/scotch-box#308]
If you update your Scotch Box to version 3.0 with `vagrant box update`, next time you `vagrant up` the process will just loop, probably because a password prompt has been introduced with the latest Scotch Box version 3.0.

Looks like it's time to look for an alternative to Scotch Box, it was great while it lasted ... Anyone got any suggestions for a basic Vagrant LAMP with PHP 7, MySQL, etc.?

**Comment by smutek** [comment]
Confirmed. 

```
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
```

**Comment by whatnickcodes** [comment]
@smutek Can you confirm that works?

**Comment by whatnickcodes** [comment]
@gitressa 

- https://github.com/fideloper/Vaprobash
- https://laravel.com/docs/5.4/homestead
- https://puphpet.com

**Comment by gitressa** [comment]
Thanks for the suggestion, I tried entering the username and password in my Vagrantfile, and get this:
```
==> default: The machine you're attempting to SSH into is configured to use
==> default: password-based authentication. Vagrant can't script entering the
==> default: password for you. If you're prompted for a password, please enter
==> default: the same password you have configured in the Vagrantfile.
vagrant@127.0.0.1's password: 
```
I can now at least enter password and get access. But it seems like the PHP version is still 5.6.14:
```
vagrant@scotchbox ~ $ php -v
PHP 5.6.14-1+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by gitressa** [comment]
... and after `vagrant halt` I get this nasty error:

```
Stdout from the command:
Stderr from the command:

bash: line 5: /home/vagrant/.ssh/authorized_keys: Permission denied

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir -p ~/.ssh
chmod 0700 ~/.ssh
cat '/tmp/vagrant-insert-pubkey-1496238366' >> ~/.ssh/authorized_keys && chmod 0600 ~/.ssh/authorized_keys
result=$?
rm -f '/tmp/vagrant-insert-pubkey-1496238366'
exit $result

Stdout from the command:
Stderr from the command:
bash: line 5: /home/vagrant/.ssh/authorized_keys: Permission denied

 INFO interface: Machine: error-exit ["Vagrant::Errors::VagrantError", "The following SSH command responded with a non-zero exit status.\nVagrant assumes that this means the command failed!\n\nmkdir -p ~/.ssh\nchmod 0700 ~/.ssh\ncat '/tmp/vagrant-insert-pubkey-1496238366' >> ~/.ssh/authorized_keys && chmod 0600 ~/.ssh/authorized_keys\nresult=$?\nrm -f '/tmp/vagrant-insert-pubkey-1496238366'\nexit $result\n\n\nStdout from the command:\n\n\n\nStderr from the command:\n\nbash: line 5: /home/vagrant/.ssh/authorized_keys: Permission denied\n"]
```

**Comment by whatnickcodes** [comment]
I think it's a weird Vagrant thing...

I just did the same thing and am getting similar issues.

I was able to fix it by:

**Backing up my databases
Running `vagrant destroy`
Re-runnning `vagrant up`**


```
vagrant@scotchbox:~$ php -v
PHP 7.0.19-1+deb.sury.org~trusty+2 (cli) (built: May 22 2017 13:29:59) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1+deb.sury.org~trusty+2, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by gitressa** [comment]
Well, that got the version bumped up to PHP 7, but also removed more or less all the databases, only one remain now ... So not recommended, if you want to retain your projects in a working state ...

**Comment by gitressa** [comment]
Yes, well it is a vagrant virtual machine after all, and not a major problem for me. Restoring virtual machines are also a bit of a process, as far as I recall. But thanks for the suggestions (Vaprobash, etc.), I will check them out.

**Comment by samscarsella** [comment]
Adding

**Comment by samscarsella** [comment]
Adding `config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"`

**Comment by samscarsella** [comment]
adding ```
config.ssh.username = "vagrant"
    config.ssh.password = "vagrant" 
``` solved my issue

**Comment by m-eric** [comment]
> This sometimes happens with the upgrade. Try this in the Vagrantfile:

>config.ssh.username = "vagrant"
>config.ssh.password = "vagrant"

Worked for me.

This is how my Vagrantfile looks like now, if someone wants to copy/paste:
`
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.box = "scotch/box"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "scotchbox"
  config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

end
`

**Comment by alexrindone** [comment]
adding config.ssh.username = "vagrant" config.ssh.password = "vagrant" explicitly in my Vagrantfile solved my issue as well...took me an hour or two to find this. Thank you!

**Comment by peshmerge** [comment]
You don't need to do vagrant destroy. Adding config.ssh.username = "vagrant" config.ssh.password = "vagrant"  will solve the problem, but you need first to shutdown the vagrant machine and then do vagrant up.

**Comment by abuango** [comment]
Adding `config.ssh.username = "vagrant" config.ssh.password = "vagrant"` to the Vagrantfile worked for me. Thanks!

**Comment by MuneebRabaney** [comment]
adding the username and password to the vagrant file worked like a charm!! Thanks @whatnickcodes

**Comment by olvlvl** [comment]
Thanks for the tip @whatnickcodes, my authentication was broken after last MacOS security update, and I spent an hour trying way more complex solutions that did nothing. Cheers!

**Comment by rdimascio** [comment]
> Anyone got any suggestions for a basic Vagrant LAMP with PHP 7, MySQL, etc.?

Docker?

**Comment by paddy1228** [comment]
Adding `config.ssh.username = "vagrant"` `config.ssh.password = "vagrant"` to the Vagrantfile worked for me too! Thanks!

**Comment by vcttai** [comment]
This setting help me to solve the problem

> config.ssh.username = "vagrant"
> config.ssh.password = "vagrant"

Thanks so much!

**Comment by muhdazrain** [comment]
> config.ssh.username = "vagrant"
> config.ssh.password = "vagrant"

This setting saved my day! Thank you very much :)

**Comment by jeremybphillips** [comment]
> Oof... This has nothing to do with the Pro version!
> 
> This sometimes happens with the upgrade. Try this in the Vagrantfile:
> 
> ```
> config.ssh.username = "vagrant"
> config.ssh.password = "vagrant"
> ```
> 
> This happened last time:
> 
> * https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved
> * https://scotch.io/bar-talk/announcing-scotch-box-2-5#toc-debugging-the-update
> 
> Leaving this open so people can see

Worked for me!
