### ISSUE TITLE
Warning: Authentication failure. Retrying help wanted

### ISSUE THREAD

**Issue by whatnickcodes** [scotch-io/scotch-box#309]
**MAKE SURE YOU BACKUP EVERYTHING BEFORE UPDATING**

This sometimes happens with the upgrade. Try this in the Vagrantfile:

```
config.ssh.username = "vagrant"
config.ssh.password = "vagrant"
```

This happened last time. Read the old update docs:
- https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved
- https://scotch.io/bar-talk/announcing-scotch-box-2-5#toc-debugging-the-update

Leaving this open so people can see

**Comment by sjaster** [comment]
Thanks for that!

**Comment by whatnickcodes** [comment]
Getting some reports of weird update problems. The best way to update is to:

```
- Back everything up
- Destroy the box with `vagrant destroy`
- Run `vagrant box update`
- Run `vagrant up`
```
