### ISSUE TITLE
vagrant halt takes more than a minute

### ISSUE THREAD

**Issue by gitressa** [scotch-io/scotch-box#312]
After `vagrant halt` it takes more than 70 seconds for it to shut down, whereas `vagrant up` only takes 15 seconds.
- Scotchbox 3.0
- Vagrant 1.9.1
- Virtualbox 5.1.22 r115126 (Qt5.5.1)

**Comment by mohnjatthews** [comment]
Can confirm, takes quite a while. Not sure why.

**Comment by gitressa** [comment]
I just benchmarked Scotch Box 2.5:
- `vagrant up`: 25 seconds
- `vagrant halt`: 15 seconds

**Comment by whatnickcodes** [comment]
I usually just do:

```
vagrant up
vagrant suspend # this is always super fast for me
```

25 seconds is about normal I'd say - depending on your machine / power. Provisioning a server with Scotch Box features from scratch would probably take about 10 minutes

Right now, I'm unsure if the halt is related to Vagrant / Your system / Virtual Box / scotch box or something else

**Comment by whatnickcodes** [comment]
Adding to this:


``` bash

 # First time will be ~25 seconds (normal)
vagrant up

# Should be ~5 seconds (normal)
vagrant suspend 

# Should be ~5-10 seconds (normal)
vagrant up  # or "vagrant resume"

# Unknown what's happening here
vagrant halt

# Should be quick
vagrant destroy
```

**Comment by mohnjatthews** [comment]
In the grand scheme of things it's really not a massive issue. Just something to keep in mind if other time-related issues keep popping up.
