### ISSUE TITLE
Using an earlier version of Scotch Box

### ISSUE THREAD

**Issue by gitressa** [scotch-io/scotch-box#316]
I want to use version 2.5 of Scotch Box, since my project seems to not work with PHP 7. I found this page, where I got a hint as how to use an earlier Scotch Box: https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved

It states that you can put `config.vm.box_version = 2.5` in your Vagrantfile, but the version number need to be quoted, in order to work, like this `config.vm.box_version = "2.5"`.

Otherwise you'll get this error: ```an /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/box_metadata.rb:52:in `version': undefined method `split' for 2.5:Float (NoMethodError)```

**Comment by whatnickcodes** [comment]
Check this out: https://github.com/scotch-io/scotch-box/issues/202

I think 2.5.0 might work. Otherwise just reference the box URL directly

**Comment by gitressa** [comment]
Thanks for commenting and directing me to that issue, this worked fine for me:
`config.vm.box_version = "2.5"`

**Comment by whatnickcodes** [comment]
Ah, duh. Thanks
