### ISSUE TITLE
Missing PHP repo = `apt update` broken

### ISSUE THREAD

**Issue by macemmek** [scotch-io/scotch-box#318]
On fresh box:

`vagrant ssh`
`sudo apt update`

This ends with:

> W: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.

It causes problem when chaining commands while provisioning, like `sudo apt update && sudo apt upgrade`

**Comment by notflip** [comment]
+1

**Comment by wucherpfennig** [comment]
+1

**Comment by G-Rath** [comment]
This is related to #275 & #273.

I suggest for now looking at the [comment made](https://github.com/scotch-io/scotch-box/issues/275#issuecomment-318615444) by @kadimi

**Comment by whatnickcodes** [comment]
check out the update coming later today for major upgrades
