### ISSUE TITLE
Website bugs

### ISSUE THREAD

**Issue by drawcard** [scotch-io/scotch-box#319]
I think you might have missing webfonts on your site? I'm seeing a bunch of square boxes in random places.

![image](https://user-images.githubusercontent.com/1435638/26863946-a6fe7026-4b94-11e7-90c5-3379d52cacf9.png)

My specs: www.whatismybrowser.com/w/J7YTJKZ

**Comment by whatnickcodes** [comment]
I used emoji's for the icons and I don't know if your system supports the chars yet :/

**Comment by whatnickcodes** [comment]
I'll probably update it. Here's what it's supposed to look like: http://imgur.com/a/REu9z

**Comment by nternetinspired** [comment]
Emoji support in Chrome is only for OSX 10.10+

http://caniemoji.com/os-x/

**Comment by whatnickcodes** [comment]
I wonder if there's a JS detection for emoji support for fallback

**Comment by drawcard** [comment]
Cheers for the update. That's odd as I'm running the latest macOS Sierra... The "cool glasses" emoji should definately work as I use that a lot myself 😎
