### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by caterwomtious** [scotch-io/scotch-box#32]
Is it possible to access the scotch box over HTTPS rather than HTTP? My production site is all HTTPS so I need to test with that too, even if it's just a self-signed certificate.

**Comment by sean-kang** [comment]
I second this.

**Comment by ncerminara** [comment]
If you do: "vagrant share --https 443" it will create a local tunnel on a Hashicorp HTTPS server. As for self signed SSL, it's totally possible. I have never done it though

**Comment by caterwomtious** [comment]
I set it up yesterday on my dev box. Admittedly it's Windows but most of the process I followed uses openssl and Apache so is probably exactly the same:

1. Generate a certificate. I'm not sure if you can do it for an IP, but you could set it up for a hostname like 'scotchbox.local' and recommend people update their hosts file to recognise that. I used this walkthrough. http://www.neilstuff.com/apache2-ssl-windows.html

2. You can set up the HTTPS site in Apache as an additional VirtualHost, leaving the HTTP site unchanged, which means you could set it up for users to connect exactly as they do now but also have the option of connecting to the same site/folder over HTTPS.

3.I had to add the certificate to the operating system's certificate store so that it would be trusted, and not generate a warning when accessing the site in a browser. That's for the host OS though, not the scotch box, so it would just mean linking to a tutorial for each OS, and if you don't do it you can still get to the site but you get a warning first.

So I think this would be a simple and really useful change. The only problem I can see is that it's tied to a specific hostname, so multiple scotchboxes would compete for that. But you use a single consistent IP now so it's not that different. 

I'd be happy to help you work out the Apache configuration if that would be useful.

**Comment by octoxan** [comment]
@caterwomtious Would step 2 there entail just adding a new .conf file to /etc/apache2/sites-available/?

Struggling to get SSL set up on here. Entire production site uses SSL and redirects all http to https, so seems silly to have to modify my htaccess and site settings every time I pull/push.

**Comment by caterwomtious** [comment]
That was two years ago so I may have forgotten something, but I think it was all done in /apache2/extra/httpd-ssl.conf. That was Apache 2.4 and I don't remember a sites-available folder, so the setup may be different now. The lines I remember adding/enabling in httpd-ssl.conf are:

```
Listen 443

<VirtualHost mysitename.local:443>

DocumentRoot "C:/path-to-my-source-code/public_html"
<Directory "C:/path-to-my-source-code/public_html">
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

ServerName mysitename.local:443
LoadModule php5_module "C:/path-where-php-installed/php5apache2_4.dll"
AddHandler application/x-httpd-php .php

SSLEngine on

SSLCertificateFile "C:/path-to-apache-install/conf/mysitename.local.crt"
SSLCertificateKeyFile "C:/path-to-apache-install/conf/mysitename.local.key"

</VirtualHost>                
```                  

On Windows you also need to update the "hosts" file to recognise "mysitename.local" as 127.0.0.1. I think it's a similar process on Linux.
