### ISSUE TITLE
php.ini - changes don't seem to take effect

### ISSUE THREAD

**Issue by peterbournecommunications** [scotch-io/scotch-box#320]
Trying to edit the php.ini settings  (in new v3) - and they don't appear to be applied.

(Specifying an error_log location - but none showing up). 

phpinfo() also shows error_log as having no value.

Any help gratefully received.

Thanks

**Comment by whatnickcodes** [comment]
I believe the ini for PHP 7 is something like this:

```
/etc/php7.0/apache2/conf.d/user.ini
```

**Comment by peterbournecommunications** [comment]
Thanks!

/etc/php/7.0/apache2/conf.d/user.ini (added the slash before 7.0)

Did look promising - there is some config in there - but I still couldn't get it to take... even with an apache restart.

I'll try 'restarting' (halt/up) the vagrant box and see if that helps...

**Comment by whatnickcodes** [comment]
Try in `/etc/php7.0/fpm/conf.d/user.ini` or `/etc/php7.0/cgi/conf.d/user.ini`

**Comment by peterbournecommunications** [comment]
Thanks - Had a look at phpinfo() and it confirms that its running as an Apache module - and tells me where config file etc is:

Server API 	Apache 2.0 Handler
Virtual Directory Support 	disabled
Configuration File (php.ini) Path 	/etc/php/7.0/apache2
Loaded Configuration File 	/etc/php/7.0/apache2/php.ini
Scan this dir for additional .ini files 	/etc/php/7.0/apache2/conf.d 


My conf.d  file is:
display_startup_errors = On
display_errors = On
error_reporting = E_ALL
error_log = /var/www/public/php_errors.log
short_open_tag = On
opcache.enable = 0

Very strange.....

**Comment by peterbournecommunications** [comment]
Restart this time seems to have helped. 

But its definitely the: 

/etc/php/7.0/apache2/conf.d/user.ini

file to edit.

Many thanks.
