### ISSUE TITLE
Old version of wp-cli

### ISSUE THREAD

**Issue by AdamWills** [scotch-io/scotch-box#325]
Any reason why we're using such an old version of wp-cli? The version that comes pre-installed doesn't support PHP7.

**Comment by whatnickcodes** [comment]
I didn't realize that WP-CLI didn't support PHP7.

Pro has the latest version of WP-CLI but this will go out in the next update

**Comment by AdamWills** [comment]
It does - but version 0.20 which comes pre-installed, doesn't. The current version is 1.21.

**Comment by antanova** [comment]
you can go into the box using `vagrant ssh` then `sudo wp cli update --allow-root` will update it to the latest version.

**Comment by whatnickcodes** [comment]
**Check out the update coming later today for major upgrades**
