### ISSUE TITLE
Enable PHP Short Tags

### ISSUE THREAD

**Issue by ncerminara** [scotch-io/scotch-box#33]

**Comment by mattfelten** [comment]
+1

**Comment by mattfelten** [comment]
I was able to edit /etc/php5/apache2/php.ini and turned short_open_tag to On and restarted php and it worked. I'd make a pull request but I have no idea how to on this.

**Comment by alphex** [comment]
Short Tags are being deprecated... I would suggest NOT supporting them.

**Comment by mattfelten** [comment]
Perfect world, yes, it shouldn't need to be supported. Real world, there are a TON of existing sites/themes/plugins that do still use short tags. It'd be a pretty major bummer to not support it here.

**Comment by ncerminara** [comment]
I enabled them:  Run: `vagrant box update`

**Comment by ArjandeV** [comment]
So I'd like them disbaled (working with XML files through php), but when I edit user.ini or even ini_set in my index, it stays on. Any idea where I can turn it off again?

**Comment by ncerminara** [comment]
You can just do:

```
vagrant ssh
sudo vim /etc/php5/apache2/conf.d/user.ini
```

And remove: `short_open_tag = On`

**Comment by papalardo** [comment]
This work me
`sudo vagrant ssh`
`sudo apt-get update`
`sudo apt-get upgrade`
