### ISSUE TITLE
php5.6 repo source

### ISSUE THREAD

**Issue by h2ll** [scotch-io/scotch-box#331]
```
W: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
```

I just took it from the list to avoid the error, but every new box has the same problem.

Regards

**Comment by macemmek** [comment]
Already opened https://github.com/scotch-io/scotch-box/issues/318

**Comment by whatnickcodes** [comment]
Upgrade your boxes later today to have a new version. For 5.6, you'll want to use an older version of Scotch Box

https://github.com/scotch-io/scotch-box/issues/202
