### ISSUE TITLE
MYSQL database crashes after couple of weeks

### ISSUE THREAD

**Issue by csimpi** [scotch-io/scotch-box#333]
Hi!

I'm using scotchbox.io for years, I love it, but I have a big issue with it. My Mysql always crashes, then I can't 
solve the problem without vagrant destroy command. I have had a couple of major data loss because this issue.

I can't provide you too much explanation about that, because it just happens after couple of weeks using without any presage.

What am I noticed, before this is happening my CPU on 100% for minutes, than my workstation reboots. 
It happened with my PC (i7,16GB RAM) and my Alienware (2017 newest version) also, so the problem not with my hardware, I'm sure.

This is happens when I'm working, I'm sure I not changed nothing on Vagrant environment, I only change the php codes, so I can't ruin the mysql server.

Everything else is working like a charm, only the mysql dies frequently.

I've tried almost everything what is on StackOverflow to save my databases and my Vagrant environment, but I have had destroy it each times when crash happened and start everything from backups or someties from over.

> vagrant@lamp:~$ mysql -u root
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket /var/run/mysqld/mysqld.sock' (111)

**SYSLOG after vagrant up**

> Jul  5 22:00:58 lamp kernel: [   11.930564] init: mysql respawning too fast, stopped

vagrant@lamp:~$ sudo service mysql restart
stop: Unknown instance:
start: Job failed to start

**SYSLOG**
Jul  5 22:19:08 lamp kernel: [ 1102.941774] audit_printk_skb: 3 callbacks suppressed
Jul  5 22:19:08 lamp kernel: [ 1102.941778] type=1400 audit(1499285948.426:19): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/sbin/mysqld" pid=2250 comm="apparmor_parser"
Jul  5 22:19:09 lamp kernel: [ 1104.044157] init: mysql main process (2262) terminated with status 1
Jul  5 22:19:09 lamp kernel: [ 1104.044181] init: mysql main process ended, respawning
Jul  5 22:19:10 lamp kernel: [ 1104.981851] init: mysql post-start process (2263) terminated with status 1
Jul  5 22:19:10 lamp kernel: [ 1104.988611] type=1400 audit(1499285950.469:20): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/sbin/mysqld" pid=2310 comm="apparmor_parser"
Jul  5 22:19:11 lamp kernel: [ 1106.054340] init: mysql main process (2322) terminated with status 1
Jul  5 22:19:11 lamp kernel: [ 1106.054350] init: mysql main process ended, respawning
Jul  5 22:19:12 lamp kernel: [ 1107.029766] init: mysql post-start process (2324) terminated with status 1
Jul  5 22:19:12 lamp kernel: [ 1107.037071] type=1400 audit(1499285952.512:21): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/sbin/mysqld" pid=2370 comm="apparmor_parser"
Jul  5 22:19:13 lamp kernel: [ 1108.098176] init: mysql main process (2382) terminated with status 1
Jul  5 22:19:13 lamp kernel: [ 1108.098186] init: mysql respawning too fast, stopped

> vagrant@lamp:~$ sudo /etc/init.d/mysql start
> Starting MySQL database server mysqld
> ...fail!

**SYSLOG**

Jul  5 22:21:52 lamp /etc/init.d/mysql[3338]: 0 processes alive and '/usr/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf ping' resulted in
Jul  5 22:21:52 lamp /etc/init.d/mysql[3338]: #007/usr/bin/mysqladmin: connect to server at 'localhost' failed
Jul  5 22:21:52 lamp /etc/init.d/mysql[3338]: error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Jul  5 22:21:52 lamp /etc/init.d/mysql[3338]: Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
Jul  5 22:21:52 lamp /etc/init.d/mysql[3338]:

**Comment by whatnickcodes** [comment]
Some thoughts:

- Sounds like VM issue or the VM running out of memory
- Always run `vagrant suspend` before shutting down computer / when done working on project
- Never update your OS / VB / Vagrant without backing up databases
- Consider making a script to dump DB quickly before running `vagrant suspend` and a script to re-add the dump after `vagrant up`
- Consider specifying higher memory usage in your Vagrantfile  if you can or are working on a large project

**Comment by csimpi** [comment]
After hours of google-ing I got same thoughts, thank you!
Now I finally restored the corrupted innoDb database.
I added 

> innodb_force_recovery = 2

to my my.cnf file

Database is recovered well.

1. Could you give me some advice about how should I raise the memory of VM and innoDB files?

2.  Yes you are right, I should make a full db backup on provisioning, and I will add it to cron. In the most cases I working on a project for 2 months, and I never reboot my workstations or suspend VMs.

**Comment by whatnickcodes** [comment]
Ha! Thank God / congrats on getting it back.

Go here: https://box.scotch.io/common-questions/. And search "Vagrant is Slow!". Specifically: "Allow More Resources"

> Yes you are right, I should make a full db backup on provisioning, and I will add it to cron. In the most cases I working on a project for 2 months, and I never reboot my workstations or suspend VMs.

That's crazy talk to me. I try to always shutdown machine every night, but I can definitely understand where you're coming from

**Comment by whatnickcodes** [comment]
Also - if the DBs are huge, check this out on how to add storage. I've never done this before though https://github.com/scotch-io/scotch-box/issues/160
