### ISSUE TITLE
phpunit/php-code-coverage 4.0.8 requires ext-dom

### ISSUE THREAD

**Issue by notflip** [scotch-io/scotch-box#334]
It seems like ext-dom is not installed, I tried fixing it the following way:
https://github.com/scotch-io/scotch-box/issues/311

But it's still giving me that error, any idea how to fix this?

**Comment by adriangordon1231** [comment]
Sam issue

**Comment by Aretheyhappy** [comment]
https://github.com/scotch-io/scotch-box/issues/311

**Comment by notflip** [comment]
https://github.com/scotch-io/scotch-box/issues/311 Fix

**Comment by adriangordon1231** [comment]
That did not work for me. When I try to install laravel, I get the same error: 
 phpunit/phpunit 5.7.21 requires ext-dom

**Comment by adriangordon1231** [comment]
I was only able to solve the issue by manually installing the following packages: 

apt-get install libapache2-mod-php7.0 libphp7.0-embed libssl-dev openssl php7.0-cgi php7.0-cli php7.0-common php7.0-dev php7.0-fpm php7.0-phpdbg

**Comment by whatnickcodes** [comment]
I know this sucked. Check the update coming later today. Should be fixed
