### ISSUE TITLE
How do i downgrade my box back to php 5.6?

### ISSUE THREAD

**Issue by sprov03** [scotch-io/scotch-box#335]
My box crashed twice and the same week after running like a champ for a year.
I figured i would update it since it was telling me to update. As soon as i did i cant get any of my tests to run because my setup was with php 5.6. I downloaded php 5.6 and mcrypt and restarted apache but i still the the error that mcrypt is not installed.

**Comment by notflip** [comment]
I think you can just 

    vagrant box add scotch/box -–box-version 2.5

(untested)

**Comment by StyxOfDynamite** [comment]
Better fix would be to specify the box version in the Vagrantfile

`config.vm.box_version = "2.5"`
