### ISSUE TITLE
Mongo DB module error

### ISSUE THREAD

**Issue by HashandSalt** [scotch-io/scotch-box#336]
I've been getting an intermittent error from a few sites i'm running on Vagrant Pro 3.

`PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mongo.so' - /usr/lib/php/20151012/mongo.so: cannot open shared object file: No such file or directory`

The sites do not even need this library (they are powered by Kirby CMS and not using a database of any kind). I have checked that folder via SSH and the `mongo.so` file is missing but there is a `mongodb.so` file.

Any idea how to fix it? I have run server updates via `apt` on every provision, so the box is up to date and not the same as the released box. Could this have caused the problem?

**Comment by paulpullen** [comment]
I was getting this on a new Scotch-Box Pro box; it seems the `mongodb.so` extension is the correct extension (and is loaded properly), but in /`etc/php/7.0/apache2/conf.d/user.ini`,  `mongo.so` (the older, now deprecated extension) is referenced, and this generates the startup warning as that file doesn't exist.

Commenting out the following line in that `user.ini` file fixed it for me:
`# extension = mongo.so`

**Comment by HashandSalt** [comment]
Thanks. see if that does the trick.

**Comment by jordanboston** [comment]
Thanks, that fixed it!

**Comment by whatnickcodes** [comment]
Oh, sorry about this. I am removing that from the build scripts.

It's part of a major update coming later today
