### ISSUE TITLE
provisioning pro version with build script: grub interactive dialogue problem

### ISSUE THREAD

**Issue by grahamtk** [scotch-io/scotch-box#338]
Hi! 
I meet this issue with the non-interactive build script being halted by the interactive setup dialogue for grub:
As described here:
https://www.bountysource.com/issues/37968311-ubuntu-grub-pc-forces-non-interactive-apt-get-upgrade

Also seems nginx does not start. Ill create a new issue if the grub issue does not resove that. 

Can I get some help on how to proceed with this? 
Best regards, 
Øyvind.

**Comment by whatnickcodes** [comment]
It's because of this. Just swap this for provisioning

```
# The following is "sudo apt-get -y upgrade" without any prompts
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade

```
