### ISSUE TITLE
Missing PHP7

### ISSUE THREAD

**Issue by giodum** [scotch-io/scotch-box#339]
Hello everyone, I recently installed ScotchBox 3.0 (free version) with clone instructions:

```git clone https://github.com/scotch-io/scotch-box my-project```

I need this Vagrant machine in order to work with Drupal8, but while I was installing drupal I noticed that my current version of php is not the latest. The result of `php -v` is:

```
PHP 5.6.14-1+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```
I can't find PHP7 neither in `/bin/`nor in `/usr/bin`. Moreover if I try to install it via `sudo apt-get install php7` there are no elements listed in the repository.

In the main info page of scotch box it is clear that Php v7.0 is provided. Is it normal I can't find it?
How can I solve the problem? How can I install and enable it? Or should I install a new version of sctochbox?

Thank you,

Giorgio

**Comment by urbankid** [comment]
Can it be that you need to manually update the vagrant scotch-box box?
Try running `vagrant box update` and `git clone ...` again

**Comment by giodum** [comment]
Thank you very much, it worked! I had to update the vagrant box too.

**Comment by denizdogan** [comment]
I have the reverse problem... PHP 7.0 is installed and enabled, but I needed 5.6. I haven't updated or changed anything myself. I thought only the Pro version came with PHP7? Are there any instructions on how to downgrade to 5.6?
