### ISSUE TITLE
Add "unzip"

### ISSUE THREAD

**Issue by techninja** [scotch-io/scotch-box#34]
A pretty common package, often used for automated builds when pulling packaged libraries. Was pretty surprised not to see it already there.

**Comment by vanderb** [comment]
It should definitively insert into box by default.
Meanwhile you could install it manually:

sudo apt-get update
sudo apt-get install unzip

**Comment by techninja** [comment]
Yep, that's what I did. Should have documented it here, thanks.

**Comment by ncerminara** [comment]
Run: `vagrant box update`
