### ISSUE TITLE
SimpleXML not available

### ISSUE THREAD

**Issue by mfisher31** [scotch-io/scotch-box#341]
Hi I'm using scotchbox v3 and even though phpinfo() is telling me that SimpleXML is available, when I run:

`class_exists('SimpleXMLElement');`

It returns false and I can't use the library.  Isn't SimpleXML supposed to be part of PHP?

**Comment by whatnickcodes** [comment]
https://github.com/scotch-io/scotch-box/issues/311

Check this out. Bug in 3.0


This works out of box in Pro 1.0.0

**Comment by whatnickcodes** [comment]
Going to close this per the other issue
