### ISSUE TITLE
Can't enable SOAP

### ISSUE THREAD

**Issue by marcelo2605** [scotch-io/scotch-box#348]
These are the files I've changed:

/etc/php/7.0/apache2/php.ini (remove semicolon before extension=php_soap.dll)

/etc/php/7.0/apache2/conf.d/user.ini (adding extension=php_soap.dll)

After restart Apache, nothing happens: the Soap not appear in `phpinfo()`

**Comment by TonyBrownDev** [comment]
@marcelo2605, I can confirm. I am attempting to load Magento 1.9.3.7 (which requires SOAP). I have updated the same files as you and ran the following commands:

service apache2 restart
service php7.0-fpm restart

Nothing appears to be working.
