### ISSUE TITLE
OctoberCMS on SB Pro 3, create new administrator error

### ISSUE THREAD

**Issue by andreasottosson** [scotch-io/scotch-box#358]
I´m getting this error when using OctoberCMS on Scotch Box Pro 3.0. Is it missing the php-xml extension?

"Class 'DOMDocument' not found" on line 465 of /var/www/public/vendor/erusev/parsedown-extra/ParsedownExtra.php

**Comment by andreasottosson** [comment]
php-xml extension is not missing btw..

**Comment by johnstephens** [comment]
I'm getting the same error when I use Parsedown Extra. I had it working on all my scotch-box instances recently, but I had to include the following in my boostrap file:

    sudo apt-get update
    sudo apt-get upgrade
    sudo apt-get install php7.0-xml

Now it doesn't work at all. :(

**Comment by andreasottosson** [comment]
No solution to this? It works fine using MAMP...

**Comment by lzomedia** [comment]
i had the same issue ended up by reinstalling the XML library

**Comment by johnstephens** [comment]
@lzomedia, how did you do that?

Like I said, I tried running `sudo apt-get install php7.0-xml` and that does not resolve the issue for me.

**Comment by johnstephens** [comment]
@andreasottosson, I was able to resolve this by downgrading scotch/box to version 2.5.

Simply add `config.vm.box_version = "2.5"` to the Vagrantfile, and verify that the bootstrap file installs php7.0-xml:

```
sudo apt-get update
sudo apt-get install php7.0-xml
sudo service apache2 restart
```

**Comment by johnstephens** [comment]
@andreasottosson: And, this works for me using scotch/box 3.0:

```
## Add PHP-XML support
 #

sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get -y install php7.0
sudo apt-get -y install php-xml php7.0-xml
sudo apt-get -y install php-mbstring
sudo apt-get -y install libapache2-mod-php7.0 libphp7.0-embed libssl-dev openssl php7.0-cgi php7.0-cli php7.0-common php7.0-dev php7.0-fpm php7.0-phpdbg
sudo service apache2 restart
```

**Comment by andreasottosson** [comment]
@johnstephens Thank you soo much! I will try this and see if it works for me.

**Comment by whatnickcodes** [comment]
I know this has sucked for everyone! This is like the 5th issue on it.

I'm pushing a major update today. So this will be resolved OOB
