### ISSUE TITLE
Give less recourses to VirtualBox

### ISSUE THREAD

**Issue by ViliusG** [scotch-io/scotch-box#362]
Hello.

I have this Asus X200MA which is quite old and not so powerful. I have Ubuntu operating system on it.

After installing virtual box i clone the git repository of scotchbox and try to do vagrant up.

Almost every time I do that my computer freezes. Ir rare occasions, when it doesn't I'm left with big lag all the time. I've notices that running vagrant up automatically creates a virtual box.

My question is is it possible to set the recourses I want to dedicate for the virtual box? Maybe that would solve the problem.

One of the errors I keep getting: remote connection disconect

**Comment by whatnickcodes** [comment]
```
config.vm.provider "virtualbox" do |v|

    v.memory = 300
    v.cpus = 1

end
```

You can pick and choose your settings like this.
