### ISSUE TITLE
Speed! I know I know

### ISSUE THREAD

**Issue by latwelve** [scotch-io/scotch-box#363]
I've toyed with Scotchbox before as well as other Vagrant offerings but keep going back to XXAMP and then get frustrated when it has hissy fits occasionally so I'm back looking at boxes!

Is it just my system that finds scotchbox and other docker or vagrant options slower than say a digital ocean wp install!? surely being local on a 16gb ram system with an i5 chip should have a blazing fast experience?

I feel I'm stupidly missing something.. I tried the speed up tricks on your site to no avail :(

**Comment by slibbe** [comment]
I would say that Scotchbox is fast enough; what may be a difference is that whenever dealing with big files I use the commandline. 
The only thing that hopefully some day is gonna work better is using WSL assuming you are in Windows 10. Til that day I enjoy Scotchbox and Vagrant.

**Comment by whatnickcodes** [comment]
Don't go back to XXAMP!
