### ISSUE TITLE
vagrant up keeps failing.

### ISSUE THREAD

**Issue by eeyon** [scotch-io/scotch-box#364]
i have to include a screenshot because i have no idea what the heck is going on. appears to have some issues with grub.

![screen shot 2018-01-13 at 6 06 07 pm](https://user-images.githubusercontent.com/3076075/34912096-83b55efe-f88c-11e7-84d0-4bff3d3d201a.png)

any ideas on a work around so i can get a box up and running?

**Comment by mizner** [comment]
Having the exact same problem

**Comment by whatnickcodes** [comment]
Can you guys get any other Vagrant box working?

**Comment by whatnickcodes** [comment]
It's because it's trying to pop open an interactive screen.

REplace with: `DEBIAN_FRONTEND=noninteractive sudo apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade`


https://github.com/chef/bento/issues/661

**Comment by whatnickcodes** [comment]
Also updating the Scotch Box Build Scripts soon with this fix. It's ugly but effective
