### ISSUE TITLE
Not receiving debug connection from xdebug.

### ISSUE THREAD

**Issue by jendo** [scotch-io/scotch-box#366]
Hello, I am not able to debug my code using your virtual box and phpstorm. Did you try it ? Maybe i am doing something wrong. :(

My xdebug.ini: 
zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_connect_back=1
xdebug.remote_port=9000
xdebug.remote_host=192.168.33.1
xdebug.remote_log=/tmp/xdebug.log
xdebug.idekey="PHPSTORM"

My xdebug.log log:
Log opened at 2018-02-05 12:05:17
I: Checking remote connect back address.
I: Checking header 'HTTP_X_FORWARDED_FOR'.
I: Checking header 'REMOTE_ADDR'.
I: Remote address found, connecting to 192.168.33.1:9000.
E: Time-out connecting to client. :-(
Log closed at 2018-02-05 12:05:17

I spent hours to get it work but unsuccessfully.  Thanks for any advice.

**Comment by jendo** [comment]
Can help me anyone ?

**Comment by whatnickcodes** [comment]
Try these

https://github.com/scotch-io/scotch-box/pull/281
https://github.com/scotch-io/scotch-box/issues/244
https://github.com/scotch-io/scotch-box/issues/90
https://github.com/scotch-io/scotch-box/issues/7
https://rocinantesoftware.blogspot.com.es/2015/07/phpstorm-xdebug-scotchbox-20.html
