### ISSUE TITLE
404 https://atlas.hashicorp.com/scotch/box

### ISSUE THREAD

**Issue by GavinJaynes** [scotch-io/scotch-box#367]
Hi - when installing ( vagrant up ) I get the following error: 

The box 'scotch/box' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/scotch/box"]
Error: The requested URL returned error: 404 Not Found

Please help - much appreciated

**Comment by temp1029** [comment]
Getting the same thing here but on Pro version.  Didn't see an issue there so tacking it onto this one here.

**Comment by whatnickcodes** [comment]
Looks like Vagrant Cloud bug

But it looks like Vagrant people are killing off the atlas.hashicorp domain and it's causing Hell for everyone.

For example, this is the URL you want: https://app.vagrantup.com/scotch/box


This is the direct link:

https://app.vagrantup.com/scotch/boxes/box/versions/3.0/providers/virtualbox.box

**Comment by whatnickcodes** [comment]
Jeeze:

Here's a work around: https://github.com/hashicorp/vagrant/issues/9442#issuecomment-363080565

**Comment by whatnickcodes** [comment]
Also for anyone else.

Maybe just destroy and delete all boxes. Remove Vagrant completely, install latest version...

**Comment by geckoseo** [comment]
All I did was add the box again manually using the new location and it flushed out the old meta..

I didn't even need to shut the machine down first, and when I reloaded it the errors were gone.

**Comment by jayhill90** [comment]
Adding V`agrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')` to the Vagrantfile works.
