### ISSUE TITLE
Custom Post Types and Customizer panels not available on local install of Jetpack

### ISSUE THREAD

**Issue by johnpitchko** [scotch-io/scotch-box#373]
_I previously opened issues with (WPDistillery)[https://github.com/flurinduerst/WPDistillery/issues/73] and with [Jetpack](https://github.com/Automattic/jetpack/issues/9104), but I closed them as I believe the issue is now with Scotchbox (see below)._

Hello, just did two clean installs of WPDistillery and enabled Jetpack in Development Mode (so no connection to Wordpress.com). I then enabled the two built in custom post types (CPTs) in Jetpack (Portfolio and Testimonials). Activation appears to work okay, but the post types do not appear in the Admin screen, or in Settings > Writing. I am using Independent Publisher 2 theme (which adds the Content Options panel to Customizer).

No idea if the issue is with WPDistillery, Scotchbox, or Jetpack, but opening a low priority issue to do some testing and to ask if anyone else can replicate this issue.

![missing-content-options-panel](https://user-images.githubusercontent.com/7190681/37748377-3c1ded6c-2d49-11e8-858b-2c79632e73c0.png)
![missing-portfolios-panel](https://user-images.githubusercontent.com/7190681/37748378-3c354692-2d49-11e8-9567-df704093f690.png)

The issue is not related to my custom theme. I switched to a different theme (Argent), which is listed to be compatible with Jetpack Portfolios, and encountered the same issue.

Other custom post types are allowed. I installed the CPT UI plugin and created my own dummy custom post type through Wordpress admin. It displays correctly in the admin bar after creation.

I manually copied the register_custom_post_type() function for the jetpack-portfolio custom post type from Jetpack and ran it manually in my functions.php. The Portfolio post type did appear in the admin bar.

## Latest

The good news is that I installed (VCCW)[http://vccw.cc/], which is another pre-configured Wordpress dev environment for Vagrant, installed Jetpack, and enabled Portfolios custom post type. Portfolio is now available on the nav bar! Also, Content Options is available in the Customizer when using my custom theme!

Bad news means that this issue appears then to be with Scotchbox.

![customizer-vccw](https://user-images.githubusercontent.com/7190681/37748447-7fd68e88-2d49-11e8-9b91-939fd3b8ef79.png)
![jetpack-vccw](https://user-images.githubusercontent.com/7190681/37748448-7fedc922-2d49-11e8-92d3-e29abeb74340.png)

**Comment by whatnickcodes** [comment]
Weird... Can you turn on PHP errors (like absolutely force them on and track down what is breaking?

My gut says PHP version is causing some pain here

**Comment by johnpitchko** [comment]
I'll certainly try! Not sure the best way to do it but will use some Google-fu.

According to phpinfo(), I am using version 7.0

![scotchbox-phpinfo](https://user-images.githubusercontent.com/7190681/37778103-bb3bed5a-2dae-11e8-9cb1-82355f2dce10.png)

**Comment by flurinduerst** [comment]
@johnpitchko see https://codex.wordpress.org/Debugging_in_WordPress for WP-options on PHP-Errors and http://php.net/manual/en/function.error-reporting.php for general PHP-Error reporting

**Comment by johnpitchko** [comment]
Thanks @flurinduerst 

Debugging enabled in wp-config.php:
```
define('WP_DEBUG', true);

/* That's all, stop editing! Happy blogging. */

define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
define( 'JETPACK_DEV_DEBUG', true );
```

Debugging enabled in /etc/php/7.0/apache2/php.ini:
```
error_reporting = E_ALL
display_errors = On
log_errors = On
error_log = /var/log/php_errors.log
```

Are these correct/valid for Scotchbox?
