### ISSUE TITLE
Does scotchbox cache wordpress?

### ISSUE THREAD

**Issue by TomLewis** [scotch-io/scotch-box#379]
Im trying to develop a theme locally on a plane install of scotch box, I don't use any cache plugins. but most of the times my changes are not reflected live. Even with a browser cache reset/incognito.

For instance, I just installed a plugin called "img-responsive for Bootstrap" to add the bootstrap img-fluid class to all images as im developing with bootstrap. it didnt work, I reset the box, didnt work, I assumed it was broken, tried a HELL of a lot of other alternatives nothing was working. gave up.

Today I start vagrant and its just worked! What is going on, is there some form of cache in scotchbox, how do I disable it?

**Comment by whatnickcodes** [comment]
Are you on Pro? It's PHP OPCache, just disable

**Comment by TomLewis** [comment]
No im not on pro, just using the free version. how do I disable OPCache?
