### ISSUE TITLE
Provisioning instead of baked-in box.

### ISSUE THREAD

**Issue by thibmaek** [scotch-io/scotch-box#39]
Isnt it smarter to install some dependencies over provisioning with Bash or Chef instead of baking everything in and having to update the box time and again?

**Comment by ncerminara** [comment]
It's a lot smarter. That's not the point of Scotch Box though. Scotch Box is aimed to beginners and for basic LAMP applications. Scotch Box is Chef and Puppet ready. You can also use Vagrant to run shell commands.

You might have missed this:

> Scotch Box is a preconfigured Vagrant Box with a full array of LAMP Stack features to get you up and running with Vagrant in no time.

> A lot of PHP websites and applications don't require much server configuration or overhead at first. This box should have all your needs for doing basic development so you don't have to worry about configuring Vagrant and you can simply focus on your code.

> No provisioning tools or setup is really even required with Scotch Box. Since everything is packaged into the box, running "vagrant" is super fast, you'll never have to worry about your environment breaking with updates, and you won't need Internet to code.
