### ISSUE TITLE
Unable to set date.timezone.

### ISSUE THREAD

**Issue by JustinTBrown** [scotch-io/scotch-box#399]
Similar to issue #391, I'm unable to correctly set `date.timezone`.

I've edited both `/etc/php/7.0/apache2/php.ini` and `/etc/php/7.0/apache2/conf.d/user.ini` with `date.timezone = America/Edmonton`, but `phpinfo()` shows "no value" for timezone.

Any ideas?

**Comment by kenef** [comment]
What does phpinfo() say for php.ini file location? You might want to try editing the date.timezone in /etc/php/7.0/cli/php.ini

Cheers.

**Comment by JustinTBrown** [comment]
@kenef That worked. Many thanks!
