### ISSUE TITLE
Install SQLite

### ISSUE THREAD

**Issue by florianletsch** [scotch-io/scotch-box#40]
I get the following error when trying to use sqlite from php. Seems like the pdo sqlite driver is missing. I guess that should be added. 

`"Uncaught exception 'PDOException' with message 'could not find driver`

Local fix:

```bash
vagrant ssh
sudo apt-get update
sudo apt-get install php5-sqlite
sudo service apache2 restart
```

**Comment by ncerminara** [comment]
Renamed this and will install with the next update

**Comment by ncerminara** [comment]
Done! Run: `vagrant box update`
