### ISSUE TITLE
Unable to download scotch box

### ISSUE THREAD

**Issue by mohankumaranna** [scotch-io/scotch-box#41]
On trying to download scotch box, I get following error. (my internet speed is 512 kbps max).  I am not sure on what I am missing. Appreciate your suggestions.  [ vagrant version is 1.7.2, virtual box version is 4.3.22 r 98236, OS is Windows 8.1, I have Laravel Homestead box, it is working]

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'scotch/box' could not be found. Attempting to find and install
...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'scotch/box'
    default: URL: https://atlas.hashicorp.com/scotch/box
==> default: Adding box 'scotch/box' (v1.0.2) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/scotch/boxes/box/versions/
1.0.2/providers/virtualbox.box
    default: Progress: 11% (Rate: 56588/s, Estimated time remaining: 3:38:16)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054

**Comment by ncerminara** [comment]
The server is live! Let me know if you keep having this issue. I might be able to get you a Dropbox link to manually download it.

**Comment by mohankumaranna** [comment]
Thanks.  I will retry and let you know if experience any problem.

**Comment by kylegalloway** [comment]
I'm having the same problem... Horrible internet connection. I'll try again tomorrow with a better connection to see if that helps.

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'scotch/box' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'scotch/box'
    default: URL: https://atlas.hashicorp.com/scotch/box
==> default: Adding box 'scotch/box' (v1.0.2) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/scotch/boxes/box/versions/1.0.2/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
    default: Progress: 0% (Rate: 0/s, Estimated time remaining: 12:50:26)3)))
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054
