### ISSUE TITLE
Add ability to test email functionality using something like mailCatcher

### ISSUE THREAD

**Issue by pythonic1** [scotch-io/scotch-box#42]
Currently it appears that nothing happens when my app attempts to send out emails.

http://mailcatcher.me/ seems like a great way to test email functionality in development and could be a great addition to scotch-box

**Comment by mikecrittenden** [comment]
https://github.com/mailhog/MailHog is another option that is easier to install.

**Comment by agarzon** [comment]
+1

**Comment by maxpou** [comment]
+1 !

If you want to install it manually :
`gem install mailcatcher`

In your php.ini file (/etc/php5/apache2/php.ini add this line sendmail_path) add this : `sendmail_path = /usr/bin/env catchmail`.
If don't work, install Mailcatcher Dependencies (sqlite, ruby)
`sudo apt-get install -y libsqlite3-dev ruby1.9.1-dev`

**Comment by ncerminara** [comment]
ADDED! https://scotch.io/bar-talk/announcing-scotch-box-2-5#using-mailcatcher
