### ISSUE TITLE
the php version need be update to 7.4

### ISSUE THREAD

**Issue by ahkkud** [scotch-io/scotch-box#425]
After run the WPDistillery, go to the Wordpress admin page, there is a notification like this：

<img width="748" alt="Screenshot 2021-12-04 at 23 43 19" src="https://user-images.githubusercontent.com/7379351/144716019-69efff14-91cb-422a-a016-8b41c1bc584c.png">

hope someone can help to update the php version settings

cheers~

**Comment by reddingwebpro** [comment]
@zhangyangsk8 - Nick has abandoned this product, I'd like to direct you to my variation called Cognac box which is a much more current version based on supported versions of Ubuntu, PHP and Vagrant. You can find at: https://github.com/reddingwebpro/cognacbox
