### ISSUE TITLE
Create an Update Policy

### ISSUE THREAD

**Issue by Glutnix** [scotch-io/scotch-box#47]
(many assumptions were made in the writing this, please educate me where I assumed falsely, and thanks for reading and understanding)

While Scotch Box is a very lightweight set of tools, knowing it is maintained and maintained well is key to it competing with and replacing XAMPP, WAMP and MAMP. 

The Scotch Box image is supposed to be updated rarely in order to not break with Vagrant or VirtualBox.

I also know that because it's built on an open stack, and on Ubuntu, updating packages inside the box is an achievable task to leave to the user, but must be done manually, and regularly, and must remember to do `apt-get update`, `composer global update` and `npm -g update`, and others that I can't think of.

Right now the Scotch Box image hasn't been updated for five months. This is most likely by design, but to the outsider and beginner this may seem like a long time in terms of security and software updates, and makes me wonder if the project is abandoned, and if or when the image might be updated.

**I propose a project policy to when Scotch Box's image should be updated by maintainers**, in order to build trust among those who want to rely upon it. To help explain that 5+ months without updates is by design, trust us, we know what we're doing.

When will Scotch Box's image be updated? Why should it be updated? Under what circumstances? When new versions of dependant software (VirtualBox, Vagrant, Ubuntu, PHP, Apache, MySQL, Node JS, etc?) are released? When security updates are released? Only when things break? Every six months no matter what? When are users expected to update the internals themselves?

Who needs this? Individuals who run a different Scotch Box for each project they maintain. Teachers who want to recommend Scotch Box as a perfect VM for beginners to web design and development.

**Comment by ncerminara** [comment]
Thanks for posting this here vs Twitter - very thorough. I'll create an update policy.

The beauty of this is anyone using Puppet or Chef via Vagrant can add or provision updates whenever necessary without worrying about the base box. I should have an update policy for the base box though since that kills off the point of simplicity.

What do you recommend for schedule / timeline?

**Comment by Glutnix** [comment]
I don't know what kind of schedule it should have. I don't want maintaining the project to be onerous for your or anyone, nor us users; the more demanding the schedule, the more likely maintenance will slip, for both the image makers and the image users.

In contrast, Laravel Homestead is only 11 months old (April 16 2014) and has updated 15 times, updating dependancies and packages numerous times, including moving to PHP 5.6, MySQL 5.6, Postgres 9.4 and HHVM.
https://vagrantcloud.com/laravel/boxes/homestead

(2¢) Every three months feels like a sweet spot for keeping it up to date, but it could be less frequent, but I feel no more than 6 months should pass between updates.

**Comment by ncerminara** [comment]
Not as detailed as you'd probably like, but https://scotch.io/bar-talk/announcing-scotch-box-2-5#update-policy-and-the-future-of-scotch-box

Also, we'll eventually phase out in favor of Otto

**Comment by Glutnix** [comment]
This is actually great. Nice work by the way!

**Comment by sidspyker** [comment]
So now that Otto is gone and last Scotch update is 12 months old... are there any plans?
