### ISSUE TITLE
[question] Is scotch-box using DEFAULT or NSF sharing?

### ISSUE THREAD

**Issue by alphex** [scotch-io/scotch-box#49]
Is scotch-box using DEFAULT or NSF sharing?

**Comment by ncerminara** [comment]
Default.

You can add NSF easily: http://docs.vagrantup.com/v2/synced-folders/nfs.html

**Comment by ncerminara** [comment]
Here's how to add it by the way: 

`config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }`
