### ISSUE TITLE
can't connect mysqlworkbench

### ISSUE THREAD

**Issue by ferminako** [scotch-io/scotch-box#51]
Hello i'm trying to connect to mysql to create new database tables etc... using mysqlworkbench but when I do it  I get Can't connect to MySQL server on '127.0.0.1' (61)

I'm using:
Database Name	scotchbox
Database User	root
Database Password	root
Database Host	127.0.0.1
Host Port 3306

**Comment by ncerminara** [comment]
You have to use SSH forwarding in order to connect.

**Comment by ncerminara** [comment]
Also check this thread: https://github.com/scotch-io/scotch-box/issues/38

**Comment by tucq88** [comment]
It seems like scotch-box doesn't allow portforwarding right ? I want to allow remote access to MySQL but no luck. Could you confirm or suggest a way to achieve that, @whatnickcodes ?

**Comment by whatnickcodes** [comment]
It definitely should. I do:

https://box.scotch.io/database-logins.jpg
