### ISSUE TITLE
Cannot connect to scotchbox after installing Lavarel Homestead

### ISSUE THREAD

**Issue by 19eighties** [scotch-io/scotch-box#53]
How can I get my scotchbox to ce-exist with Lavarel Homestead? I am also trying to understand how it would interfere with the scotchbox install. Thanks.

**Comment by ncerminara** [comment]
They're separate VM's. You might be running into issues where something is breaking when you run both of them at the same time.

**Comment by 19eighties** [comment]
I was not running both at the same time.
