### ISSUE TITLE
32-bits version

### ISSUE THREAD

**Issue by victorleal** [scotch-io/scotch-box#54]
A 32-bits version would be useful,regarding there are some computers which don't support 64-bits VMs.

Beside it, the installation makes a configuration about using VT-X technology which also some computers don't support. I spent some time until find that I had to disable this option.

**Comment by ncerminara** [comment]
Hey victorleal. Unfortunately I don't have plans to support a 32-bit version. You can easily create your own box here https://scotch.io/tutorials/how-to-create-a-vagrant-base-box-from-an-existing-one or with packer.io
