### ISSUE TITLE
Using NFS for synced_folder fails with incorrect IP

### ISSUE THREAD

**Issue by mikecrittenden** [scotch-io/scotch-box#55]
If I edit the Vagrantfile and set `type: "nfs"` then I end up with this error when running `vagrant up` the first time:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'dmode=777,fmode=666' 192.168.33.1:'/Users/mcrittenden/Documents/Code/scotchbox1' /var/www

Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: an incorrect mount option was specified
```

As you can see, it's trying to use `192.168.33.1` instead of `192.168.33.10` which will obviously fail. Seems like a simple typo somewhere in the box?

Here's my full Vagrantfile, just in case:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "scotch/box"
  config.vm.network "private_network", ip: "192.168.33.33"
  config.vm.hostname = "scotchbox"
  config.vm.synced_folder ".", "/var/www", type: "nfs", :mount_options => ["dmode=777", "fmode=666"]

end
```

**Comment by ncerminara** [comment]
Hey Mike

I think your syntax is wrong. You should do:

`config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }`

I think I'll bake this in to be default in Vagrantfile.
