### ISSUE TITLE
Can't connect to MySQL server on 'localhost'

### ISSUE THREAD

**Issue by andrewrice** [scotch-io/scotch-box#56]
First off, great tool! I was able to setup everything on my Macbook in < 5 minutes. 

However, I'm running into an issue trying to connect to the database on Windows using the HeidiSQL client:

![image](https://cloud.githubusercontent.com/assets/3012015/7339981/afb17016-ec4f-11e4-94f3-393ba4aa0f48.png)

Below are my connection settings:

![image](https://cloud.githubusercontent.com/assets/3012015/7339986/fb7a9108-ec4f-11e4-8ef3-269435468462.png)

![image](https://cloud.githubusercontent.com/assets/3012015/7339974/81499c4e-ec4f-11e4-8b7c-3c5eb8b41903.png)

I've double checked my passwords:

*MySQL:* root/root
*Vagrant:* vagrant/vagrant

Any idea why this isn't working out-of-the-box for me?

Thanks!

Andrew

Edit: 
I should note that I'm able to access the IP in the browser so the web server seems to be working, at least. Also, the mysql service is running when I SSH into the vagrant box.

**Comment by andrewrice** [comment]
I've tried it with port 22 on the SSH Tunnel tab as well.

**Comment by andrewrice** [comment]
Cross-posted to StackOverflow: http://stackoverflow.com/questions/29885693/cant-connect-to-vagrant-using-heidisql-cant-connect-to-mysql-server-on-loca

**Comment by ncerminara** [comment]
Just commented something for you to try.

Can you verify you can SSH into the box with `vagrant ssh` or verify somehow your vagrant ssh credentials are correct. You can run `vagrant ssh-config`.

If you can SSH into the box that helps resolve reveal some things. If you're SSH'd into the box, can you then try and connect to the database via mysql from the command line: `mysql -u root -p`

**Comment by ncerminara** [comment]
Also, I would suggest trying a different database client like http://www.navicat.com/.

**Comment by andrewrice** [comment]
@ncerminara Nicholas, thanks for you reply! I love the package, and I appreciate the time you have put into producing it and providing support.

I can confirm I'm able to ssh into the vagrant box, and I'm able to connect to MySQL via the command line in SSH.

I'll try connecting again using Navicat when I get home.

Thanks again for your reply and keep up the great work :)

**Comment by ncerminara** [comment]
Try connecting instead with the SSH key via the settings in `vagrant ssh-config` versus the user:password

**Comment by andrewrice** [comment]
@ncerminara It works with Navicat.... really strange! Thank you for your help. I wonder if any other HeidiSQL users have experienced the issue.

**Comment by ncerminara** [comment]
Super weird. I'm going to close this since it seems to be a config issue with HeidiSQL.

BTW: Before going getting a Mac and having access to Sequel Pro, I was a huge fan of Navicat for doing database stuff (vs say Heidi). Hopefully it works the same for you in the future.

**Comment by andrewrice** [comment]
For what it's worth, updating HeidiSQL to 9.1 resolved the issue. I'll still give Navicat a whirl though and see if I prefer it :)

**Comment by davidshq** [comment]
FYI, found this: https://laracasts.com/forum/?p=1729-a-guide-for-connecting-to-vagrant-mysql-db-using-heidisql-in-wi/0

It is still occurring in 9.3.

**Comment by acrolink** [comment]
It is a timeout issue, just increase it.

**Comment by rlax** [comment]
Same problem with _9.3 build 5109_, up-to-date as i wrote this.
When i set plink timeout to 20, this problem solves itself.

**Comment by ghabxph** [comment]
Hello, instead of 192.168.33.10, why not try 127.0.0.1 instead. It works for me.
