### ISSUE TITLE
Host networking

### ISSUE THREAD

**Issue by thespotvin** [scotch-io/scotch-box#60]
Hi there - I'm using scotchbox (and love it) except during the Wordpress install I see an error regarding networking from the guest machine. When I `vagrant ssh` in, I am only able to ping external devices by IP.

My specific situation is installing Wordpress - it complains at the initial install that it cannot communicate with wordpress.org.

Is there a workaround for this that I've missed?

Thanks!

**Comment by ZacheryPD** [comment]
It works on mine, have you tried destroying and re-running vagrant up?

**Comment by thespotvin** [comment]
I had tried that - but this morning I'm seeing that all my vagrant boxes suffer from the same thing. Thanks!
