### ISSUE TITLE
Recurring issue with chmod when ssh'd

### ISSUE THREAD

**Issue by groovenectar** [scotch-io/scotch-box#61]
I've run into a few problems with file permissions when SSH'd into Scotch Box. A web application might complain that directories are not writable.

So I `chmod -R 755 directoryname` while SSH'd. Now, this has no effect when I list the files -- the permissions stay the same. However, outside the box, when I exit SSH, the permissions would take.

But the webserver still can't write to it. The only fix I could find so far is to change Apache to run as `vagrant:vagrant`. Would it make sense to have that as the default? Surely I'm not the only one who's run into this.

Further, since I can't `chmod` files while SSH'd in the box, it's not possible to change a file to make it executable, if it needs to be run from within the Vagrant instance...

Edit: I can `chmod +x filename.sh` while SSH'd, but again, that doesn't take while SSH'd. It does take outside the instance, and from there it can be executed. But it looks like from within Scotch Box it keeps the 666 file permissions no matter what, so the file won't run while in an SSH session :-(

**Comment by ncerminara** [comment]
UPDATED! Run `vagrant box update`

**Comment by audstanley** [comment]
Same issue here. "vagrant box update" didn't work.

**Comment by ncerminara** [comment]
Re-opening and will look into

**Comment by groovenectar** [comment]
Sorry for not adding feedback before, I think this is the way I had worked around it in the Vagrantfile but I'm not sure whether it's an ideal route:

    # Default user:group for shared folder if not specified is vagrant:vagrant
    config.vm.synced_folder ".", "/var/www", owner: "www-data", group: "vagrant", :mount_options => ["dmode=777", "fmode=774"]

**Comment by dsikkema** [comment]
Having the same issue. Just ran update, says I'm on latest version. Can't chmod files that are under the shared directory (var/www).

**Comment by dxvargas** [comment]
Still not working (v2.5).
Tried @groovenectar without luck.

**Comment by XedinUnknown** [comment]
Basically, I need to execute an install script in the mounted directory while inside the VM. But apparently, by design, it is not possible to change permissions for shared (i.e. mounted) files. So, the question for me is: how can I run scripts in the mounted directory inside the VM without making all the shared files executable via `fmode=777`?

**Comment by veganista** [comment]
Try uncommenting ( remmeber to comment out the previous one ) in the vagrant file:

    config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

I've found that this fixes a number of permission problems for me on both Windows and OSX, although it did seem to be a bit slower.

It'd be good to know why if possible, it's just stumped me while trying to install a load of npm binaries and it seemed like the permissions could not be set on the binaries until I used the NSF option.
