### ISSUE TITLE
Problem with Apache user and group settings

### ISSUE THREAD

**Issue by johnstephens** [scotch-io/scotch-box#62]
Scotch/box—wow! I love it. Thank you!

Like the tin says, **it just works** for a lot of the sites I'm working on.

But when I tried using it for a [Processwire][pw] installation, I ran into a problem, and the only way I could solve it was by manually editing the scotch/box apache2 config file, [as outlined here][fork], by changing this:

    User ${APACHE_RUN_USER}
    Group ${APACHE_RUN_GROUP}

to this:

    User vagrant
    Group vagrant

Then, it works!

But if I have to destroy the box, `up`ing it again restores the original Apache config (as it should).

Is it a bug in my scotch/box instance that I have to change those settings? Is there any way I can persist the custom Apache config using my provisioning script or other method?

Thanks for any guidance on this!

[pw]: https://processwire.com/
[fork]: https://github.com/forkcms/forkcms/issues/1020#issuecomment-76196959

**Comment by ncerminara** [comment]
I'll update a fix for this in 2.0. Thanks for bringing it to my attention

**Comment by ncerminara** [comment]
The only way to persist is to do it through vagrant (shell script, chef, puppet, some sort of provisioning)

**Comment by johnstephens** [comment]
Thanks! Will this issue send me a notification when it changes?

**Comment by ncerminara** [comment]
Yeah it should...

**Comment by ncerminara** [comment]
UPDATED! Run `vagrant box update`
