### ISSUE TITLE
Recipe or Manifest to rebuild Scotchbox locally

### ISSUE THREAD

**Issue by Pluto1010** [scotch-io/scotch-box#63]
Hey guys,

would be nice if you could provide a recipe for Chef or a manifest for Puppet, Ansible, Salt, (whatever) to make it possible to rebuild the ScotchBox with Packer locally for myself.

Thanks!

**Comment by r4j4h** [comment]
+1 Or at least share how you built it to empower others to also provide high quality packaged environments :]

**Comment by ncerminara** [comment]
@r4j4h I did a similar method here: https://scotch.io/tutorials/how-to-create-a-vagrant-base-box-from-an-existing-one

Obviously learning and using provisioning tools is a better method though.
