### ISSUE TITLE
Different provider?

### ISSUE THREAD

**Issue by jasonhjohnson** [scotch-io/scotch-box#64]
Hi, 

I'd like to use this but I use Parallels as my vagrant provider. When I 'vagrant up' I get a message saying my provider isn't supported.

Any ideas?

Thanks,
Jason

**Comment by ncerminara** [comment]
Unfortunately, I don't have any plans to support anything besides VirtualBox right now. Let me leave this open and make it enhancement though just in case

**Comment by badlydrawnrob** [comment]
I'd like to get this working with `vagrant up --provider vmware_fusion` — unfortunately I've already bought the damn plugin license without checking if scotch/box works! (I just assumed, seems like fusion boxes aren't overly popular but I've read performance is better).

I might give this a go on Virtual Box, but had issues with `vagrant up` not working with VB 5.0. So, might give [Laravel Homestead](https://medium.com/@mattcollins_6/setting-up-a-local-dev-environment-for-craft-cms-using-laravel-homestead-2724be3954a5) a go for the time being.

Seems quite a lot of work compared to Mamps/Ampps mind you ;)

**Comment by ncerminara** [comment]
Sorry - right now I have no plans to support Scotch Box 2.0 on any other providers but Virtual Box.

Scotch Box 3.0 probably will be more robust, but not this iteration unfortunately.

**Comment by c-fitzmaurice** [comment]
I know this is closed, but any timeline on 3.0 support of vmware_fusion?

**Comment by ncerminara** [comment]
Unfortunately, there are no plans for this
