### ISSUE TITLE
Access from different PC on local network

### ISSUE THREAD

**Issue by guilhermemarconi** [scotch-io/scotch-box#65]
Hi,

How can I access the box from another PC in my local network?
Here at work some partners in the office likes to see how the projects are going, and access from their own PCs would be really nice.

I saw that it is possible on [Vagrant's Networking Documentation][1] but couldn't make it.

_PS.: I already have Vagrant Share configured, but is not exactly what I'm looking for right now._

[1]:http://docs.vagrantup.com/v2/getting-started/networking.html

**Comment by povrazor** [comment]
Open up the Vagrantfile and add a line:

config.vm.network "public_network"

Next time you start vagrant, it should acquire an IP on your local network.

**Comment by guilhermemarconi** [comment]
@povrazor 

This is the `config.vm.network` config on my Vagrantfile:

    config.vm.network "public_network", ip: "192.168.33.10"

This way it doesn't work even in my PC.

**Comment by povrazor** [comment]
No IP, just public_network. It'll figure out what IP to use via DHCP.

**Comment by guilhermemarconi** [comment]
But, how can I know the IP?

I ran `ipconfig` and none of `IPv4` Adresses listed for Vagrant VM won't work.

**Comment by povrazor** [comment]
Do a `vagrant ssh` and run `ifconfig` while connected. It's probably eth2.

**Comment by guilhermemarconi** [comment]
NICE!

It was `eth1` but thanks anyway!

**Comment by Madses** [comment]
eth0      Link encap:Ethernet  HWaddr 08:00:27:3a:0b:5b  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe3a:b5b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1907 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1761 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:145612 (145.6 KB)  TX bytes:136984 (136.9 KB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:97:c5:84  
          inet6 addr: fe80::a00:27ff:fe97:c584/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:29 errors:0 dropped:0 overruns:0 frame:0
          TX packets:73 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2494 (2.4 KB)  TX bytes:20174 (20.1 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:96 errors:0 dropped:0 overruns:0 frame:0
          TX packets:96 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:41809 (41.8 KB)  TX bytes:41809 (41.8 KB)

vagrant@scotchbox:~$ ls
cant figure which one

**Comment by nahuelbrandan** [comment]
And then how to connect?

**Comment by mikekasprzak** [comment]
@Madses eth0 is the only one with inet address (i.e. IPv4, `10.0.2.15`).

@nahuelbrandan As mentioned, `vagrant ssh` to connect to the machine. Once connected, you can `ifconfig` or `ip addr` to list the IP addresses assigned to the machine. One of those will likely be an address on your local network. Assuming that's `192.168.1.44`, you would type `http://192.168.1.44/` in the browser.
