### ISSUE TITLE
How to import dump of mysql database to scotchbox and create database and usernames

### ISSUE THREAD

**Issue by Danjavia** [scotch-io/scotch-box#67]

**Comment by ncerminara** [comment]
https://box.scotch.io/

Scroll down to the "database" section. It's already mostly setup.

**Comment by Danjavia** [comment]
yes but how can import the sql file within vagrant scotchbox?

**Comment by ncerminara** [comment]
Use sequel pro to do it

**Comment by Danjavia** [comment]
Im on windows

**Comment by ncerminara** [comment]
You can download navicat or heidiSQL to do the same thing. You just need a Database client.

**Comment by Danjavia** [comment]
Ok so perfect thanks ;)

**Comment by devninjajeremy** [comment]
Actually, this would still be a pretty good feature. Take for instance the db for a custom application. Which would need data to go with it. Being able to run a .sql file that is in a folder automatically and it create the database, tables and insert data without anyone doing a thing would be ideal. Then the only thing you would need to do to get a project up and going, no matter the project, would be vagrant up.

**Comment by Eoler** [comment]
Yeah, something like this:
https://github.com/Eoler/scotch-box/commit/9c0173cad32d8fe8060168f9f468defcae9a3fa2

**Comment by devninjajeremy** [comment]
Exactly. Although to make it more streamline to where you dont have to mess with the code in scotchbox, just have a folder designated for sql files and it picks up all of them and runs them. So in theory, just adding a .sql file to a folder would allow you to import your db.
