### ISSUE TITLE
An error occurred while downloading the remote file.

### ISSUE THREAD

**Issue by jonnyhaynes** [scotch-io/scotch-box#70]
Getting an error when trying to `vagrant up`.

Error reads: 

```
SSL read: error:00000000:lib(0):func(0):reason(0), errno 54
```

Basically get's about 20% of the way in then just grinds to a halt before showing the above error code.

![screen shot 2015-05-27 at 16 12 49](https://cloud.githubusercontent.com/assets/1654845/7839663/7200aa6c-048b-11e5-9b0f-be6ff8b48417.png)

This is following the instructions at: https://box.scotch.io

Any ideas?

**Comment by ncerminara** [comment]
You can download the box manually here: https://drive.scotch.io/scotchbox/1.5.0/scotch.box

**Comment by jonnyhaynes** [comment]
Just so you're aware for future reference, I actually ended up getting this to work by removing the vagrant stuff, then running `vagrant init scotch/box; vagrant up --provider virtualbox` in that empty folder. This worked first time.
