### ISSUE TITLE
Secure connection to wordpress.org fails

### ISSUE THREAD

**Issue by kyotoprotokollet** [scotch-io/scotch-box#71]
I'm using Scotchbox as my local Wordpress environment. Lately I've been getting a very sluggish behavior in the backend, when visiting certain pages that tries to set up a secure connection to wordpress.org.

I get the following message: 
An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.)

I'm wondering if there is a setting or something in the Scotchbox that needs to change, or If I need to install something on it to enable ssl connections to external pages?

**Comment by ncerminara** [comment]
I don't think this is Scotch Box related.

**Comment by riveramauro** [comment]
I had the same issue and I was able to fix it resolving the Wordpress IP in the VM.

SSH into the VM, then edit the `/etc/hosts` file and add `66.155.40.202 api.wordpress.org`.

Got it from http://stackoverflow.com/a/30355347

**Comment by kyotoprotokollet** [comment]
Looks like that did it for me too, thanks!
