### ISSUE TITLE
Connectint to mysql DB hosted on a remote server via mysql tunnel

### ISSUE THREAD

**Issue by zRosenthal** [scotch-io/scotch-box#73]
Notes: I am running Ubuntu 14.04 and have recently started to use scotch-box because of it's simplicity

I am trying to connect to a remote mysql DB, the DB is hosted on a remote server, I am using vagrant/scotch-box I have tried to use putty(as I have done in the past on my windows desktop) and type in the remote server ssh info then  go to   SSH->Tunnels and enter 8989 as my source port and mysql-user:3306 as my destination (local and auto boxes selected)
![selection_001](https://cloud.githubusercontent.com/assets/9902783/7924824/8e82b464-088c-11e5-9a7c-42a97283d608.png)

I have also tried to connect via command line(as I have previously done on my mac laptop) with no success using the below command
ssh my_user_name@my_server -L 8989:mysql-user:3306 -N

This is how I connect to the database in my php application
![selection_002](https://cloud.githubusercontent.com/assets/9902783/7924898/35a79098-088d-11e5-9006-59e7ebb5742e.png)

I can understand why this doesn't work because the application is running on the virtual machine and not my local computer. 
I have tried the command above while ssh into the virtual machine
I have also tried changing the local port when connecting in putty with no success.

Any insight is greatly appreciated.

**Comment by ncerminara** [comment]
Hey. I'm not sure if this is even related to Scotch Box TBH.
