### ISSUE TITLE
 npm install error

### ISSUE THREAD

**Issue by sylvhama** [scotch-io/scotch-box#74]
Hello,

I started to use Scotch Box for the first time, I used to install my dev dependencies via my personal *package.json*.

    {
    "name": "myApp",
    "dependencies": {},
    "devDependencies": {
    "gulp": "*",
    "gulp-util": "*",
    "gulp-plumber": "*",
    "gulp-coffee": "*",
    "gulp-concat": "*",
    "gulp-uglify": "*",
    "gulp-imagemin": "*",
    "gulp-compass": "*",
    "gulp-minify-html": "*",
    "gulp-minify-css": "*",
    "gulp-useref": "*",
    "del": "*",
    "require-dir": "*"
    }
    }
But when I run *npm install* I see many errors like:

- npm ERR! Please try running this command again as root/Administrator.
- npm ERR! Linux 3.2.0-23-generic
- npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"

Adding *sudo* does not change anything. If I write *whoami* I get vagrant.
Do you have any idea? I just want to have my "personal" node_modules for each project I make.

**Comment by sylvhama** [comment]
I found a workaround to my issue:
After trying solutions posted by others users *npm install --no-bin-links* or *npm install -g* or running those commands as root, I decided to move my *package.json* to my */home/vagrant/*. From there I can run *sudo npm install*, all my packages have been downloaded successfully. To finish, I have created a symbolic link from my project (*/var/www/public/my-project*) to the *node_modules* directory located in my home.

**Comment by apricot13** [comment]
I'm having this issue as well!

**Comment by sylvhama** [comment]
I tried to follow this Ticket on VirtualBox website about Windows symbolic link creation but it did not work... https://www.virtualbox.org/ticket/10085

**Comment by apricot13** [comment]
My fix for this was to just use git bash and install node etc on my windows machine in the shared folder to do all of the grunt/bower work. Its not perfect but it works! I'm sure the same method would work on mac too (I'll probably have to test it out soon)

**Comment by ncerminara** [comment]
For now, just do:

```bash
sudo npm install blah
```
