### ISSUE TITLE
Apache Environment Variables

### ISSUE THREAD

**Issue by WolfieZero** [scotch-io/scotch-box#76]
I've not looked yet into an actual build but looking through the docs and code it doesn't look like an easy way to set a apache host's environment variables (useful for Yii and Laravel)?

Anybody have any experience of doing this in Scotch Box?

**Comment by ncerminara** [comment]
https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#creating-environment-variables
