### ISSUE TITLE
Ubuntu 14 & MySQL 5.6?

### ISSUE THREAD

**Issue by KerryJones** [scotch-io/scotch-box#77]
Are you looking at either creating a secondary box or updating this one to the latest Ubuntu and MySQL?

**Comment by ncerminara** [comment]
I'll be updating this one. Thanks

**Comment by ncerminara** [comment]
UPDATED! Run `vagrant box update`

I couldn't add MySQL 5.6. You'll have to do it manually. It required a little too much memory to make it worth it. It would have forced me to dictate a minimum memory requirement to use this.
