### ISSUE TITLE
Not able to share files with guest

### ISSUE THREAD

**Issue by caseyrlentz** [scotch-io/scotch-box#78]
I'm not able to share files from my local machine to the guest machine. Perhaps i'm doing something wrong. I'm new to vagrant as well as scotch box so any help would be great. Vagrant says that if you touch any file next to the vagrant file it will be shared on the guest machine. This is not working for me with Scotch Box.

Thanks in advance!

**Comment by EdEichman** [comment]
Did you check /var/www on the vagrant box? Things from the top level should be there.
I did vagrant up on the C:\user\ed\Vagrant\devbox folder, and created a file called bob.txt in windows, and found it at /var/www/bob.txt. Creating /var/www/bob2.txt on the vagrant machine showed up on C:\user\ed\Vagrant\devbox\bob2.txt
In your vagrant file, check the value of config.vm.synced_folder to see where it's mounting.

**Comment by caseyrlentz** [comment]
Thanks very much for your help!
