### ISSUE TITLE
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.

### ISSUE THREAD

**Issue by chadmazilly** [scotch-io/scotch-box#79]
I started receiving this prompt when "vagrant up"ing after upgrading from scotch-box 1.5 to 2.0. I'm running Windows 7 and VirtualBox 4.3. I've found a potential fix here: https://github.com/mitchellh/vagrant/issues/5153. Is this new annoying prompt specific to my environment configuration, or is anyone else receiving this?

**Comment by ncerminara** [comment]
Can you try adding this to your `Vagrantfile`:

```bash
config.ssh.username = "vagrant"
config.ssh.password = "vagrant"
```

There seems to be a bug with packaging boxes on Vagrant 1.7.x that causes this. You can do this in the meantime.

**Comment by ncerminara** [comment]
Going to leave this open until a better fix is in place where we don't have to worry about it.

**Comment by chadmazilly** [comment]
That eliminates the prompts for me. Thanks!

**Comment by ncerminara** [comment]
Searching for a fix. You might also want to try deleting your known_hosts file on your machine.

So: `rm ~/.ssh/known_hosts`.
