### ISSUE TITLE
Can not sync folder with guest machine

### ISSUE THREAD

**Issue by the-ruby9323** [scotch-io/scotch-box#80]
After run "vagrant up", guest machine booted and ready but synced_folder did not work.
Please help me to solve this, I am new to vagrant.
Below is message from the command line after I ran "vagrant up":

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'scotch/box'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'scotch/box' is up to date...
==> default: Setting the name of the VM: scotch-box_default_1436930901808_31938
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version o
f
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you
 see
    default: shared folder errors, please make sure the guest additions within t
he
    default: virtual machine match the version of VirtualBox you have installed
on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.28
    default: VirtualBox Version: 5.0
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /var/www => E:/work/savvy-shopping/scotch-box
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
chown: changing ownership of ???/var/www???: Not a directory

I'm using Vagrant 1.7.3, Virtual 5.0 on Windows 7 x64

**Comment by ncerminara** [comment]
For anyone who reads this. Chances are it was Virtual Box 5.0. It's not compatible with Vagrant.

Right @the-ruby9323?

**Comment by the-ruby9323** [comment]
@ncerminara  right, i'm using Virtual Box 4.3.28 now, and it works. About a month ago, scotch box worked find with Virtual Box 4.2, the issue just started at this week
