### ISSUE TITLE
charset and collation database

### ISSUE THREAD

**Issue by jasperf** [scotch-io/scotch-box#81]
What is the collation and charset for the database server of scotchbox and the sctochbox database? Had issues and had to affirm utf8 for charset and collation using WordPress Constants
```
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', 'utf8_general_ci' );
```
to load all characters OK so was wondering why that was needed.

**Comment by ncerminara** [comment]
You can create a new database and set your own if needed. The database "scotchbox" is just the out-of-the-box solution. It should be `UTF-8 Unicode (utf8)`
