### ISSUE TITLE
Error with Synced Folder on Yosemite?

### ISSUE THREAD

**Issue by billcava** [scotch-io/scotch-box#82]
When I tried a straight up plain vanilla setup by cloning the GitHub repo, on a Mac running Yosemite 10.10.4 (14E46) using Vagrant (Version: 1.6.5) and Virtual Box (Version: 4.3.20r96996), I was given a 404 when I tried to browse the site from the host. After troubleshooting, I found that things worked as expected if I changed this line:

`config.vm.synced_folder ".", "/var/www", ":nfs => { :mount_options => ["dmode=777","fmode=666"] }”`

to 

`config.vm.synced_folder ".", "/var/www"`

**Comment by billcava** [comment]
FYI, upgraded Vagrant to version 1.7.3 and see same behavior.

**Comment by serhioli** [comment]
Seems like the nfs daemon stopped...
Check your ```nfsd``` in terminal by executing ```nfsd status```
You must get in echo something like:
```nfsd service is enabled```
```nfsd is running (pid 4011, 8 threads)```

**Comment by ncerminara** [comment]
That sounds right. Try no NFS with:

```ruby
config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
```

**Comment by serhioli** [comment]
One more thing about my env - Yosemite 10.10.4, Vagrant 1.7.3, VirtualBox 5.0.0r101573. Everything works fine! Try to update your tools and I'm on 90% sure that nfs will start

**Comment by jiannelli** [comment]
It happened the same on my Ubuntu 14.04, I commentend the nfs part to fix it.
To improve usability and the motto "That Just Works" I would advice to change the Vagrantfile leaving the nfs option commented.  The users that need performance could install nfs and configure the Vagrantfile with nfs enabled.

config.vm.synced_folder ".", "/var/www"
    #, :nfs => { :mount_options => ["dmode=777","fmode=666"] }

**Comment by ncerminara** [comment]
You're right, I may consider this. Let me think about it.

I was under the impression Vagrant would fallback if NFS isn't installed.

**Comment by jiannelli** [comment]
Under ubuntu it doesn't fallback, It shows an error message saying that you
should install/configure nfsd.

It seems that the same Vagrantfile works just fine under windows, because
nfs does not work under windows:
*"Windows users:* NFS folders do not work on Windows hosts. Vagrant will
ignore your request for NFS synced folders on Windows. "
http://docs.vagrantup.com/v2/synced-folders/nfs.html

**Comment by ncerminara** [comment]
I wish there was a way we could do: `vagrant up --nfs` vs changing the `Vagrantfile`. I'm trying really heard to keep this as simple / stripped down as possible.

I think I'll just remove it

**Comment by jiannelli** [comment]
Hi, I couldn't find an option like that in the vagrant documentation.
If you add an if to the Vagrantfile you can call vagrant using vagrant up
but also using an env variable like so:
USE_NFS=yes vagrant up

Vagranfile:
Vagrant.configure("2") do |config|

    config.vm.box = "hashicorp/precise32"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"

    if ENV['USE_NFS']
    config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options =>
["dmode=777","fmode=666"] }
    else
    config.vm.synced_folder ".", "/var/www"
    end
end

**Comment by ncerminara** [comment]
Ugh - I wish this didn't cause so many issues. NFS removed by default per "dead simple" / "just works" philosophy. https://github.com/scotch-io/scotch-box/commit/5ae1880e7c40780199c5bcadce16ebe3181023b5

**Comment by ianrobertdouglas** [comment]
I've been trying out scotchbox, but also get 404 on internal links in sites. I've tried both with and without NFS, with reloads of vagrant, but it still doesn't work. Any pointers?
