### ISSUE TITLE
wp-cli in the box

### ISSUE THREAD

**Issue by slaFFik** [scotch-io/scotch-box#83]
Would be nice to have it available out of the box. So developers won't need to install it again and again

**Comment by kjbrum** [comment]
+1

**Comment by ncerminara** [comment]
I'll add this eventually but for now you guys can just do this for your Vagrantfile. It might appear red, but is working perfectly:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }


    config.vm.provision "shell", inline: <<-SHELL, privileged: false

        # Install WP CLI
        echo "Let's install WP-CLI"
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
        wp --info

    SHELL

end
```

Going to leave this open for others and as a reminder

**Comment by slaFFik** [comment]
Yeah, I did that in vagrantfile as well, but copy-pasting for every project is boring :( And downloading on every provisioning is overkill, imo.
And it's better to use 
```
curl -s https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar > wp-cli.phar
``` 
instead of 
```
curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
```
to prevent displaying lots of red strings :)

Hopefully, this will be included in the box in the nearest future. 

Thanks, Nicholas!

**Comment by ncerminara** [comment]
Awesome, great update to the `curl` command. Yes, this will get added in the next update

**Comment by slaFFik** [comment]
Any news regarding next update of the box?

**Comment by ncerminara** [comment]
ADDED: https://scotch.io/bar-talk/announcing-scotch-box-2-5
