### ISSUE TITLE
mysql keeps stopping after some time

### ISSUE THREAD

**Issue by danielscarpim** [scotch-io/scotch-box#84]
Everything works fine, but after some time I start getting this error:
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'

If I restart the vm, everything starts working again.

**Comment by ncerminara** [comment]
Probably related to running out of memory. You working on a big project or on a machine with limited resources?

Can you try provisioning with more memory by adding this to your `Vagrantfile`? See: http://docs.vagrantup.com/v2/virtualbox/configuration.html

```ruby
config.vm.provider "virtualbox" do |v|
  v.memory = 1024
  v.cpus = 2
end
```

Or even more:

```ruby
config.vm.provider "virtualbox" do |v|
  v.memory = 2048
  v.cpus = 2
end
```

**Comment by danielscarpim** [comment]
You are probably right. I'm working with magento. It does use a lot of memory. I'll try that.

**Comment by ncerminara** [comment]
Cool I'm closing this then. I hit the same problems trying out MySQL 5.6 on this box. Just allocated a little bit too much resources.

**Comment by ncerminara** [comment]
And you can just do:

```
vagrant ssh
sudo service mysql restart
```

Instead of restarting the VM
