### ISSUE TITLE
git pull causing merge conflict in public folder

### ISSUE THREAD

**Issue by wernerdesign** [scotch-io/scotch-box#86]
I have been using scotchbox for WordPress development, dropping the WP install directly into the public folder (overwriting the default public/index.php in the scotchbox repo.) I decided to update my scotchbox from 1.5 to 2.0 by doing a quick pull, and it mangled my WordPress index.php file. No big deal, just a quick conflict resolution, but am I missing something in the way that the public folder is supposed to be used?

**Comment by ncerminara** [comment]
Ah, you're right. Didn't even think about that. You need to manually replace the file or ignore the public folder. Going to leave this open until I update the article.

**Comment by ncerminara** [comment]
BTW, the only thing that changed in the Vagrantfile is NFS for synced folders. Technically, nobody has to do this.

**Comment by wernerdesign** [comment]
Great, thanks. I think the NFS change is causing some issues too, keeps asking for admin pw after this prompt:
```
Preparing to edit /etc/exports. Administrator privileges will be required...
```
Oddly, [this thread](https://github.com/mitchellh/vagrant/issues/4495) seems to have fixed it, although I'm not sure if it's a permanent. I tested the config change as suggested...
```
config.vm.synced_folder "./", "/var/www/html", type: "nfs", nfs_export: false
```
...and then switched it back to the default config and now the prompt is not required.

**Comment by ncerminara** [comment]
Yeah... Just add this to your `Vagrantfile` for now:

```
config.ssh.username = "vagrant"
config.ssh.password = "vagrant"
```

We're working on a fix / explanation.

**Comment by wernerdesign** [comment]
Well, I had actually included those in my vagrantfile config, and was still getting the prompt. I thought it might be some sort of caching issue with virtualbox, like it was still trying to access the old box, but deleting the boxes altogether didn't help either.

Thanks-

**Comment by ncerminara** [comment]
NFS requires admin privileges to be created. I thought you we're being prompted with the Vagrant users password.

**Comment by wernerdesign** [comment]
Ah, sorry if I wasn't clear. So the password is required on every `vagrant up`? Any way around that?

**Comment by ncerminara** [comment]
Admin password is required for NFS. If you don't have to use it (just faster). You can just use default syncing:

```
config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
```
