### ISSUE TITLE
Composer won't update even with sudo

### ISSUE THREAD

**Issue by cerkauskas** [scotch-io/scotch-box#87]
Hello.
It seems like there is something with /var/www permissons. If I clone https://github.com/symfony/symfony-standard and then try to do composer update and nothing works. I've tried giving almost all PC resources (8GB ram, 4 cpus), but nothing changes. You can see [here](https://gist.github.com/anonymous/35a065da410cd64fc32c) my first try to do composer update. Then [sudo composer update](https://gist.github.com/anonymous/5ed20b754ea131f9d917). And I've created new scotch box and tried to do sudo compoer update (I thought non-sudo might create files), but results could be seen [here](https://gist.github.com/anonymous/50fb553c4ec9b29e2dd0).
By the way, if I do everything not in /var/www, but in /home/vagrant, everything goes okay with sudo composer update.
Please look into it.
Thank you. :)

**Comment by ncerminara** [comment]
Merging this: https://github.com/scotch-io/scotch-box/issues/94
