### ISSUE TITLE
Create GitHub releases (or at least tags)

### ISSUE THREAD

**Issue by joshdifabio** [scotch-io/scotch-box#88]
This repo could really do with a changelog and [GitHub releases](https://github.com/scotch-io/scotch-box/releases) (or at the very least, tags) so that:
* We can easily use older versions of Scotch Box, for example if we wish to use a PHP 5.5 box
* We can see when Scotch Box has changed and what is different

It's really easy to do this via the GitHub releases interface.

**Comment by ncerminara** [comment]
I was actually meaning to do that. Totally forgot. I'll do that soon

**Comment by joshdifabio** [comment]
Great, thanks.

**Comment by ncerminara** [comment]
Done

Note the Vagrantfile is backwards compatible and always looking for the most recent box. If you want to jump back to the older box, check this out: https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#want-the-older-box-back?

**Comment by joshdifabio** [comment]
You're a dude. Thanks.
