### ISSUE TITLE
Add xDebug to the box

### ISSUE THREAD

**Issue by jpjoao** [scotch-io/scotch-box#90]
Why not add xDebug (with remote access enabled) to make it the state of the art dev box?

**Comment by ncerminara** [comment]
Since this box has so many beginners, we decided to leave it out: https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#installing-xdebug

**Comment by EdEichman** [comment]
Hi jpjoao,

FYI, I had problems with xdebug and PHPStorm. I [wrote a blog post about my solution](http://rocinantesoftware.blogspot.com.es/2015/07/phpstorm-xdebug-scotchbox-20.html) in case anyone else has the same problem.

Thanks,
Ed Eichman
Cambrils, Spain

**Comment by ncerminara** [comment]
Awesome share. I'm going to add this to the docs.

**Comment by ncerminara** [comment]
Reopening this until I do

**Comment by jpjoao** [comment]
@EdEichman I made it work by adding only this to /etc/php5/apache2/php.ini file:
```
zend_extension="/usr/lib/php5/20131226/xdebug.so"
xdebug.remote_enable = on
xdebug.remote_connect_back = on
```
No need for the specifics IP and port as you did. Looks simpler to me, don't you think?

**Comment by EdEichman** [comment]
@jpjoao Using PHPStorm? And "Validate Debugger Configuration on Web Server" did not give a "Remote host is configured as 'localhost' despite server host is probably not local" warning?

xdebug.remote_port does look redundant... I'll remove that from my post, thanks!

**Comment by jpjoao** [comment]
I am currently debugging with the configuration I posted. I do have a hostname configured and that can be what made it work without the IP thing. Give it a try. (btw I am using PHPStorm 9)

**Comment by EdEichman** [comment]
@jpjoao I also have a hostname configured and am using PHPStorm 9. But only got rid of the warning with the xdebug.remote_port setting. NOTE: It was only a warning, but I like to clean warnings - I assume it would work without remote_port set.

**Comment by jpjoao** [comment]
I am not getting any warning whatsoever... But if in some configurations you do get them I'd recommend to have in the docs all lines.

Cheers

**Comment by ncerminara** [comment]
@EdEichman Added a link back to your post in the 2.0 blog post. Thanks

**Comment by iuriimattos** [comment]
enter ssh session and install this package "sudo apt-get install php-xdebug"
