### ISSUE TITLE
Different databases across multiple domains and backing up / preserving database schema

### ISSUE THREAD

**Issue by Dobby89** [scotch-io/scotch-box#93]
Because I don't want to run multiple instances of scotchbox on my machine at once (for space and memory reasons), I've just [set up the Vagrantfile](https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#multiple-domains-(virtual-hosts)) so I can run more than one site on the one VM, which is working fine.

**Using this setup, is there a way to run more than one database on the VM at once, so I can have a database per domain?**

Also, is there a good way to preserve a database after running `vagrant suspend`? This command removes all database schema and unless I'm missing something, I don't want to have to remember to backup my database everytime I suspend the VM and then have to import it again when I come back to work on it. **Is there a way to preserve databases after you've suspended the VM?**

**Comment by ncerminara** [comment]
You can create as many databases as you want. Just connect with Sequel Pro and click "Add Database".

<img width="590" alt="screen shot 2015-08-02 at 6 58 21 pm" src="https://cloud.githubusercontent.com/assets/1021163/9028487/92bff504-3948-11e5-8c20-f8753631e642.png">
<img width="617" alt="screen shot 2015-08-02 at 6 58 26 pm" src="https://cloud.githubusercontent.com/assets/1021163/9028486/92be17c0-3948-11e5-8398-37c80b16ac42.png">
<img width="576" alt="screen shot 2015-08-02 at 6 58 43 pm" src="https://cloud.githubusercontent.com/assets/1021163/9028488/92c10afc-3948-11e5-837b-8b48fb057252.png">

**Comment by Dobby89** [comment]
Okay, thanks for that. I feel a bit stupid for not trying that....

But what about preserving the actual data in the database after `vagrant suspend`? Is there a best practice for this?

**Comment by ncerminara** [comment]
Yeah `vagrant suspend` will preserve it. It's basically the equivalent of freezing the state of it. You can also do `vagrant halt` which is the equivalent of shutting it down. Then, `vagrant destroy` is for terminating the instance.

I just do vagrant up and suspends when working on a project

**Comment by Dobby89** [comment]
But when I've tried `vagrant suspend` and come back to the database, it's empty again. Is there something I might be missing?

**Comment by ncerminara** [comment]
Run a test again. I use this everyday and the database is always preserved. Plus the command `vagrant suspend` wouldn't make sense for it to be missing. You might have done a `vagrant destroy`

**Comment by Dobby89** [comment]
No, the database schema is definitely being removed.

Here's what I'm doing:

* `vagrant up`
* Check the database - empty
* `vagrant ssh`
* `cd /var/www/website.local/laravel-app`
* `php artisan migrate`
* Check the database - it's got tables
* `vagrant suspend`
* `vagrant up`
* Check the database - empty

**Comment by ncerminara** [comment]
Here's a video of it working for me: http://www.filedropper.com/example_1

**Comment by ncerminara** [comment]
Something weird must be going on
