### ISSUE TITLE
Disable OPcache

### ISSUE THREAD

**Issue by benjamincrozat** [scotch-io/scotch-box#95]
Hello,

Scotch Box is a intended to be a development environment. Why is Zend OPcache enabled by default? Currently, I perform a search and replace on provision like so:
```shell
sed -i 's/;opcache.enable=0/opcache.enable=0/g' /etc/php5/apache2/php.ini
```

If a lot of beginners use Scotch Box, they'll quickly get crazy because of this.

**Comment by ncerminara** [comment]
Caching is enabled. But it shouldn’t matter since files are automatically invalidated when they are changed. Right?

**Comment by benjamincrozat** [comment]
I had to wait ~10 seconds to refresh my site. This was very annoying (easily fixed though). And really, you use Scotch Box for development, OPcache should not be enabled. This is non-sense. :(

**Comment by ncerminara** [comment]
Sounds like some weird VirtualBox out of sync issue. But I'll disable it. You're right. Good call

**Comment by ncerminara** [comment]
This is added by default now: https://scotch.io/bar-talk/announcing-scotch-box-2-5

**Comment by jbinfo** [comment]
I think, we must have a doc on how to enable it somewhere, by default is disabled but we need to write a documentation on how to enable it.

**Comment by ncerminara** [comment]
Took note here to add to the docs: https://github.com/scotch-io/scotch-box/issues/146

Super easy though:

```
vagrant ssh
sudo vim /etc/php5/apache2/conf.d/user.ini
```
