### ISSUE TITLE
change public to public_html

### ISSUE THREAD

**Issue by stevieg83** [scotch-io/scotch-box#97]
our projects production server runs from public_html as our doc root, how can we change it?

**Comment by ncerminara** [comment]
Check this out: https://github.com/scotch-io/scotch-box/issues/14

And check this: https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#changing-/public-to-/public_html 

Ha literally did this for someone this morning and updated the post
