### ISSUE TITLE
Possible to add PHP config to Vagrantfile?

### ISSUE THREAD

**Issue by djkush** [scotch-io/scotch-box#98]
So I understand that it's possible to SSH in to the box and change the php.ini from here but I was wondering if there was a quicker way to set defaults in the Vagrantfile?

For example, yesterday I needed to increase the `max_file_uploads`. Is it possible to stick this in the Vagrantfile and re-provision the box? 

If it's possible I think a lot of Scotch Box users (who are usually Vagrant novices, like me) would find this extremely useful.

Thanks.

**Comment by peterbrinck** [comment]
I've stumbled upon something called Provisioning, in Vagrant
It can install things for you at the first ``` vagrant up ```, and alter configs etc.

https://docs.vagrantup.com/v2/provisioning/index.html

**Comment by djkush** [comment]
I've seen that page.... Way over my head unfortunately - Standing on the shoulders of giants here!

**Comment by ncerminara** [comment]
Two ways:

### Regular Server Way

After running `vagrant up`. Do: `vagrant ssh`. You are not SSH'd into this "server". Just add:

```
upload_max_filesize = 100M
post_max_size = 100M
```

To the bottom of:

```
/etc/php5/apache2/conf.d/user.ini
```

With Vim, that's:

```
sudo vim /etc/php5/apache2/conf.d/user.ini
# Add your lines
ESC :wq
```

### Vagrantfile Method

This will work, but will always tack on the lines at the end of the user.ini every single time the server's provisioned.

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

    config.vm.provision "shell", inline: <<-SHELL
        echo 'echo "upload_max_filesize = 100M" >> /etc/php5/apache2/conf.d/user.ini' | sudo -s
        echo 'echo "post_max_size = 100M" >> /etc/php5/apache2/conf.d/user.ini' | sudo -s
        sudo service apache2 restart
    SHELL

end
```

**Comment by kush1960** [comment]
@ncerminara thanks for this. I somehow missed your reply notification. The Vagrantfile method will come in very useful.
