### ISSUE TITLE
Adding alias by shell provisioning

### ISSUE THREAD

**Issue by Emetrop** [scotch-io/scotch-box#99]
I'm trying add a new alias to .bashrc file by shell provisioning like this:

    sudo echo "alias seleniumup='DISPLAY=:99 xvfb-run --server-args=\"-screen 0 1280x1024x24\" java -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver -jar /usr/local/bin/selenium-server.jar'" >> ~/.bashrc

But when is provisioning done and I check the .bashrc file it's not there. How can I do this properly?

**Comment by ncerminara** [comment]
This works for me:

```
    config.vm.provision "shell", inline: <<-SHELL
        sudo bash -c 'echo alias test="123"' >> /home/vagrant/.bashrc
        source ~/.bashrc
    SHELL
```

**Comment by mtpultz** [comment]
Hi @ncerminara, this doesn't seem to work for me using ScotchBox 2.5.  I did what you suggested, but I don't even see the .bashrc in `/home/vagrant`.  Any suggestions?

```bash
# Append Aliases
sudo bash -c 'alias cakephp="cd /var/www/cakephp"' >> /home/vagrant/.bashrc
sudo bash -c 'alias codecept="./vendors/bin/codecept"' >> /home/vagrant/.bashrc
sudo bash -c 'alias codeceptr="./vendors/bin/codecept run"' >> /home/vagrant/.bashrc
sudo bash -c 'alias codecepta="./vendors/bin/codecept run acceptance --steps"' >> /home/vagrant/.bashrc

# Install file now, without restart
source ~/.bashrc
```
